### ISSUE TITLE
Сохранение ref в cookies

### ISSUE THREAD

**Issue by nikdementev** [swaponline/swap.react#101]
Noxon ⚡️, [05.07.18 18:06]
чтоб в куки сохранялись swap.online/?ref=0x33134

Noxon ⚡️, [05.07.18 18:06]
0x33134 чтоб сохранались

Noxon ⚡️, [05.07.18 18:08]
сделай чтоб просто в куки писался ref из адресной строки

Noxon ⚡️, [05.07.18 18:08]
если его там нет

**Comment by noxonsu** [comment]
я сделал пока через cloudflare чтоб это было
