### ISSUE TITLE
сделать URL shortcuts

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/swap.react#102]
1. There should be a URL based orderbook, when you select a specific currency pairs, urls should change. example: swap.online/book#ETH-BTC. When opening such URL it should show you that orderbook.

![swap-url-base](https://user-images.githubusercontent.com/22708849/42370692-158eae86-8116-11e8-9687-a9f983e28042.gif)

2. There should be a URL for a `new order`. So you can send a link to an order to your buddy to accept. Example: swap.online/order#376483463323

3. There should be a URL for every `accepted order`. Need to think very well how to identify the order without having to store order index. Hash of offer? When you visit accepted order URL you should not only see the progress, but be able to cancel it if possible, or to make a refund on expired order.

**Comment by vladiuz1** [comment]
I think its a good idea for a decentralized way to create a unique `order_id`. This id can be used as parameter to order link. 

There are two steps of an atomic swap of course:

1. order matching (mostly off chain, using ipfs pubsub)
2. atomic swap (once the order has been matched)

It would be a very good option for the identifier of both steps of the order to be identical, so the following is possible:

1. I (as marketmaker) sent you a link to an order to sell my bitcoin.
2. You as buyer of bitcoin, visited the linked, accepted the order, and started the swap.
3. Your phone lost connection, or got turned off, or whatever happened.
4. You turned your phone back on, and got the same link from a chat with your buddy, visited it, and saw the atomic swap at the stage where it got stuck. note: (using THE SAME link you got from me to initiate the order.)
5. You waited enough to finish all steps of the atomic swap. Now the link is always showing a page that says the order was complete, with links to respective transactions in both blockchains.

In order to make such scenario possible, it would be good to have a good way to generate order_id and it should match swap_id in the blockchain.

### Proposal

I propose using hash(secret).hex() as such id.

### Rationale

It ensures uniqueness by design. A market maker will need to be the keeper of the secret. Market maker is a better secret keeper anyways, because he is more technologically advanced. Market maker (as keeper of the secret) is motivated to create unique hashes, as hashes that are not unique do not guarantee a secure exchange. If your secret is known before you claim your crypto, secret keeper may loose his crypto.

Now we delegate unique order id generation to the market maker. To help him out, we could provide an API. We can keep all known swaps in a central db (or in the case of swaps involving ethereum for example, we could add functionality to swap smart contract to keep list of all previously used hashes).

Another problem is finding the right addresses (smart contract) in a decentralized way given the order id.

Having the hash of secret as a unique key to the swap also helps solve this problem. If you know other parameters of the swap, such as amount, destination addresses, and the smart contract generation algorithm is unified by protocol design, then you should be reconstruct the whole order.

Of course if you forgot the exact amount of your swap, and destination address (in the middle of swap), it will be very hard to get the pointers to swap contracts given the hash alone in many blockchains (in ethereum its possible if we use one smart contract for all swaps).

The solution to this problem shall lie in implementation rather than in protocol itself. The browser (or any other client) may keep all the data required to reconstruct all the details of the swap given the hash as the key. In the browser, you may save all the required data in localStorage. local storage allows key-value store, and all related order/swap data should be stored in key->value where key is the hash, and value is the rest of swap data collected as the order progresses.

This way, you can use the link containing just the hash of the secret to reconstruct all of the order from hash alone.

**Comment by caffeinum** [comment]
> Having the hash of secret as a unique key to the swap also helps solve this problem.

Maybe that would be a good idea to hash `IPFS peer + unique secret`, to eliminate stupid testing errors if someone uses `secret = 0` or `secret = 1`

> Example: swap.online/order#376483463323

It's better to use `base58` or `base64`

> The browser (or any other client) may keep all the data required to reconstruct all the details of the swap given the hash as the key. 

Yeah, current implementation does that

**Comment by caffeinum** [comment]
The downside to having a secret as an ID is that you have to generate a secret for each order.

ALSO, now one order can result in multiple swaps, so having one id for each of them would not be good.

**Comment by caffeinum** [comment]
Тут главный вопрос, хотим ли мы переиспользовать ордер для нескольких обменов. Если нет, тогда все проще с ID, но сложнее с ордербуком. Придется каждый раз, когда обмен начался, заполнять ордербук свежими ордерами.

Should we reuse one order for multiple swaps? It would help with orderbook, but it's harder on IDs.

If we reuse, we can't easily address swap by unique ID url.

If we don't reuse, we need to refill orderbook each time swap begins. We will flood the orderbook then.

**Comment by caffeinum** [comment]
I think it's better to reuse, AND each unique order URL makes sense only when visiting from YOUR account. Then, it takes `order creator IPFS peer id`, it takes your `IPFS peer id`, and the `secret hash`, and this gives unique triple.

**Comment by caffeinum** [comment]
Еще предложение: кодировать в айди ордера не только уникальный номер, но и объем обмена, пару, и даже тестнет/мэйннет.

**Comment by vladiuz1** [comment]
base58 is best for URLs, this is a fact.

> Maybe that would be a good idea to hash IPFS peer + unique secret, to eliminate stupid testing errors if someone uses secret = 0 or secret = 1

no, point is to identify order in blockchain if you lost it all data. with enough effort its possible if you can remember other parameter. if you comingle hash of secret with peerID, it is harder.

> Yeah, current implementation does that

very good.

> Should we reuse one order for multiple swaps? It would help with orderbook, but it's harder on IDs.

Absolutely not. Its not helping the orderbook, its unneded complexity of protocol that solves no problems.

> If we don't reuse, we need to refill orderbook each time swap begins. We will flood the orderbook then.

You could say that if this was the only vector to introduce flood, but unfortunately its not. Besides, i guess cases where you will get two requests for same order quite rare. Need other opinion. Also, to fight flood we can introduce a 'cancel order' broadcast.

Trading hash as order_id for order re-use IMHO is not a good solution from usability point of view.

Adding peer_id as an extra url parameter is ok imho. but it provides no additional identifying information. peer_id can be stored in your local storage. I understand that we don't leave in a perfect world, but why would anyone create an order where `secred=1` - its a bug, shouldn't be happening.

**Comment by caffeinum** [comment]
# encode whole order info into base58

This way, to restore the swap, you only need your browser history.

```javascript
{
  owner: { peer: "QmRLiZzgoVXPn3hd9JUNssF1AYhHmyjNRVTE1k6tNyDZx8" },
  buyCurrency: "ETH",
  sellCurrency: "BTC",
  buyAmount: 10,
  sellAmount: 1,
  secretHash: "c0933f9be51a284acb6b1a6617a48d795bdeaa80",
}

// PEER-BUY_CURR-SELL_CURR-BUY_AM-SELL_AM-SECRET_HASH
QmRLiZzgoVXPn3hd9JUNssF1AYhHmyjNRVTE1k6tNyDZx8-ETH-BTC-10-1-c0933f9be51a284acb6b1a6617a48d795bdeaa80

// base58 hash of the whole string (138 symbols)
4AYhNMahYvKsXx3Bg1pcMqZySdAHGWDGSYGapyZBVkQoAnu8dBE2sABDZrs1FNkZ4hhqFszbD8gN9xdBNg5zHX7bmph14NMhZAA8mXUNzBpnkUErKdzBfEEhhSca49DChg41Z2GMd

// or hash only the tail (121 symbols in total)
QmRLiZzgoVXPn3hd9JUNssF1AYhHmyjNRVTE1k6tNyDZx8-2GTFTDDEQ8szEND3g2iSwBPTmnmnxJdvzcc48WzsVkpe1vVj6MmLVEbnJzNKEHk8ApGqXLyrX
```

**Comment by noxonsu** [comment]
делаем без конвертации в баз64 тоесть прямо так

QmRLiZzgoVXPn3hd9JUNssF1AYhHmyjNRVTE1k6tNyDZx8-ETH-BTC-10-1-c0933f9be51a284acb6b1a6617a48d795bdeaa80


ср, 11 июл. 2018 г. в 18:29, Aleksey Bykhun <notifications@github.com>:

**Comment by vladiuz1** [comment]
Two more arguments supporting id = hash(secret) proposal:

### Proof of Cancellation.

order/swap ids = hash(secret)

Another argument supporting hash(secret) as identifier of both order and swap is Proof of Cancelation. Let's say you have a marketmaker advertising an offer to sell 1 btc. This orderid=hash(secret) = 0x0aE13ffFDC8b3511857554913c3e940958353dBD, in order to proove that the guy cancelled the order - create a handshake mechanism where each side of the order (taker and maker) sign the following metadata: (hash(secret), amount1, symbol1, amount2, symbol2)  with their private keys. And as long as both users signed the same metadata these signatures can be used as proof of cancellation by our central authority in order to check which party has indeed cancelled the order at any stage of the swap. Be it contract creation, sending crypto or secret sharing.

1. the user can prove at any stage of the order(swap) that he was 'cheated'
2. the reputation authority (us) can make sure this user indeed lost time (by locating his/her smart contract)

by having hash(secret) as an id of order/swap we simplify the proof of concellation mechanism.

### 2 entities need to be unique

1. The id of each order and each swap.
2. The secret of each atomic swap.

Instead of doing double work making sure both of entities are unique, we can merge these entities into one, having id = hash(secret). 

One can argue that the secret of cancelled order can be reused for active order. This is true, but the cost of creating a new secret can be neglected, besides this cost is compensated by the fact that we only need to calculate 1 unique entity instead of 2 (order id, and secret).

Since the choice of hash algorithm solved the collission problem for most blockchain and cryptography objectives, the chance of hash collision can also be neglected.

**Comment by vladiuz1** [comment]
The following info is enough to id the transaction in ANY blockchain:
```
{
  "QmRLiZzgoVXPn3hd9JUNssF1AYhHmyjNRVTE1k6tNyDZx8": { 
  ethDestination: "1DnqQ89hMobPkKqzVr6gaHiaUjKSkDa7wV" },
  btcDestination: "0x369f0505959de7ec1517d300532e5aee6b5c5b95" },
  ethAmount: 10,
  btcAmount: 1
}
```

every pair has a different algo, so its ok to embed the names of symbols into names of parameters.

also, there is no such thing as 'buy', 'sell'. its symmetric exchange, you exchange 10 eth for 1 btc... that's it, no buy or sell.

**Comment by nikdementev** [comment]
ae8637d58e1eee641ab36e36a150526e1fe02e12

**Comment by caffeinum** [comment]
это сделано @noxonsu

**Comment by caffeinum** [comment]
это сделано? @noxonsu

**Comment by noxonsu** [comment]
нет это не сделано, таск слишком большой, нужно раскидать на 3 мелких

**Comment by nikdementev** [comment]
мы сделали конвертацию оредера и редирект 
что еще нужно сделать по этому issue ?
