### ISSUE TITLE
autorefund если есть что рефандить то рефандить

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1028]
в боте есть авторефанд, надо и в свап реакте такое

**Comment by noxonsu** [comment]
можно сделать в два шага

- [ ] авторефанд срабатывает если ты находишься на странице со свапом
- [ ] если ты находишься где бы ты небыл на сайте

**Comment by caffeinum** [comment]
тогда полезно хранить время начала свопа

**Comment by nikdementev** [comment]
оно хранится

**Comment by nikdementev** [comment]
> можно сделать в два шага
> 
> * [ ]  авторефанд срабатывает если ты находишься на странице со свапом
> * [x]  если ты находишься где бы ты не был на сайте

второй на данный момент нельзя сделать
