### ISSUE TITLE
сделать вывод сообщения wrong address если человек пытается отправит на неправильный адрес биток

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1032]
![](https://airdb.wpmix.net/chrome_2018-11-26_11-00-15439732bd-ac59-493c-bed8-3d169242cbaa.png)

**Comment by noxonsu** [comment]
- [ ] проверил отправку биткоина минималка соблюдается
- [ ] проверил создание оредра минималка битка соблюдается
- [ ] проверил создание эфир
- [ ] проверил создание eth

**Comment by shendel** [comment]
Добавил проверку адреса на корректность используя утилиты кора
