### ISSUE TITLE
SEO задача. Просьба решить срочно. Метатеги на внутренних страницах.

### ISSUE THREAD

**Issue by 1maxim** [swaponline/swap.react#1034]
- [x] Существует нерешенная проблема с метатегами внутренних страниц.
Google не ест метатеги всех внутренних страниц, везде виден один и тот же тайтл как на главной (дескрипшен вовсе не видит), вбить нужно в Google "site:swap.online/bitcoin-wallet" чтобы проверить, скармливал эту страницу роботу, чтобы он переиндексировал, метатеги все так же не видит.

 
- [x] Ссылки необходимо привести к единому виду или всегда и везде в конце слеш "/" или всегда и везде его нет. Сейчас страница https://swap.online/bitcoin-wallet и страница https://swap.online/bitcoin-wallet/ являются дублирующими. Не важно какой вариант будет выбран, но с другого типа страниц надо проставить 301 редирект на выбранный тип.

- [x] Необходима страница с 404 ошибкой с свойственной для такой страницы структурой (а также отдающая не 200 а именно 404 ответ) и кнопкой вернутся на главную, сейчас ситуация вот такая https://swap.online/bitcoin-walletsdfsdfs
.

**Comment by noxonsu** [comment]
должно заработать все после того как в мейннет сбилдим
