### ISSUE TITLE
exchange: как то получилось запустить свап 0 ETH ⟶ 0 BTC

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1078]
пока пробуем повторить ошибку...

**Comment by shendel** [comment]
В partial на странице /exchange в определенных моментах
Удалось воспроизвести - если ввести какие то значения и получить расчет - кнопка Start становится доступной. Потом если сменить направления обмена - поля с суммами обнулялись, а кнопка Start оставалась доступной
Исправлено несколько мерджей назад
