### ISSUE TITLE
wallet: Failed prop type: Invalid prop `items[0]` of type `string` supplied to `Wallet`, expected `object`.

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#1089]
![image](https://user-images.githubusercontent.com/1909384/49536956-ccf47f80-f8d8-11e8-916c-8c5d88271293.png)

Branch: develop
Ошибка не появляется на testnet.swap.online, потому что она появляется только в режиме dev. Но тем не менее, там куда-то передаются неправильные данные. Это не очень круто

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/pull/1116
