### ISSUE TITLE
Новый формат заявок для ордербука

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#109]
Давайте аккуратно разберемся. Я предлагаю выписать для себя небольшую справку.

Во-первых, внутри кор сейчас следующие правила:
```javascript
// order:
{
  isMy: true
  buyCurrency: "ETH"
  sellCurrency: "BTC"
}
```

Это означает, что я ПОКУПАЮ ETH, ПРОДАЮ BTC, и далее я буду это называть ПРЯМЫМ направлением.

Тот же ордер в чужом ордербуке будет:
```javascript
// order:
{
  isMy: false
  buyCurrency: "ETH"
  sellCurrency: "BTC"
}
```

То есть поля buy и sell относятся только к создателю ордера. Для другого человека это неактуально, потому что он продает эфир, а покупает биткоин. То есть, для него направление ордера будет ОБРАТНЫМ.

# Прямые и обратные ордера

Для любой пары введем базовую и вторичную валюту. В ETH-BTC и TOKEN-BTC очевидно базовой будет биткоин. Продажа ETH будет ПРЯМЫМ обменом, а покупка – ОБРАТНЫМ. Запомнить можно так: раз она вторичная, то ее нужно ПРОДАТЬ, чтоб иметь надежную базовую валюту. :)

# bids / asks

В трейдерском мире используется терминология bid/ask, что означает заявку на покупку и на продажу соответственно. Запомнить тоже легко, *B*ID = *BUY*, A*S*K = SELL. То есть, bid = предложение купить ваши ETH от продавца, а ASK = просьба купить у него ETH. Опять логика со вторичной валютой нам помогает.

# Новый формат
Итого, я предлагаю для ордербука конвертировать заявки в примерно следующий формат:

```javascript
// order:
{
  type: BID | ASK,
  pair: "ETH-BTC", // всегда в таком порядке
  price: 0.07, // всегда цена ETH в BTC,
  amount: 10 // всегда количество ETH
}
```

Скрипты для конвертации есть у меня внутри бота в репо caffeinum/swap.core, позже опубликую.

@noxonsu @nikdementev 

https://github.com/swaponline/swap.react/issues/99#issuecomment-404207034

**Comment by noxonsu** [comment]
да бид и аск более профессиональная терминология, поддерживаю

**Comment by nikdementev** [comment]
единственное pair будет не удобно разбивать на составляющие

**Comment by noxonsu** [comment]
на хаке пообщался с прогером классических бирж, он говорит должен быть список пар, в каждой паре должна быть главная валюта (напр биткоин) и курс указывается по отношению к главной. она обычно пишется второй например JOT/BTC

**Comment by caffeinum** [comment]
закрываю, потому что есть https://github.com/swaponline/swap.react/issues/545
