### ISSUE TITLE
Miner fee label is not correct

### ISSUE THREAD

**Issue by 7flash** [swaponline/swap.react#1104]
## What is working wrong?
Miner fee label says that fee is 0.004

## What should happen instead?
It should says that fee is 0.00015

## Steps to reproduce
Click `Withdraw`

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

## Additional info
![screenshot from 2018-12-07 09-13-43](https://user-images.githubusercontent.com/4569866/49652702-e108c000-fa43-11e8-8cf6-28d2bc6a42bb.png)
![screenshot from 2018-12-07 09-13-19](https://user-images.githubusercontent.com/4569866/49652703-e108c000-fa43-11e8-992a-bf736907d500.png)

**Comment by caffeinum** [comment]
Я тоже заметил. Подумал, что лучше константу 0.004 уменьшить и заменить на 0.00015, тогда все правильно будет. Потому что выводить минимум 0.004 – это пипец, это почти тысяча рублей
