### ISSUE TITLE
Создать кнопку добавление газа при свапе

### ISSUE THREAD

**Issue by nikdementev** [swaponline/swap.react#114]

**Comment by noxonsu** [comment]
суть в том, что транзу которая уже отправлена и зависла можно просто еще раз переформировать и подписать но уже с другим газ прайсом (но nonce нужно чтоб был такой же) вроде так

**Comment by SabirICOadmin** [comment]
В идеале, создайте такую же прямую, как на эзерскане, чтобы чел мог выставлять значение газа
