### ISSUE TITLE
explorer.swap.online

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/swap.react#115]
## Swap explorer

need to create a swap explorer with list of all swaps performed with market makers with non-zero reputation.

Every swap must have amounts, transaction fees, links to transactions.

There should be a filter by pair, every pair must have a price/volume chart.

The id of every swap must be the hash of its secret

**Comment by noxonsu** [comment]
@chromebookman нужен десигн

**Comment by chromebookman** [comment]
Я не понимаю, что это за задача, и не понял что от меня нужно? О чем тут речь?

**Comment by noxonsu** [comment]
делает прототип криптоигорь, далее будет понятно что дизайнить

**Comment by chromebookman** [comment]
Ты хочешь чтобы  я променеджерил этот процесс, отдал Матвею и проконтролировал?

**Comment by chromebookman** [comment]
Issue moved to [swaponline/Office #296](https://github.com/swaponline/Office/issues/296) via [**ZenHub**](https://www.zenhub.com/)
