### ISSUE TITLE
history glitch in chrome

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/swap.react#116]
![history-problem](https://user-images.githubusercontent.com/22708849/42720577-eecb3086-8731-11e8-8380-a2063a0fe62a.gif)

same history item is added on every /history visit

fix needed

**Comment by nikdementev** [comment]
f589d5b04ac1cf5d438b4125bbb2800cb41bdba6

**Comment by vladiuz1** [comment]
cant close until updated on website

**Comment by nikdementev** [comment]
fedc71217f082edb6d9e0a469b7a68d9a0cee67d
