### ISSUE TITLE
withdraw: добавить ~x$ в поле когда где то укзаывается сумма в крипте на отправку 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1169]
![](https://airdb.wpmix.net/chrome_2018-12-20_00-31-438551c1eb-c0e9-4dc1-ba21-7138fb5fc889.png) то же самое с биткоином, эфиром и остальными где есть какойто трейдинг

**Comment by Pasha8914** [comment]
я сделаю
