### ISSUE TITLE
wallet: Can't send money to BTC address

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#1171]
## What is working wrong?

![image](https://user-images.githubusercontent.com/1909384/50253498-72404500-03fb-11e9-9813-11311686304e.png)

Адрес не проходит

## What should happen instead?

```
2Mu66hdTjpTLb47Sc6hxvohTzMmPqBqaJz8
```
https://test-insight.swap.online/insight/address/2Mu66hdTjpTLb47Sc6hxvohTzMmPqBqaJz8

это нормальный адрес

## Steps to reproduce

https://testnet.swap.online/
Send BTC

## Your system charateristics

- Browser: Chrome
- OS: Mac OS
- Mainnet or Testnet: testnet

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by shendel** [comment]
https://github.com/swaponline/swap.core/blob/e7d040210ab238780929490cd3836d74716354a2/src/swap.app/util/typeforce.js#L22
![image](https://user-images.githubusercontent.com/1880211/50299306-53d95880-0492-11e9-8b3e-a4d931ffc1d0.png)

35 символов, в коре допускается 34 :-|

**Comment by Pasha8914** [comment]
#208

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/pull/1183
