### ISSUE TITLE
при создании ордеров они не появляются у других (не редерятся)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#122]
когда кто то создает ордер то он сам не появляется у человека на странице, нужно в рекате что то сделать например перетйи на другую страницу и обратно

**Comment by noxonsu** [comment]
провели исследование, эффект проявляется только если перезагрузить страницу и очень быстро что то делать, никита сказал что перепишет какуюто часть

**Comment by nikdementev** [comment]
проблема в том что в react подписывается на эвенты от ipfs и если с ними что то не так он не рендерит страницу, я удалил лишние, но дальше надо менять только ipfs

**Comment by nikdementev** [comment]
03ee10d0d889071641185b58da1c851fcc0dcb4a
