### ISSUE TITLE
предлагаем пополнить баланс если нехватает фи(перед отправкой на баланс)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1225]
Мы приняли пул, но там есть проблема с тем, что логика немного нарушена, нужно выдавать только если не хватает денег на газ https://github.com/swaponline/swap.react/pull/1220#pullrequestreview-188284257

**Comment by noxonsu** [comment]
чеклист

- [ ] в браузере алисы очистить приватный ключ эфира, перезагрузить, таким образом на счету будет 0 эфира. 
- [ ] в браузере боба перекинуть на адрес алисы 2 свапа
- [ ] в браузере боба создать оредр на покупку 2 свапов
- [ ] в браузере алисы запустить этот ордер, дойти до шага когда потребуется заморозить свапы, так как нет эфира на газ об этом сообщить юзеру.

**Comment by sdwas** [comment]
На видео 2 теста подряд:
1. Баланс эфира 0.0003 - проходит своп и на финише просит пополнить баланс, тк баланс < 0.001
2. Теперь баланс 0.0002 - не проходит своп, останавливается на 4 шаге задолго до предложения пополнить баланс
https://yadi.sk/i/g-aTMY6pSAUZQg

**Comment by Pasha8914** [comment]
Ждем мержу пула в кор, улучшенный расчет фи 
redux: add setFee to reducer #1265

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/pull/1325
