### ISSUE TITLE
на странице балансов сделать возможность импортирования своего ключа

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#125]
там ниже где exit сделать еще import ключа, при нажатии появляется окно с выпадающим списком какой блокчейн импортировать (сейчас ETH и BTC MAINNET и BTC TESTNET) рядом imput куда собсно вводить ключ надо, но обязательно проверять на валидность (например тестнет и мейннет битка различаются). Собсно если сюда ввести приватники то они сохраняются в локарсторадже, нужно обязательно проверять чтоб на соотвествующем балансе было 0. иначе не давать импортировать ключ, писать "you must withdraww BTC funds otherwise they will be lost after replacing the private key"

**Comment by nikdementev** [comment]
#97
