### ISSUE TITLE
Идея. После создания ордера

### ISSUE THREAD

**Issue by apelsin555** [swaponline/swap.react#127]
Идея на будущее юзабилити. Сейчас после создания ордера просто окно создания закрылось и всё (и мы висим на той странице, где были и раньше, а это может быть и не главная). Создался он или нет, пользователю ещё не понятно может быть. Предлагаю внедрить что-нибудь, типа уведомления после создания ордера, типа ваш ордер успешно создан, его можно посмотреть "тут".

**Comment by nikdementev** [comment]
db91892f3c7a6cc8d9a2b1c782bf2a1a93d33e03
