### ISSUE TITLE
swap: текста BTC->TOKEN, TOKEN->BTC

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1273]
BTC->TOKEN
![](https://airdb.wpmix.net/chrome_2019-01-14_12-39-314f003593-9707-44b5-9b4b-f106789fd573.png)

**Comment by nthgness** [comment]
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/10322798/51119043-60a85c80-1844-11e9-8c2c-60dc31cbb672.png">
