### ISSUE TITLE
ETHTOKEN2BTC.js:253 Error: Secret already exists and it differs!

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1274]
## What is working wrong?

...Describe the bug briefly...
![image](https://user-images.githubusercontent.com/43392281/51107169-bd524a00-1839-11e9-8a67-c76c7f8c56a3.png)

## What should happen instead?

...Describe what do you think should happen instead in this situation...

## Steps to reproduce

Начинаем свап токены - бтс, баланса эфира нехватает на фи, пополняем , поялвляется ошибка

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [x] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [x] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...

**Comment by noxonsu** [comment]
исправили вроде, кор надо обновить https://github.com/swaponline/swap.core/issues/217

**Comment by Pasha8914** [comment]
ошибка возникла в обновленном тревисе
в скором времени постараюсь повторить баг, если не будет повторения 
17 января закрою
