### ISSUE TITLE
firebas грузит не абсолютный путь

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1277]
![](https://airdb.wpmix.net/chrome_2019-01-14_17-53-143b5585ce-a705-489d-8311-fbeb94457996.png)

**Comment by noxonsu** [comment]
не могу повторить, закрываю

**Comment by sdwas** [comment]
![screenshot_20190128_203907](https://user-images.githubusercontent.com/43396375/51831458-dc72d080-233d-11e9-933f-73e44c0b2069.png)
