### ISSUE TITLE
Белая страница при закрытии (крестиком) формы создания ордера

### ISSUE THREAD

**Issue by 7flash** [swaponline/swap.react#1283]
## What is working wrong?
When I close modal I see white secreen

## What should happen instead?
I expect to see page without error

## Steps to reproduce
![out](https://user-images.githubusercontent.com/4569866/51243254-aec77800-198a-11e9-8715-8f19ac784d8d.gif)

**Comment by 7flash** [comment]
Browser:
**Chrome**

**Comment by sdwas** [comment]
Не вышло повторить ошибку на последней сборке с ветки develop testnet:
https://yadi.sk/i/6-XKwUpPCE6fpw

**Comment by noxonsu** [comment]
подвтерждаю, не повторяется ошибка
