### ISSUE TITLE
бесконечные входящие реквесты на партиал ордер если уже идет свап

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1287]
удалось повторить баг с бесконечными входящими реквестам.

1. в одном браузере создаем ордер на продажу eth
2. во втором в /exchange запускаем свап, пока все хорошо
3. в третьем браузере повторяем п.2 и в первом браузере возникают бесконечные реквесты (но пока они видны только в локалсторадже, т.к. скрываются из за текущего свапа)

**Comment by noxonsu** [comment]
связано https://github.com/swaponline/swap.react/issues/976

**Comment by caffeinum** [comment]
Лēшå Быхун, [24.01.19 13:04]
куда я пришел пока что, это я поставил брейкпоинт везде где можно, и когда баг возникает, то во-первых, вызывается declineRequest в реакте,

Лēшå Быхун, [24.01.19 13:05]
ну понятно почему вызывается, там при начале свопа стоит команда "отправить decline" всем остальным реквестам

Лēшå Быхун, [24.01.19 13:05]
но дальше интересное: каждый раз, после того, как он вызывается, массив .requests.length увеличивается вдвое

Лēшå Быхун, [24.01.19 13:09]
инструкция примерно такая:
- создать партиал ордер в первом браузере
- со второго отправить партиал реквест
(
 - принять его в первом браузере
 - отправить еще один реквест во втором браузере
)(повторить N=(0,беск) раз)
- отменить его в первом браузере
- со второго отправить еще один
- принять его в первом браузере
- словить баг

Лēшå Быхун, [24.01.19 13:09]
вот это вот значение N найти бы

Лēшå Быхун, [24.01.19 13:10]
еще есть вероятность, что это может быть баг от того ,что он запрашивает partial request к ордеру, который был создан в ответ на partial request, но вообще говоря это не должно быть проблемой

Лēшå Быхун, [24.01.19 13:11]
[In reply to Лēшå Быхун]
плюс: точно известно, что .requests становится огромным массивом у того ордера, который был  создан именно в ответ на partial request, и создан он был нормально

**Comment by sdwas** [comment]
Бага поймана:

Повторить по-быстрому: https://yadi.sk/i/iYIHoT8gJsT_Fg

В двух словах: создаем два ордера. Начинаем своп с первым, во время этого свопа отправляем запрос на второй ордер. Итог: создатель ордеров на лопатках.
