### ISSUE TITLE
При создании order на продажу BTC, необходимо наличие ETH

### ISSUE THREAD

**Issue by Odny** [swaponline/swap.react#1293]
## What is working wrong?

При создании ордера на тестнете на продажу BTC и покупку ETH вылезает надпись о необходимости наличии ETH

## What should happen instead?

Надпись не должна появляться, ордер должен быть создан

## Steps to reproduce

-зайти на тестнет
-создать ордер на продажу btc и покупку eth

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...

## Additional info
![default](https://user-images.githubusercontent.com/46775958/51308229-b6eaea80-1a52-11e9-80df-60a256ef8d67.PNG)

**Comment by Pasha8914** [comment]
так пользователю все равно нужно иметь эфир на балансе, чтоб свап окончился, если он начнет свап без эифра и у него не будет возможности пополнить баланс эфира, он очень долго будет ждать возвращение своих средств
