### ISSUE TITLE
При создании ордера на продажу BTC и покупку ETH, существует проблема округления валюты (конвертация некорректна).

### ISSUE THREAD

**Issue by Odny** [swaponline/swap.react#1294]
## What is working wrong?

Зашел в ордер на продажу BTC(0,002) и покупку ETH(0.05957) со стороны продающего BTC. Отображается верно. Когда захожу со стороны продающего ETH, отображается сначала продажа 0.05957 ETH, а в итоге на кнопке 0,0596 ETH. Некорректное округление

## What should happen instead?

Вероятно, должно стоять многоточие после определенного знака, которое будет означать приблизительное округление, возможно при наведении в подсказке будет показываться точное число decimal.

## Steps to reproduce

- создать ордер на продажу
- нажать share и открыть в другой вкладке
- проверить конвертацию

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

![default](https://user-images.githubusercontent.com/46775958/51309420-6628c100-1a55-11e9-9dfb-50390087e5e0.PNG)

**Comment by Pasha8914** [comment]
округляет в большую сторону, в чем проблема?

**Comment by noxonsu** [comment]
цифры разные
