### ISSUE TITLE
swap: При выполнении ордера на продажу BTC и покупку ETH произошла ошибка на стадии создания контракта продающего ETH.

### ISSUE THREAD

**Issue by Odny** [swaponline/swap.react#1295]
## What is working wrong?

При подтверждении ордера завис шаг на создании контракта со стороны продающего ETH.  Валюта в наличии.

## What should happen instead?

Должен создаваться контракт и продолжаться транзакция обмена.

## Steps to reproduce

-создать ордер
-через кнопку share открыть со второго кошелька
-подтвердить транзакцию, убедившись в наличии средств
 
## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [x] yes
- [ ] no

## Are real funds at risk?

- [x] yes
- [ ] no

## Screenshots

![image](https://user-images.githubusercontent.com/46775958/51310246-51e5c380-1a57-11e9-9d64-c206bec708db.png)

**Comment by noxonsu** [comment]
подтверждаю, проблема именно с ETH, токен ок обновился

**Comment by caffeinum** [comment]
Возможно,
- слишком маленький gasLimit
- swap уже существует

**Comment by noxonsu** [comment]
проверил в одном из старых пулов такой ошибки нет

**Comment by Odny** [comment]
Проверил с другим ордером, теперь все работает
