### ISSUE TITLE
refund: При отмене ордера на продажу BTC и покупку ETH и возврата средств вылезает непонятная надпись.

### ISSUE THREAD

**Issue by Odny** [swaponline/swap.react#1296]
## What is working wrong?

При отмене ордера и нажатии кнопки возврата средств вылезает непонятная надпись.

## What should happen instead?

Необходимо исправить описание, вероятно ("Код возврата средств "и т.п.)
Вставить подсказку с инструкцией по возврату средств, куда этот код вставлять

## Steps to reproduce

- создать ордер
- через кнопку share открыть с другого кошелька
- попытаться обменяться валютой при наличии на счету
- отменить со стороны создателя ордера транзакцию

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

![image](https://user-images.githubusercontent.com/46775958/51310701-4e067100-1a58-11e9-97da-b01019c55af2.png)

**Comment by noxonsu** [comment]
просто "Возврата транзакции" переименовать
