### ISSUE TITLE
Баг при указании адреса кошелька в функции "Обмен" (Exchange)

### ISSUE THREAD

**Issue by Odny** [swaponline/swap.react#1297]
## What is working wrong?

Во вкладке Обмен при создании транзакции можно указать автоопределение кошелька с помощью маркера "Использовать swap online кошелек". Но если поменять валюты местами с помощью характерной кнопки (две стрелки: поменять местами), то автоопределение адреса слетает: при отключении функции автоопределения адреса кошелька, ссылка на кошелек остается, а при включении "Использовать swap online кошелек" - поле становится пустым.

## What should happen instead?

При включении "Использовать swap online кошелек" после перемены валют местами в блоке обмена должна автоматически генерироваться ссылка на кошелек. При выключении этой функции - поле должно обнуляться. Сейчас наоборот.

## Steps to reproduce

- Зайти во вкладку Обмен
- Вбить количество валюты для обмена
- Поставить использование кошелька
- Поменять валюты местами
- Снять маркер использования кошелька

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ..
![image](https://user-images.githubusercontent.com/46775958/51311628-64153100-1a5a-11e9-826e-3780b2916c63.png)
![image](https://user-images.githubusercontent.com/46775958/51311651-73947a00-1a5a-11e9-8a37-3d5cd6f2df37.png)

**Comment by noxonsu** [comment]
https://airdb.wpmix.net/chrome_2019-01-17_19-09-31caf56114-40d3-43e2-bc45-bd9d8b76f767.png

**Comment by Pasha8914** [comment]
![image](https://user-images.githubusercontent.com/43392281/51367939-ad3bb280-1b38-11e9-90db-50ef2dc09b04.png)
зачем генерировать выводить адресс кошелька?

**Comment by Odny** [comment]
Как я понял, при нажатии кнопки "использовать кошелек", поле автозаполняется адресом кошелька. 
Дальше, если поменять валюту местами, кнопка остается в положении "использовать кошелек", поле обнуляется, при снятии с кнопки "использовать кошелек" - автозаполняется тем же адресом, что в первом случае. 
По логике, должно быть так: после смены валюты снимается кнопка (использовать кошелек), поле пустое, при нажатии этой кнопки - появляется адрес

**Comment by Pasha8914** [comment]
как я делаю, ты заходишь на страницу- поле заполнено адресом по дефолту -бтс, когда ты меняешь валюту поле заполняется нужным адресом, если выключаешь то не заполняется
