### ISSUE TITLE
create order: Красные поля ввода при обмене валюты

### ISSUE THREAD

**Issue by Odny** [swaponline/swap.react#1302]
## What is working wrong?

при создании ордера, при вводе любого числа поля ввода становятся красными. Браузер Mozilla FireFox

## What should happen instead?

при вводе значений должно проверяться наличие валюты в кошельке без изменения цвета поля ввода/ Браузер Mozilla FireFox

## Steps to reproduce

- создать ордер
- ввести количество валюты
- (провести замену валют)

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...
![image](https://user-images.githubusercontent.com/46775958/51318121-772ffd00-1a6a-11e9-9794-83c41b0a6854.png)

**Comment by Pasha8914** [comment]
это мозила?

**Comment by noxonsu** [comment]
да

**Comment by Naggertooth** [comment]
Исправил #1319
