### ISSUE TITLE
exchange: не выскочило уведомление о начале обмена

### ISSUE THREAD

**Issue by Odny** [swaponline/swap.react#1304]
## What is working wrong?

При создании ордера в одном браузере и обмене через второй браузер нет всплывающего окна о начале свапа.

## What should happen instead?

Должно выпадать окно с предложением свапа

## Steps to reproduce

- Создать ордер в первом браузере
- Начать обмен во втором браузере

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...
https://i.imgur.com/4I9pvBt.png

**Comment by Odny** [comment]
После подтверждения обмена выпадает ошибка : 
https://i.imgur.com/5OtKfLy.png

**Comment by Odny** [comment]
Спустя 5 минут окно подтверждения появилось, дошло до 1 и зависло. консоль:
https://i.imgur.com/UteTWIX.png

**Comment by noxonsu** [comment]
невозможно повторить
