### ISSUE TITLE
иногда не приходит уведомление человеку который создал оредер

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#131]
1. я создал ордер 1 SWAP > 0.015 BTC
в консоли была ошибка алреди пайпед, но не факт что из за нее.
2. никита не сразу увидел мой ордер у себя, пришлось несколько раз перезагрузить его браузер
3. пришлось перезагрузить свой браузер чтоб увидеть что кто то хочет выполнить мой ордер
4. далее все прошло ок

**Comment by noxonsu** [comment]
я думаю нужно постаивть все таки dc messaging https://github.com/DaoCasino/dc-messaging

**Comment by nikdementev** [comment]
уведомление может не приходить если второй человек не подключен к ipfs

**Comment by nikdementev** [comment]
03ee10d0d889071641185b58da1c851fcc0dcb4a
