### ISSUE TITLE
Complex Manual Test 20.01.2019

### ISSUE THREAD

**Issue by Naggertooth** [swaponline/swap.react#1333]
**базовый тест (до 10 минут)**
- [x] 1. зашел на testnet.swap.online, создал ордер SELL BTC , BUY X (вместо X любой рандомный коин, например ETH)
- [x] 1.1 увидел сразу собственный ордер в спсике своих ордеров
- [x] 2.0. с другого браузера этот ордер увиедел перейдя по кнопке share
- [x] 2.1. напрвления "ю бай" и "ю селл" в обоих браузерах показываются нормально а не перепутано
- [x] 3. куллер не шумит
- [x] 4. еслли денег достаточно то доступен "плей"
- [x] 5. нажали "плей" (с браузера яндекс), пошел свап
- [x] 5.1. в течении нескольких секунд у маркетмейкера появилось уведомление, что кто то хочет начать свап
- [x] 6.1. нажали крестик "отменить свап" отмена сработала у обоих корректно
- [x] 6.2 кто то другой попробовал запустить этот свап и не сммог
- [x] 7. подождали сколько то секунд, начался свап корректно
- [x] 8. все шаги свапа выполнились

**тест с мобилой (до 10 минут)**
- [x] 9.1 в андроиде создается оредр на продажу 1 свап за 0.0015 btc
- [x] 9.2 в браузере на компе он виден сразу
- [x] 9.3 клиент  вбраузере нажимает плей
- [x] 9.4 сразу приходит уведолмнеие на андроид
- [x] 9.5 ждем пока свап закончится
- [ ] 9.6 свап закончисля
свап не закончился 
![image](https://user-images.githubusercontent.com/24671211/51439326-806ad500-1cc9-11e9-848f-24857c0001b0.png)
![image](https://user-images.githubusercontent.com/24671211/51439709-2bca5880-1ccf-11e9-916e-33db7b6663e2.png)
но это может быть оттого, что у меня старый, кастомно прошитый андроид, я даже на конфирм нажать не могу

А еще в шаблоне указано число 0.00015, но минимально возможное для создания ордера - 0.0015

**тест маркетмейкера (до 5ти минут)**
- [x] 10.1 в браузере создается ордер на продажу 1 свап за 0.00015 BTC
- [x] 10.2 в браузере создается ордер на покупку 1 свап за 0.0001 BTC (дешевле чем на продажу)
- [x] с browserstack заходит человек и выполняет оредр 10.1
- [x] одновременно из андроида пытаемся выполнить ордер 10.2
- [ ] маркетмейкер ничего не делает по идее должен выполнится ордер 10.1, а 10.2 отказатся

![image](https://user-images.githubusercontent.com/24671211/51439538-15230200-1ccd-11e9-8053-06cdca7cfdc7.png)

![image](https://user-images.githubusercontent.com/24671211/51439715-4e5c7180-1ccf-11e9-88e5-c8699f92c6d3.png)

вероятно стоит проводить тесты с телефоном не мне, ничего не конфирмит, да и после первой попытки телефон перестал видеть оферы, созданные и видимые на компе
и судя по всему меня кто-то автоматом выкупает без каких либо подтверждений

**прочие тесты (нужно расписать подробнее)**
- [x]  тест с альтернатив дестинейшин адрес
- [x]  тест с отсутсвием биткоина на счету -  не дает создавать ордера на продажу битка
- [x]  тест с нулевыми балансами - не дает создавать ордера вообще
- [x]  элемент "копировать адрес" работает
- [x]  элемент "обновить баланс" работает
- [ ]  если двое одновременно пытаются стартануть со мной свап, то один из них отменится?
- [x] Проверка кнопок социальных сетей
- [x] Проверка кнопки уведомлений - при нажатии убирает цветные края
- [x] Проверка суммы переводов в историях - отображает суммы после вычета комиссии за транзакцию
- [ ] Проверка возврата средств при истечении 180 минут при отмены подписания контракта
- [x] Проверка актуальности ссылок в подвале сайта
не уверен насчет работы Use swap.button -> https://wiki.swap.online/about-swap-online/#b2b
- [x] Проверка стандартной операции отправки валюты
- [ ]  я добавил 1 чекбокс к этому тесту, чтоб улучшить покрытие 
- [ ]  я добавил 3 чекбокса к этому тесту, чтоб улучшить покрытие

**Comment by noxonsu** [comment]
>вероятно стоит проводить тесты с телефоном не мне, ничего не конфирмит, да и после первой попытки телефон перестал видеть оферы, созданные и видимые на компе

да там можно один оредр только 1 раз запустить, это типа антиспам\
