### ISSUE TITLE
проверить английскую локализацию

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1335]
пройтись по английской локализации, порверить написи на кнопках, надписи возле чекбоксов, над инпутами, всплывающие подсказки и все остально, в футере провреить понятны ли пункты меню, возможно добавить подсказки к этим пунктам. Сделать надо самой и потом совместно с нативом. Но начать надо когда примут наконец функционал локализаций https://github.com/swaponline/swap.react/pull/941

**Comment by DariaPurtova** [comment]
![screen shot 2019-01-23 at 12 09 15 pm](https://user-images.githubusercontent.com/40612252/51595432-bf866980-1f07-11e9-87fb-ae3531419469.png)

**Comment by DariaPurtova** [comment]
![screen shot 2019-01-23 at 5 01 19 pm](https://user-images.githubusercontent.com/40612252/51611577-9cbc7b00-1f30-11e9-8821-04973c5ce3fd.png)
![screen shot 2019-01-23 at 5 01 23 pm](https://user-images.githubusercontent.com/40612252/51611580-9f1ed500-1f30-11e9-8fd8-b63d673a196a.png)
![screen shot 2019-01-23 at 5 01 26 pm](https://user-images.githubusercontent.com/40612252/51611582-a219c580-1f30-11e9-89a5-a83cc11dc044.png)
![screen shot 2019-01-23 at 5 01 28 pm](https://user-images.githubusercontent.com/40612252/51611589-a5ad4c80-1f30-11e9-906c-73f6e249f933.png)
![screen shot 2019-01-23 at 5 01 32 pm](https://user-images.githubusercontent.com/40612252/51611593-a9d96a00-1f30-11e9-93da-5c7bd1c353ac.png)
![screen shot 2019-01-23 at 5 01 40 pm](https://user-images.githubusercontent.com/40612252/51611609-afcf4b00-1f30-11e9-936c-ebedfaf4e724.png)

**Comment by DariaPurtova** [comment]
![screen shot 2019-01-23 at 5 18 36 pm](https://user-images.githubusercontent.com/40612252/51612714-0dfd2d80-1f33-11e9-8c30-b59bbf9aefdb.png)

**Comment by Naggertooth** [comment]
> https://github.com/swaponline/swap.react/issues/1335#issuecomment-456725517

https://github.com/swaponline/swap.react/pull/1366/commits/eb4d44bb1a01e31eeeaf00de8c507ebb54877bda

**Comment by noxonsu** [comment]
сктраница создания ордера 

Place an offer
Available amount for sale/или/available amount to sell
Enable partial fills

**Comment by noxonsu** [comment]
во все места в тег FormattedMessage вставь новый аттрибут qualityLevel = 1 (это значит, что текст проверен и поправлен)

**Comment by nthgness** [comment]
https://github.com/swaponline/swap.react/pull/1503

**Comment by noxonsu** [comment]
еще раз контрольный проверить все и закрыть
