### ISSUE TITLE
Страница создания виджета

### ISSUE THREAD

**Issue by 7flash** [swaponline/swap.react#1337]
1.  Job. What we need to do in order to implement this feature. Steps
Страница для генерации виджета с формой, которая отправляет запрос к сервису генерации виджета

2.  Purpose. What this feature is intended to resolve? 
a) Clients benefits
Владелец сайта может легко сгенерировать виджет для обмена своего токена
b) Our benefits
Больше пользователей смогут использовать виджет

3.  Where 
a) What part of our tech resources this feature intercourse  (Back, front etc.) 
widget backend service
b) Where’ll we implement this feature (project, space etc.) 
swaponline repository

4.  Estimate time of implementation this feature 
7h

5.  Evidences.

**Comment by noxonsu** [comment]
button.swap.online

**Comment by noxonsu** [comment]
@shendel закрываем?
