### ISSUE TITLE
Add DIadem Coin

### ISSUE THREAD

**Issue by 7flash** [swaponline/swap.react#1339]
Address: 0x0e9030636b73858ad93fcbd5e1e783d5c4de1a5c
Name: Diadem
Symbol: DDM
Decimals: 18
Etherscan: https://etherscan.io/address/0x0e9030636b73858ad93fcbd5e1e783d5c4de1a5c

**Comment by Pasha8914** [comment]
почему не на амо
?

**Comment by 7flash** [comment]
@Pasha8914 Не повезло

**Comment by noxonsu** [comment]
нет доступа у Игоря туда
