### ISSUE TITLE
рефанд не работает (ждал 3 часа)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#135]
https://youtu.be/M6pO5HD0OFw

**Comment by noxonsu** [comment]
получилось отправить hex (кстати переименуй ее в Raw hex transaction - добавить слово raw). http://joxi.ru/YmE9w0DF0DL8Dm
при  этом транза прошла еще минимум только через час когда таймлок прошел.

**Comment by nikdementev** [comment]
Как только не пробовал, должен пройти час после генерации транзакции иначе он не проходит

**Comment by nikdementev** [comment]
#192
