### ISSUE TITLE
отправка эфира с кучей знаков после запятой

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1354]
![image](https://user-images.githubusercontent.com/2914674/51545995-41c54e00-1e74-11e9-92c2-b7bb85da31b4.png)
я нажал на MAX

**Comment by Naggertooth** [comment]
https://github.com/swaponline/swap.react/pull/1366/commits/64cb86ce8294052198df4c3ff18503b3e6cebbf2
