### ISSUE TITLE
убрать анимацию логотипа на файрфоксе

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1370]
на файрфоксе (а может и еще где) анимация прелоадера корявая (дергается левый треугольник)

**Comment by caffeinum** [comment]
походу это происходит только на реактовском прелоадере, потоум что первый раз все ок

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/51772091-2c625500-20fc-11e9-855b-5777b88c3fa5.png)
в хроме тоже бывает тупит сильно
