### ISSUE TITLE
qr код в пополнении битком не работает

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1371]
![image](https://user-images.githubusercontent.com/2914674/51683005-e58c3680-1ff9-11e9-898a-7d888c869c4b.png)
 
а так же в deposit напротив биткоина.

как проверить
1. скачать кошелек биткоина на мобилу, например electrum
2. внутри него нажать send > scan qr и отсканировать наш QR 
3. должно отработать нрмально (адрес вытащится и сумма, если есть)

сейчас пишет erroк broken qr

**Comment by caffeinum** [comment]
на айфоне можно использовать просто приложение Камера

**Comment by caffeinum** [comment]
Лēшå Быхун, [24.01.19 17:35]
[ Photo ]

QR Code Bot, [24.01.19 17:35]
Got The Image ! Processing...

QR Code Bot, [24.01.19 17:35]
[In reply to Лēшå Быхун]
bitcoin:2NCHR4wFLWuYw63GV8RBomDRKnDfb7F7ra3?amount=0.003289

**Comment by noxonsu** [comment]
все ок
