### ISSUE TITLE
exchange.swap.online пруфрид

### ISSUE THREAD

**Issue by DariaPurtova** [swaponline/swap.react#1383]
https://exchange.swap.online/ru/

**Comment by Naggertooth** [comment]
> залить сюда exchange.swap.online

https://exchange.swap.online/ - залито
Нужен перевод:

![image](https://user-images.githubusercontent.com/24671211/51938498-4e224b80-241e-11e9-9e55-374fedf35457.png)
"Мы получаем определение атомарного свопа как серии операций над двумя блокчейнами, которые либо ведут к успешному обмену криптовалютами, либо они откатываются назад, и обмен не происходит. Ситуация, когда одна сторона получила криптовалюту, а другая нет, невозможна."

**Comment by noxonsu** [comment]
Atomic swap is a smart contract technology that enables exchange of one cryptocurrency for another without using centralized intermediaries, such as exchanges.
