### ISSUE TITLE
exchange: добавить прямые ссылки на обмен /exchange/btc-to-swap

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#1388]
# Problem

Если переходить на SHOW ORDERBOOK /eth-btc  и обратно, то валюты сбрасываются

# Task

Сделать ссылки `/exchange/eth-to-btc`

# Estimate time of implementation

2 часа

# Additional data

![image](https://user-images.githubusercontent.com/1909384/51774310-e361cf00-2102-11e9-9fb5-1a280373d3ca.png)

Плюс, так будет удобнее добавлять в закладки

**Comment by noxonsu** [comment]
дубль https://github.com/swaponline/swap.react/issues/1384

**Comment by noxonsu** [comment]
не не дубль
