### ISSUE TITLE
exchange: продать все доступные биткоины: показывать какой у тебя баланс, или кнопку MAX

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#1390]
# Problem

Непонятно, сколько я могу потратить:

![image](https://user-images.githubusercontent.com/1909384/51775974-82d59080-2108-11e9-99ad-6de2973b28b7.png)

Я хочу купить столько своп-токенов, сколько мне позволит мой кошелек

# Task

- кнопка MAX, как в Withdraw
- либо просто выводить где-то рядом твой баланс в этой валюте

# Estimate time of implementation

2 часа

**Comment by noxonsu** [comment]
не показывать баланс и кнопку макс если на балансе 0 (для виджета)
