### ISSUE TITLE
swap: SWAP2BTC, не хватало эфира, пополнил, пошло дальше, но ошибка не исчезла

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#1393]
## What is working wrong?

Вылезла ошибка:

Пополнил, появилась транзакция, но ошибка не пропала?

![image](https://user-images.githubusercontent.com/1909384/51786708-34aca580-2179-11e9-8e86-0d450764e12e.png)

## What should happen instead?

Пускай ошибка скрывается

## Does this affect atomic swap flow?

- [x] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by caffeinum** [comment]
Ошибка пропадает только на следующем шаге, а должна сразу, когда чувак уже пополнил

**Comment by sdwas** [comment]
> Ошибка пропадает только на следующем шаге, а должна сразу, когда чувак уже пополнил

В btc2eth ошибка вовсе не пропадает, даже когда пополнил:

![screenshot_20190126_225251](https://user-images.githubusercontent.com/43396375/51787412-50399f80-21bd-11e9-85c4-36fe1d8e5e30.png)


 В коре всё норм: флаг сразу же меняется.

![screenshot_20190126_224730](https://user-images.githubusercontent.com/43396375/51787354-7d398280-21bc-11e9-8e03-b04b3342e3fe.png)

**Comment by shendel** [comment]
Проблема в рендере...
