### ISSUE TITLE
Возможность указать адрес назначения при полном выкупе через ордербук

### ISSUE THREAD

**Issue by shendel** [swaponline/swap.react#1394]
1. При полном выкупе токенов через ордербук (не partial), у пользователя исчезла возможность указать адрес для токенов
2. При полном выкупе через ордербук Btc2Eth, Eth2Btc, Btc2Token - у пользователя нет возможности указать адрес для эфира/биткоина

**Comment by noxonsu** [comment]
согласен, альтернатив дестинейшин нужен для виджета в основном, для осноного не надо, меньше мороки будет с оформлением свапа

**Comment by caffeinum** [comment]
в коре эта фича все равно осталась, и если будет спрос, добавим в реакте
