### ISSUE TITLE
swap: Не могу совершить транзакцию (sign)

### ISSUE THREAD

**Issue by Naggertooth** [swaponline/swap.react#1409]
## What is working wrong?

Не нажимается кнопка SIGN, транзакция не совершается на ветке develop

## What should happen instead?

Транзакция должна совершаться после 5 секундного ожидания

## Steps to reproduce

- Создать ордер_1 в 1 браузере
- Зайти на /exchange и совершить транзакцию на ордер_1 в другом браузере
- Ждать или попробовать нажать на SIGN

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [x] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...
https://vimeo.com/313868596

**Comment by noxonsu** [comment]
на видео мотаем на 1:36

**Comment by noxonsu** [comment]
уже все ок
