### ISSUE TITLE
Поставить лимит для создания ордеров по максимальной сумме баланса

### ISSUE THREAD

**Issue by apelsin555** [swaponline/swap.react#141]
Поставить лимит, чтобы нельзя было создавать ордер на сумму, большую чем на балансе. (ещё вариант: с учётом % комиссии). Сейчас можно создавать ордера с любыми суммами. Обмен конечно не пройдёт, т.к. на втором шаге обмена заблокируется, но всё же создавать ордер можно и даже начать обмен.

**Comment by nikdementev** [comment]
У нас можно продолжить свап пополнив баланс
