### ISSUE TITLE
неправильная страница /NotFound

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#1425]
## What is working wrong?

Вместо настоящей 404 показывает все так, будто бы NotFound это валюта

https://testnet.swap.online/xxx

Тут вовсе не работает

https://testnet.swap.online/xxx-wallet

## What should happen instead?

Пускай просто надпись NotFound

## Steps to reproduce

https://testnet.swap.online/xxx
https://testnet.swap.online/xxx-wallet

**Comment by caffeinum** [comment]
https://testnet.swap.online/NotFound

![image](https://user-images.githubusercontent.com/1909384/52138509-684a6c80-265e-11e9-892c-701f9b58a9a5.png)

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/52138532-7a2c0f80-265e-11e9-8e69-9def2fd1bd9e.png)

**Comment by caffeinum** [comment]
хм...

**Comment by caffeinum** [comment]
может билд недособрался?

**Comment by Pasha8914** [comment]
![image](https://user-images.githubusercontent.com/43392281/52163260-5da9d900-272b-11e9-8cdc-b10e63590175.png)
в девелопе
 работает

**Comment by caffeinum** [comment]
https://testnet.swap.online/xxx
https://testnet.swap.online/xxx-wallet
https://testnet.swap.online/NotFound
https://testnet.swap.online/fff-wallet/ddd
https://testnet.swap.online/404

Сейчас работает, закрываю
