### ISSUE TITLE
exchange: Вместо ETH-BTC можно выбрать BTC-BTC, но он превращается в EOS-BTC

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#1426]
## What is working wrong?
Переключается в неправильном порядке

![image](https://user-images.githubusercontent.com/1909384/51975471-59fc2500-2493-11e9-8f03-e556cc60f4d1.png)

![image](https://user-images.githubusercontent.com/1909384/51975473-5ec0d900-2493-11e9-9da0-28d7869dd0a2.png)
![image](https://user-images.githubusercontent.com/1909384/51975480-61bbc980-2493-11e9-932d-483982dec77b.png)

## What should happen instead?

BTC вообще не должно быть в верхнем списке, если он выбран внизу

Или если он там есть, то внизу должно переключаться на ETH, который был выбран в верхнем, либо всегда на SWAP токен

## Steps to reproduce

 - https://testnet.swap.online/exchange/eth-to-btc
 - https://testnet.swap.online/exchange/btc-to-btc

**Comment by caffeinum** [comment]
А если напрямую открыть, то будет так (логично)

![image](https://user-images.githubusercontent.com/1909384/51980326-c598bf00-24a0-11e9-9fe2-86fee6963d76.png)

**Comment by Pasha8914** [comment]
это сделано специально(что в верхнем списке все валюты, даже та, которая выбрана в нижнем, выбрав ее ты просто подгрузишь список валют на которые ты сможешь ее поменять

**Comment by Pasha8914** [comment]
а переключает на еос, потому что он просто первый по порядку, можно заменить порядок в редусере и поставить что угодно

**Comment by caffeinum** [comment]
### https://testnet.swap.online/exchange/btc-to-eth

редирект на eth-to-btc

https://pr1443.swaponline.site/exchange/btc-to-eth

норма работает

**Comment by caffeinum** [comment]
https://testnet.swap.online/exchange/btc-to-eth
https://testnet.swap.online/exchange/swap-to-btc

не работает! в пулле работало

**Comment by caffeinum** [comment]
https://testnet.swap.online/exchange/btc-to-btc

)) BTC-BTC

**Comment by caffeinum** [comment]
сюда можно попасть только по прямой ссылке, а если уж такую ссылку ввел, так сам виноват
