### ISSUE TITLE
Генерация секрета

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#147]
Генерировать секрет при создании свопа. 

Для референса, как я это делаю в NodeJS

```javascript
const crypto = require('crypto')
const genSecret = () => crypto.randomBytes(32).toString('hex')
```

https://github.com/swaponline/swap.react/blob/master/shared/pages/Swap/BtcToEth.js#L20

**Comment by nikdementev** [comment]
4ee2608032312c5d5d25722d8899bc5eb960b7a2
