### ISSUE TITLE
Не отображается история транзакций SWAP токена

### ISSUE THREAD

**Issue by VladislavSopov** [swaponline/swap.react#1482]
Коллеги, в кошельке не видна история транзакций (в частности, по токенам SWAP) с 01.12.2018 по настоящее время. История свопов видна.

**Comment by Pasha8914** [comment]
![image](https://user-images.githubusercontent.com/43392281/52495276-e3da8980-2c1b-11e9-8618-3c740555d5db.png)
в списке первые 2 это свап BTC-SWAP
вторые 2 просто транзакция
@VladislavSopov 
Если я не понял, отпиши пж в телегу @uhaubuhau894

**Comment by Pasha8914** [comment]
![image](https://user-images.githubusercontent.com/43392281/52495397-4764b700-2c1c-11e9-80e9-9dcf1668ad32.png)
c мозилы
