### ISSUE TITLE
Повышить Usability 

### ISSUE THREAD

**Issue by SabirICOadmin** [swaponline/swap.react#149]
1.	Job. Повышить юзабилити для пользователей:
1.1. Offer - Поставить над полем Available amount 
1.2.  На стартовой странице слева поставить Create Offer 
1.3. Где поле Exchange rate в углу слева поставить иконнки валют, для наглядности 
1.4. Внизу, где иконки с изображениями, кто это, что это для кого это? Написать:
Who can participate in our airdrop:
2.	Purpose. 
a) Первые шаги к повышению юзабилити
3.	Where 
a) Стартовая страница
Переход по offer

4.	Проставить эстимейты
5.	Evidences. См. ниже

1.1 
![image](https://user-images.githubusercontent.com/41383491/42946434-8999cbaa-8b73-11e8-8cd5-0366c87b1797.png)
1.2.
![image](https://user-images.githubusercontent.com/41383491/42946495-af171928-8b73-11e8-9e83-e64ff8871584.png)
1.3.
![image](https://user-images.githubusercontent.com/41383491/42948381-06c2fdc8-8b78-11e8-8483-46de945f96ec.png)
1.4
![image](https://user-images.githubusercontent.com/41383491/42948748-da393744-8b78-11e8-94e3-5195f32ceda9.png)

**Comment by noxonsu** [comment]
1.4 не делать
