### ISSUE TITLE
при отправке трнзакций выводить txid ссылку на езерскан

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#153]
http://joxi.ru/KAxb179CM8Gv6m

**Comment by nikdementev** [comment]
<img width="958" alt="2018-07-24 12 50 20" src="https://user-images.githubusercontent.com/17093843/43130804-2c52c782-8f40-11e8-9d55-92a718c332b7.png">

**Comment by nikdementev** [comment]
148fc8bcb3880f3d169b5188ce49fa344b2e40bf
