### ISSUE TITLE
orderbook: btc-swap должен переводить на swap-btc

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#1540]
## What is working wrong?

https://testnet.swap.online/btc-swap

![image](https://user-images.githubusercontent.com/1909384/52564717-e7d1fb80-2e15-11e9-8e53-f77631fb201b.png)

## What should happen instead?
Должно переходить на swap-btc в правильном порядке

В TRADE_TICKERS есть все валютные пары, везде либо -BTC основная, либо USDT. Нужно, чтоб ордербуки были в правильном порядке.

## Does this affect atomic swap flow?

- [x] no

## Are real funds at risk?

- [x] no

**Comment by noxonsu** [comment]
как ты сюда попал?

**Comment by caffeinum** [comment]
https://testnet.swap.online/btc-swap

че-то не работает

**Comment by caffeinum** [comment]
откроем заново если какой-то умник кроме меня сможет туда попасть через интерфейс
