### ISSUE TITLE
НЕ РАБОТАЕТ СВАП 2 SWAP -> 0.00001 BTC 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1541]
1. Создать ордер, что покупаю 2000 SWAP за 0.01
2. Попытатся в другом бразуере чрез /exchange продать 2 свапа
3. Свап доходит до  "SWAP зачисление", но при этом битки не заморозились

в шаге заморозки битков битпей отклонил транзакцию, видимо из за того что слишком маленькая она, но все равно почемуто свап продолжился

**Comment by noxonsu** [comment]
тупо не давать стартовать свап меньше чем на 0.0001 BTC

**Comment by caffeinum** [comment]
> 0.0001 BTC

Это 10000 сатоши, а это типичная комиссия. Может, лучше даже 0.0005 BTC сделать. Хотя это 2$, а это немало

**Comment by noxonsu** [comment]
пока что сделать ограничение на 0.0001 BTC потом посмотрим
