### ISSUE TITLE
11.02 тест свапа mainnet 

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1551]
1. Пользователь не имеет никаких средств на балансе кошелька
2. Пользователь находит обмен, который его интересует (при тесте был 
btc-eth)
3. Начинается обмен, поскольку у пользователя нет средств , появляется окно для пополнения баланса скрипта
4.После пополнения баланса - окно не пропадает, информация в окне не обновляется !!!
такой проблемы нет в тестнете.
5. Поскольку, нет эфира на оплату фу, появляется окно для пополнения баланса Эфира, на этом этапе существует та же проблема, что и на предыдущем этапе, требуется перезагрузка на каждом этапе, где появляются формы
6. Бот оканчивает свап раньше, чем пользователь, после окончания свапа бот отключается. Из за этого процесс свапа у юзера прекращается. Свап останавливается и если пользователь не перейдет на вэллет, он никогда не узнает, что свап завершен.
7. После перехода на вэллет, появляется просьба  ввести ключи.
8. В шапке вэллет, появляется предложение на прохождение опроса.

Задачи:
1. Разобраться, почему не происходит перерендаринг, при появлении окон именно в mainnet
2. Не отключать бота, пока свап не закончится у обоих сторон. Или же в состоянии офлайн второй стороны свапа не морозить процессы у первой

Что радует
1. После пополнения на точную сумму указанную в окнах, не возникает никаких ошибок
2. Ux выглядит понятно и приятно
3. Если бы окна обновлялись и происходил перерендаринг, свап проходит относительно быстро, несмотря на все пополнения

**Comment by Pasha8914** [comment]
15.02 Провел 3 Свапа, токены - btc 
В первом случае хватало и на свап и на фи - свап прошел удачно, без нареканий
В 2ух остальных случаях были повторены условия указанные в прошлый раз.
Что изменилось - 
  Deposit Window пропало после пополнения баланса
  FeeControler ситуация другая, данная форма не обновилась
После перезагрузски свап окончился без нареканий
Свап производился из 2ух браузеров мозила - хром

**Comment by noxonsu** [comment]
уточни все ли ок тут? надо закрыть наверно
