### ISSUE TITLE
Exchange: Вместо пар подбираются конкретные значения

### ISSUE THREAD

**Issue by Naggertooth** [swaponline/swap.react#1555]
## What is working wrong?

Когда выбираешь токен в обменнике - выбрать любой токен можно только в верхнем дропдауне, нижний подбирается, вероятно, захардкожено

## What should happen instead?

Было бы хорошо выбирать среди пар к другому токену

## Steps to reproduce

- Зайти на exchange
- Выбрать на продаже биткоин
- Не найти в покупаемых токенах EOS или SWAP, которые по идее там должны быть

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

## Screenshots

![exchange](https://user-images.githubusercontent.com/24671211/52629278-68523400-2eca-11e9-9f58-be5df9f3cadf.gif)
https://vimeo.com/316376174

**Comment by Pasha8914** [comment]
а токены между собой можно обменивать?

**Comment by Pasha8914** [comment]
я вижу 1 баг, что если поменять местами дроп список не меняется

**Comment by noxonsu** [comment]
на гифке видно что вверху выбран бтс, а внизу нет SWAP

**Comment by Pasha8914** [comment]
потому что стейт не обновился, а встал в очередь и список для эфира

**Comment by Pasha8914** [comment]
https://github.com/swaponline/swap.react/pull/1560
