### ISSUE TITLE
exchange: продать "ВСЕ" биткоины не учитывает комиссию 

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#1568]
![image](https://user-images.githubusercontent.com/1909384/52710409-4925d600-2fa0-11e9-9e67-fca860cf69f1.png)
<hr>

![image](https://user-images.githubusercontent.com/1909384/52710403-46c37c00-2fa0-11e9-9ed1-20842f1095cb.png)

**Comment by noxonsu** [comment]
комиссия может еще изменится в процессе, короче надо убрать кнпоку "все" либо отнимать от битка копейки какието

**Comment by caffeinum** [comment]
> комиссия может еще изменится в процессе

Вообще, тогда получается нужно ее оценивать перед началом свопа, чтоб выставить правильный курс обмена, а потом замораживать и пробрасывать в параметры свопа.

В целом, согласен, отнимаем константу и все
