### ISSUE TITLE
13.02.2019 Юзер-тестирование айфон 

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#1569]
# Продать свопы

Тут все хорошо,

зашел на балансы, нажал напротив SWAP кнопку exchange, случайно попал в Withdraw и поле для ввода сбило зум браузера 

Попал на /exchange, стал продавть свопы

# Ордер

Первый раз на ордер бот не ответил, долго висело и долго Тимур ждал (ждать нет смысла обычно)

Второй раз ответил "Отказ"

Я подсказал продать 1 своп, а не 50

Тогда сработало

# Вернуться к свопу

он нажал сначала на всю строку, потом подождал, пролистнул вправо, но недолистал до Link to the swap,

потом решил заново меняться, и пошел на /exchange

я подсказал, что в истории была кнопка в самом конце

 он долистал до конца и все равно не понял, что значит Link to the swap, но нажал

# Ошибка ордера?

https://etherscan.io/tx/0x3186e13ecfcd43c6d33fca840a56e8c88c17d19b8254568010deb03a67160df5

![image](https://user-images.githubusercontent.com/1909384/52714660-83e13b80-2fab-11e9-8a9e-c9528a4faad7.png)

![image](https://user-images.githubusercontent.com/1909384/52714667-89d71c80-2fab-11e9-8ade-d2dbca7f88c6.png)

# Своп

Зависло на том, что не хватает эфира на комиссию – два раза пополняли, и все равно висит эта ошибка.

Своп создался.

**Comment by caffeinum** [comment]
# Создание контракта

Намертво зависло на шаге создания контракта: видимо, он обновил страницу в момент, когда транза уже отправилась, но еще не замайнилась, и своп не сохранил этого. В следующий раз он попробовал создать своп опять, но второй раз это невозможно, или ему не хватило комиссии, хз, в общем, токены отправились, а своп дальше не пошел

**Comment by noxonsu** [comment]
>обновил страницу в момент, когда транза уже отправилась, но еще не замайнилась

нужно просить, чтоб не обновляли страницу

**Comment by noxonsu** [comment]
еще вспомнил, при первом показе всех балансов он посмотрел на первый экран и покрутил в низ, понял что их очень много, но не встмаривался, по этому надо всю кучу скрыть, оставить те кто есть с иконками красивые
