### ISSUE TITLE
Предложение не помещается в кнопку, нет "обратной связи"

### ISSUE THREAD

**Issue by shendel** [swaponline/swap.react#1586]
## What is working wrong?
Кнопки "Выкупа предложения" не "резиновые"
![image](https://user-images.githubusercontent.com/1880211/52814546-7c09c000-30ad-11e9-8036-6d44219cbd0b.png)
Плохо читается тест

Нет "обратной связи"
Я хочу продать токены, (возможно боту), продавец сделал отказ - но я не вижу никакой информации об этом и продолжаю нажимать дальше, думая, что "тормозит интернет" или еще что...
![image](https://user-images.githubusercontent.com/1880211/52814751-f2a6bd80-30ad-11e9-8ac4-dab0c67bd03b.png)

**Comment by noxonsu** [comment]
ожидаем пока реальный пользователь на это пожалуется, пока холд
