### ISSUE TITLE
Swap: use created swap, if it is not finished

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.react#1609]
Необходимо реализовать систему контроля текущего swap.

### Задача 1 (Сохранить ссылку на текущий swap):
- [x] Создать action для добавления ссылки текущего swap в redux store
- [x] Создать action для получения ссылки текущего swap в redux store
- [x] Создать action для удаления ссылки текущего swap в redux store
- [ ] Создать swapSaver для middleware redux store, чтобы сохранять текущий своп в localStore по кажому вызову action.
### Задача 2 (Использовать ссылку текущего swap, если он уже есть):
(базовый пример здесь: https://github.com/swaponline/swap.react/pull/1607)
- [x] Использовать текущий своп в `shared/pages/Swap/Swap.js` 
- [x] Удалить текущий своп по его завершению в `shared/pages/Swap/DeleteSwapAfterEnd.js`
### Задача 3 (Управление swap на его странице):
- [x] Добавить кнопку для отмены swap так, чтобы:
 - если swap не на 2м шаге, то просто удалить и вернуться в колешек.
 - если swap на шаге 2, но не 3 и 4, то удалить своп и сделать refund.
 - если swap на шаге 3 и 4, скрыть кнопку и не обрабатывать ее вызов.
 - все события по завершению swap синхронизировать со вторй стороной через ipfs.
 - по завершению времени ожидания для проведения swap делать автоматический refund и удаление swap.
### Задача 4 (Не дать начать новый swap, если текущий не завершен/удален):
- [x] Создать modal для уведомления о наличии незавершенного текущего свопа:
Составить текст о том, что есть незавершенный swap и что его нужно лио завершить, либо отменить для продолжения текущего действия. Ниже кнопка с ссылкой на него.
 - показать при посещении каждой страницы приложения
 - показать при открытии приложения
 - показать при попытке начать новый swap (не пропускать дальше)
 - показать при получении запроса на новый swap (не пропускать дальше)
 - при по пытке перейти через url в какой-либо swap, кроме текущего, перенаправлять на кошелек и показать эту modal.

**Comment by noxonsu** [comment]
Noxon, [16.02.19 20:18]
итак как я это вижу. при заходе в свап проверять, что нет текущего свапа. если есть писать типа отмените предыдущий свап и ссылка на историю (паша уже делал это). Если он заходит в тот свап который собсно текущий то есть кнопка "отменить свап" (красная ссылка возле инфы для девелоперов) он ее нажимает, стор очищается, второй стороне отправляется просто сообщение "свап отменен", но пока никак не обрабатывается.

Noxon, [16.02.19 20:19]
ну и собсно висит на треть экрана баннер на всех страницах, у вас есть незавершенный свап! перейдите продолжите или отмените его

Noxon, [16.02.19 20:19]
вот такую схему сделать вроде не сложно
