### ISSUE TITLE
Не отправляет запрос на завершение свапа второй стороной

### ISSUE THREAD

**Issue by shendel** [swaponline/swap.react#1613]
Сломалось завершение свапа продавцом (когда у покупателя нет на фии)
У покупателя в flow.state показывает, что нужно фи на снятие токенов
Но запрос не отправляет, даже если очень долго ждать
Если отправить его вручную через консоль - у продавца в state все проставляет верно
У покупателя ошибка, то-есть продавец увидел запрос, но не свог на него ответить
![image](https://user-images.githubusercontent.com/1880211/52906226-6258ac00-3258-11e9-83f6-1f1841574735.png)
![image](https://user-images.githubusercontent.com/1880211/52906228-6d134100-3258-11e9-8c6f-4fbea530ff14.png)

**Comment by sdwas** [comment]
Подтверждаю
![screenshot_20190217_195756](https://user-images.githubusercontent.com/43396375/52911356-7cdd6480-32ee-11e9-83f5-0b8cea17ff17.png)
