### ISSUE TITLE
partial: requet rejected 

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1614]
## first bag
Существуют ордера на 2 и на 1 свап токен
Аккаунт второго браузера пополнен на 2 свап токена (впервые)
При начале поиска ордер находится, при нажатии на свап, происходит загрузка на этом процесс замер
https://www.useloom.com/share/bbcdd30b30fb47d88cba1c0e0b52eb6e
При перезагрузке страницы и смене суммы, появляется надпись свидетельствующая, о том что свап уже существует.
![image](https://user-images.githubusercontent.com/43392281/52907907-cc07a300-32b6-11e9-8333-501eafdc2ecf.png)

 Нa свап history пустo
![image](https://user-images.githubusercontent.com/43392281/52907884-76cb9180-32b6-11e9-9ab8-d5cdc98c7c68.png)

https://www.useloom.com/share/312bb53928d04a62b1fd9795c7c4ea25

**Comment by noxonsu** [comment]
мои наблюдения: 
возможно отправляется другому юзеру, смотри что в ордербуке, там бывают появляются призрачные ордера. т.е. если оба окна перезагрузить то пока эти призраки не набежали, то работает

**Comment by noxonsu** [comment]
@Pasha8914 почини второе и третие пож. , первое потом дебажить будем

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/chrome_2019-02-17_19-24-46ee3560b8-fb56-4a6d-9891-039678d4068c.png) возможно это встречный ордер корявый

**Comment by noxonsu** [comment]
возможно сюда же 

Noxon, [18.02.19 19:30]
на тестнете пытаюсь продать свап токен, после ввода не /exchange и нажатии на розовую - появился белый экран  и https://screenshots.wpmix.net/chrome_2019-02-18_19-29-345d7d1c3f-f1fe-4f6e-a4dc-aaed293ba6a9.png

Noxon, [18.02.19 19:31]
если удалить оредр к которому обращались и снова добавить то сработало. эх
