### ISSUE TITLE
виджет в сафари не работает

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1619]
см https://github.com/swaponline/swap.react/issues/1571 в сафари не работает виджет, надо показать сообщение типа "к сожалению виджет коорый загружен с seven.swap.online не работает в сафари, попросите администратора перенести код на свой домен"

**Comment by noxonsu** [comment]
https://github.com/cyrilletuzi/angular-async-local-storage/issues/42

**Comment by noxonsu** [comment]
смотрит @Spa1der

**Comment by shendel** [comment]
https://www.npmjs.com/package/@ngx-pwa/local-storage
