### ISSUE TITLE
клиент где то скачал русский вайтпепер

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1620]
клиент из канады гдето скачал русский вайтпепер, пройтись по сайту и указать везде ссылку https://docs.google.com/document/d/1MWrDR5pc3FB7AiWBO0GyBWBSci3VuDKNvknkPHtTzl8/edit?usp=sharing

**Comment by noxonsu** [comment]
возможно на listing.swap.online ?

**Comment by Naggertooth** [comment]
Вроде все протыкал и просмотрел и на сайте, и на листинге, и на вики
Так же попробовал поиск по ссылке
Пока нет ни одного попадания на русский вайтпейпер
Есть предположение что в гугле можно зайти в папку с этим файлом, если он доступен по ссылке, и увидеть все доступные по ссылке файлы
