### ISSUE TITLE
Поменять сео и текста https://swap.online/dai

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1626]
1. title: 
  Swap.Online - Maker DAI Web Wallet with Atomic Swap.

2. description:  Atomic Swap Wallet allows you to manage and securely exchange DAI with 0% fees. Based on Multi-Sig and Atomic Swap technologies.

3. h1:  Your online DAI wallet with Atomic Swap.

**Comment by noxonsu** [comment]
пока на холд, думаем как лучше

**Comment by noxonsu** [comment]
поменять нужно только на этой странице, на остальных оставить как есть

**Comment by Naggertooth** [comment]
title  
{full name} ({ticker name}) Price, Description & Exchange Rates. Store & Exchange {full name} ({ticker name}) Anonymously on Swap.Online.

description  
Find out actual price of {full name}, its ticker name is ({ticker name}). Swap.Online is the best way to safely store your cryptocurrecy.

h1  
{full name} ({ticker name}) Price & Exchange Rates.

еще русский
