### ISSUE TITLE
Мультияз: Не могу вернуться на EN

### ISSUE THREAD

**Issue by 1maxim** [swaponline/swap.react#1628]
http://prntscr.com/mmrvsr Переключился на RU язык, браузер chrome, теперь не могу вернуться обратно на EN. 
При нажатии на EN страница перезагружается, но автоматом приставляет /ru в ссылку

**Comment by Naggertooth** [comment]
У нас вроде на сервере стоит редирект на ру автоматом

**Comment by Naggertooth** [comment]
Сделать куку mylang
