### ISSUE TITLE
withdrawOther вызвлася с минимальной комиссией в 1 gwei

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1658]
![](https://screenshots.wpmix.net/chrome_2019-02-23_01-14-420e432ae0-2514-42b8-82c8-973e74985455.png)

транза будет майнится 8ч. нужно установить комссиию согласно сети

**Comment by noxonsu** [comment]
в другой раз вызвал с 5 gwei короче он берет нормалную. лучше сделать нормальную +1 gwei (6 в нашем случае)

**Comment by noxonsu** [comment]
GAS PRICE 5 gwei
EST DURATION 92 secs
---
GAS PRICE 6 gwei
EST DURATION 21 secs

**Comment by noxonsu** [comment]
нужно увеличить во всех транзах газпрайс на 2 gwei

**Comment by sdwas** [comment]
Перенесено в кор:

https://github.com/swaponline/swap.core/issues/326
