### ISSUE TITLE
swap btc to eth не показал галку саксеса

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1660]
![](https://screenshots.wpmix.net/browser_2019-02-23_03-05-427901de4c-686b-46b6-b18b-830dc932f9f9.png)

**Comment by Pasha8914** [comment]
![image](https://user-images.githubusercontent.com/43392281/53313519-698d5300-3905-11e9-9f9c-ebba00ecfe04.png)
можно дополнительные условия пожалуйста
