### ISSUE TITLE
SIP1 - мастрекей на 12 слов для каждого блокчейна

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1664]
1. сделать возможность записать 12 слов (в caution этот вариант должен идти приоритетнее скачки файла инструкции)
2. в импорте ключей должна быть возможность вветси 12 слов из которых генерятся приватники и заполняются в нужные поля. при этом оставить возможность заполнить другими приватниками

**Comment by noxonsu** [comment]
давайте пока обсудим. итак вопрос

1. что будет если сид сохранен и добавляется новый блокчейн, как генерить ему приватник

**Comment by caffeinum** [comment]
Для этого есть спецификация, https://github.com/ethereum/EIPs/issues/84, https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki.

Если вкратце, из мастер-ключа генерируется приватник для нового блокчейна

`m / 44' / 0' / 0' / 0 / 0` - например, один из адресов биткоина
`m / 44' / 60' /0' / 0 / 0` - эфира

**Comment by noxonsu** [comment]
ну получается человеку надо будет ввести свои слова каждый раз когда мы новый бч добавим?

**Comment by caffeinum** [comment]
> ну получается человеку надо будет ввести свои слова каждый раз когда мы новый бч добавим?

я думал мы храним мастер-ключ, то есть автоматически генерироваться будут ключи под каждый бч

**Comment by noxonsu** [comment]
ну мы же не будем мастер ключ хранить в локалсторадже? или будем

**Comment by caffeinum** [comment]
Если его не хранить, тогда новые блокчейны нельзя будет подключать к нему, а значит от него смысла мало.

Вообще, обычно делается так, что хранится один только мастер ключ, а для всех операций выбирается конкретный ключ по определенному алгоритму, то есть, он как бы генерируется перед использованием.

**Comment by noxonsu** [comment]
Хорошо, давайте харнить, и делаем 12 слов. Еще клиенты жалуются, что не хотят скачивать ключи, хотят их записать. https://github.com/swaponline/swap.react/issues/1710

**Comment by noxonsu** [comment]
сделаем в другой раз
