### ISSUE TITLE
писать количество конфирмейшинов в истории

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#169]
http://joxi.ru/12MZwNjHM10YqA

тут пишем например "4 confirmation(s)"

**Comment by nikdementev** [comment]
b7372a58c679aff9042fff4215230d7d33cd7ca1
<img width="1174" alt="2018-07-26 9 20 52" src="https://user-images.githubusercontent.com/17093843/43244952-3ab9992e-90b5-11e8-84ec-99c4833df9a9.png">
