### ISSUE TITLE
Проверять работу API перед свапом

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#170]
Перед началом свопа проверять, что все api хорошо работают (bitpay, rinkeby.etherscan)

**Comment by caffeinum** [comment]
http://mainnet.y000r.world/insight-api/addr/1JoiKZz2QRd47ARtcYgvgxC9jhnre9aphv

новый API

**Comment by noxonsu** [comment]
не работает, используем битпей

**Comment by indapublic** [comment]
беру

**Comment by caffeinum** [comment]
Если не работает, выводить сообщение, что нет подключения к bitpay, например, и своп не начинать

**Comment by caffeinum** [comment]
надо сделать двойной запрос к апи: вначале битпэй, а если фэйл, то наша нода
