### ISSUE TITLE
Неопределенный баланс пропадает иногда и вовсе не показывается

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1700]
## What is working wrong?
![image](https://user-images.githubusercontent.com/43392281/54103659-f57ca000-4418-11e9-9314-44ca279f69c3.png)

...Describe the bug briefly...
![image](https://user-images.githubusercontent.com/43392281/54072957-26e85500-42cd-11e9-9a2f-4ad549a989a5.png)

**Comment by noxonsu** [comment]
не понятно как повторить
