### ISSUE TITLE
Фи по биткойну нужно указывать

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1702]
## нужна ли нам кнопка  весь баланс на /exchange?
![image](https://user-images.githubusercontent.com/43392281/54073155-92cbbd00-42cf-11e9-8407-7ca02bf1833d.png)

**Comment by Pasha8914** [comment]
![image](https://user-images.githubusercontent.com/43392281/54073372-0cfd4100-42d2-11e9-8551-4e7df2c5ebee.png)
кнопки правильно нет, но свап нашелся и начался

**Comment by Pasha8914** [comment]
1 из 2ух 
или починить костыль, который не дает свап на всю сумму( дизейблить кнопку)
или сделать оплату фи с другой стороны или окошко пополните на фи для битка

**Comment by Pasha8914** [comment]
![image](https://user-images.githubusercontent.com/43392281/54073422-9f9de000-42d2-11e9-92d4-cbefaeeda071.png)
ну пздц конечно

**Comment by Pasha8914** [comment]
## вопросы?
1- куда зачислять
2 - как показывать

**Comment by noxonsu** [comment]
далее обсуждаем тут https://github.com/swaponline/swap.react/issues/1714

**Comment by noxonsu** [comment]
>оплату фи с другой стороны или окошко пополните на фи для битка 

оплату фи с другой стороны - сразу нет.
