### ISSUE TITLE
Добавить надпись, что в свернутом виде свап не продолжается

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1703]
## What is working wrong?

...Describe the bug briefly...
![image](https://user-images.githubusercontent.com/43392281/54073279-fefaf080-42d0-11e9-88a4-798e5df101b5.png)
![image](https://user-images.githubusercontent.com/43392281/54073281-0621fe80-42d1-11e9-8812-41795f8561a4.png)
![image](https://user-images.githubusercontent.com/43392281/54073285-1043fd00-42d1-11e9-90b8-fae0dbbe91af.png)

**Comment by noxonsu** [comment]
помойму в фоне продалжается

**Comment by Pasha8914** [comment]
да, у нас сломалось из за того, что нехватало на фи, но все же надпись о том, что лучше находится в свопе и контролировать процесс была бы не лишней

**Comment by noxonsu** [comment]
ну так а почему не выдало сообщение что не хватает на фи или это на боте сломалось

**Comment by Pasha8914** [comment]
у нас не отработан этот момент вовсе, только по токенам и эфиру

**Comment by noxonsu** [comment]
>да, у нас сломалось из за того, что нехватало на фи


>у нас не отработан этот момент вовсе, только по токенам и эфиру

ну так суть в том, чтоб показывать окно типа докиньте столько то (это как раз твое окно которое ты долго делал). получится ли повторить баг? как я понял это если пытатся продать ровно столько скоьлко на балансе. паша сделай корректный ишью ("если пытаться продать ровно столько битка, сколько на балансе, не проходит дальше второго этапа")

надпись "не закрывайте страницу" надо просто добавить в каждый текст на каждом шаге. 

итак ишью - добавить текст "Пожалуйста, не уходите с этой страницы" на каждый этап свапа прямо в текст. "Please do not leave this page"
