### ISSUE TITLE
у многих клиентов нода битпея не доступна, поменять на свою по аналогии с test-insight.swap.onlne

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1705]

**Comment by Pasha8914** [comment]
![image](https://user-images.githubusercontent.com/43392281/54103156-19d77d00-4417-11e9-9dd8-b3c94fc025c7.png)
![image](https://user-images.githubusercontent.com/43392281/54103169-25c33f00-4417-11e9-96ae-8e01095bc762.png)
![image](https://user-images.githubusercontent.com/43392281/54103173-2e1b7a00-4417-11e9-86bc-f343d6742dc2.png)
![image](https://user-images.githubusercontent.com/43392281/54103181-38d60f00-4417-11e9-8b5d-9b9a76194416.png)
![image](https://user-images.githubusercontent.com/43392281/54103191-47242b00-4417-11e9-9e49-e96fe5fe8ff4.png)

**Comment by noxonsu** [comment]
я сделал insight.swap.online но там тестнет, надо переключить как то адрес ноды в конфиге. помойму  ты настраивал именно инсайт, я нашле в нашей истории айпи

**Comment by noxonsu** [comment]
пусть страдают, ничего пока не можем поделать, наша нода не поднимается
