### ISSUE TITLE
нужно поправить стили 

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1709]
## What is working wrong?

Yes that's right
![image](https://user-images.githubusercontent.com/43392281/54087073-2cac6c00-439b-11e9-86e9-66663e7c1622.png)
  биткойн токены свап нет кнопок с инфой
![image](https://user-images.githubusercontent.com/43392281/54087295-3931c400-439d-11e9-9362-e89b8bd01c98.png)
![image](https://user-images.githubusercontent.com/43392281/54087558-bd854680-439f-11e9-98e9-c8f536100788.png)

## What should happen instead?

...Describe what do you think should happen instead in this situation...

## Steps to reproduce

- steps
- to
- reproduce

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...

**Comment by Pasha8914** [comment]
тут я не буду искать ревью от юзеров и так все ясно)

**Comment by nthgness** [comment]
![image](https://user-images.githubusercontent.com/10322798/54113843-c156ae80-441b-11e9-9957-607ae41698f5.png)

**Comment by nthgness** [comment]
![image](https://user-images.githubusercontent.com/10322798/54113901-d6334200-441b-11e9-8996-9f12364bb3ce.png)

**Comment by nthgness** [comment]
![image](https://user-images.githubusercontent.com/10322798/54115574-468f9280-441f-11e9-9759-342ee9d8f750.png)
