### ISSUE TITLE
Запрещать создавать ордера меньше, чем комиссия

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#171]
![image](https://user-images.githubusercontent.com/1909384/43239826-5a083b0a-909c-11e8-9b95-3337af828d1a.png)

А то своп невозможно завершить, потому что чувак просто не может снять свои деньги

**Comment by caffeinum** [comment]
Я в своем боте уже сделал это, можно подсмотреть:
https://github.com/caffeinum/swap.bot/commit/7875cdf8429dcd2f1946fabd8322571f1426a435#diff-fa22e35bc3a6aea358c8872804eb1af5R97

**Comment by noxonsu** [comment]
давайте запрещать все ордера меньше 20 долларов тупо и в коре и тут

**Comment by nikdementev** [comment]
7938c3fa1697efc511d026f3913653b6ca0c15b5
