### ISSUE TITLE
выводить приватники на экран?

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1710]
## What is working wrong?

выводить адреса и приватники на экран, есть товарищи которые боятся скачивать

**Comment by noxonsu** [comment]
всегда прикладывай ссылку на диалог

**Comment by noxonsu** [comment]
ок. меняем в caution кнопку "Download keys & instructions" на "Show my private keys"

**Comment by Pasha8914** [comment]
![image](https://user-images.githubusercontent.com/43392281/54103083-c36a3e80-4416-11e9-978c-3469949b5594.png)
![image](https://user-images.githubusercontent.com/43392281/54103109-d846d200-4416-11e9-9414-01dd80bf7224.png)

**Comment by Naggertooth** [comment]
Кнопку на главной тоже надо поменять и выводить в попапе?

Все данные из txt выводить в попапе?

В caution тоже сделать попап? Или лучше красивое выезжание вниз?

**Comment by noxonsu** [comment]
1. кнопку я поменял уже вроде. 
2. уже есть попап в айос версии, надо просто его активировать для всех, а не ток для айфонов

**Comment by noxonsu** [comment]
@Pasha8914 покажи клиенту, пусть посмотри так ли он хотел, внесет свои коррективы
