### ISSUE TITLE
ужас свапа без эфира

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1711]
https://yadi.sk/i/AzSc0HDdFK1fSQ
не смог провести своп без эфира на балансе, не в первый раз, работает нестабильно как то

**Comment by noxonsu** [comment]
не работал кран, его пополнили только недавно. 

Noxon, [11.03.19 06:03]
выведи куданить чтоб по https можно было видеть что кран путс

Noxon, [11.03.19 06:03]
пуст

Noxon, [11.03.19 06:04]
я уведомление настрою, надо чтоб по урлу было ok или notok

**Comment by Pasha8914** [comment]
если свап  не с ботом? платят же юзеры а не с крана?

**Comment by noxonsu** [comment]
вторая сторона не может твои  токены перевести с твоего баланса, по этому при локе эфира и токенов платит кран

**Comment by shendel** [comment]
@Pasha8914  кран нужен продавцу токенов (и только токенов) 
Если у человека есть токены, но при этом пуст эфир, он не может продать свои токены - у него нет газа на вызов (approve+createSwap). Для этого и нужен кран, а если кран не вернул транзакцию или вернул ошибку о превышении лимита, тогда продавец (в реакте) должен видеть просьбу пополнить на "фии"


> если свап не с ботом? платят же юзеры а не с крана?

кран дает им на фии, а если кран ответил отказом - просьба пополнить эфир на нужную сумму для "фии"

**Comment by noxonsu** [comment]
нет ли здесь уязвимости? просьб можно 100 отправить и ограбить бота

**Comment by shendel** [comment]
сейчас у бота ограничение - одно пополнение на один кошелек
при повторном обращении он возвращает ошибку и реакт показывает стандартное окно с просьбой пополнить на фи

**Comment by noxonsu** [comment]
сделай ограничение на общее количество таких отправок не больше 0.01 ETH
