### ISSUE TITLE
? если пытаться продать ровно столько битка, сколько на балансе, не проходит дальше второго этапа

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1714]
насколько я понял тут этот баг проявился https://github.com/swaponline/swap.react/issues/1703

**Comment by Pasha8914** [comment]
не только

**Comment by Pasha8914** [comment]
![image](https://user-images.githubusercontent.com/43392281/54102858-cadd1800-4415-11e9-82c0-f3d93e35ed66.png)
![image](https://user-images.githubusercontent.com/43392281/54103005-666e8880-4416-11e9-8b9c-0c095ea65dd6.png)

**Comment by noxonsu** [comment]
не давать начать свап ровно на ту сумму которая на балансе?

**Comment by Pasha8914** [comment]
у нас есть окошко только докинте эфира, мы делали только для эфира и токенов

**Comment by Pasha8914** [comment]
https://github.com/swaponline/swap.react/issues/1702

больше скринов
#  тут еще скрины

**Comment by noxonsu** [comment]
Паша, биткоин работает вообще подругому, должно появлятся твое окно, потому что ошибкаи та же что и при нехватке баланса в консоли, и ошибка в консоли прямо говорит "у вас не хватает на балансе на перевод + fee"

**Comment by Pasha8914** [comment]
тогда это должно срабатывать на момент нажатия на кнопку, обменяться на партиал + кнопку начать обмен в ордер бук

**Comment by Pasha8914** [comment]
а, все понял, надо доработать, вечером займусь

**Comment by noxonsu** [comment]
еще раз не надо делать отдельное окно - добавьте на фи. надо поправить БАГ в твоем окне, когда не показывается окно при недостатке баланса

**Comment by noxonsu** [comment]
связано https://github.com/swaponline/swap.react/issues/1723
