### ISSUE TITLE
"Пожалуйста, не уходите с этой страницы" на каждый этап свапа

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1715]
добавить текст "Пожалуйста, не уходите с этой страницы (?)" на каждый этап свапа прямо в текст. "Please do not leave this page (?)" 

суть в том, чтоб люди не уходили со страницы свапа, пока он не закончен. 

при наведении на иконку вопросика текст подсказки.

"В каждом шаге при обмена требуется подпись приватными ключами, которые знает только ваш браузер" 

@DariaPurtova как на англ?

**Comment by Pasha8914** [comment]
![image](https://user-images.githubusercontent.com/43392281/54102663-1c38d780-4415-11e9-973f-28a88e1271fa.png)

**Comment by Pasha8914** [comment]
еще в каком то было, особенно чувствительно с мобильного

**Comment by Pasha8914** [comment]
https://github.com/swaponline/swap.react/issues/1703 .   # Same
