### ISSUE TITLE
Вводит в заблуждение, показывает одни цифры, пыполняет другие

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1723]
## What is working wrong?

https://www.useloom.com/share/08a4a68bd36a4c4cac20cc09c2ad4829
## What should happen instead?

...Describe what do you think should happen instead in this situation...

**Comment by Pasha8914** [comment]
при всем при это число было выбранно не оптимальное
![image](https://user-images.githubusercontent.com/43392281/54173620-72b61c80-44ce-11e9-9371-bccadd33871b.png)

**Comment by noxonsu** [comment]
дубль https://github.com/swaponline/swap.react/issues/1726
