### ISSUE TITLE
Не верный подсчет курса

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1726]
## What is working wrong?

Не правильно считает, сколько я получу за данную сумму,
точнее правильно но точно нужно не так эту информацию показывать
![image](https://user-images.githubusercontent.com/43392281/54191168-17515200-4501-11e9-8b3c-11d4768786c0.png)

**Comment by noxonsu** [comment]
Илья помнишь ты тут учел комисию (отнял) https://screenshots.wpmix.net/chrome_2019-03-13_05-03-4503d91838-6e7c-496b-9e45-55d521543240.png

Noxon, [13.03.19 05:05]
из за этого появились баги, потому что когда нажимаешь ексчендж, запрос идет на ту сумму которую "вы получаете" и встречная заявка получается меньше чем 0.01 нужно пока убрать этот функционал (не отнимать комиссию в "вы получаете"). предлагаю про кописсию прямо под "обменять" написать что то типа "итоговые суммы могут незначительно отличаться из за комисси майнеров (~0.00001 BTC, ~0.00003 ETH в данный момент)"
