### ISSUE TITLE
PartialClosure: dropdown ломается при обновлении ботом ордеров

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.react#1734]
![Screenshot_20190313_003749](https://user-images.githubusercontent.com/43396375/54210032-82fbe500-452a-11e9-97cc-580919a517c7.png)
![Screenshot_20190313_004641](https://user-images.githubusercontent.com/43396375/54210039-868f6c00-452a-11e9-8a12-be6137a66e33.png)

**Comment by noxonsu** [comment]
https://screenshots.wpmix.net/chrome_2019-03-13_06-32-532b17ee2d-439d-4301-bed9-c5b4405a3614.png еще сообщение это появляется, даже когда ордера вернулись оно не исчезает
