### ISSUE TITLE
проверка всех flow 14.03

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1749]
**Send all coins with wallet**
- [x] 1. ethToken
- [x] 2. eth
- [x] 3. btc

**Swap browser2browser**
- [x] 1. swap - btc2eth (balance - btc: full, eth:full)
- [ ] 2. swap - btc2eth (balance - btc: 0, eth:0)

- [x] 3. swap - btc2ethToken (balance - btc: full, eth:full)
- [x] 4. swap - btc2ethToken (balance - btc: 0, eth:0)

**Swap browser2bot**
- [ ] 1. swap - btc2eth (balance - btc: full, eth:full)
- [ ] 2. swap - btc2eth (balance - btc: 0, eth:0)
- [ ] 3. swap - eth2btc (balance - btc: full, eth:full)
- [ ] 4. swap - eth2btc (balance - btc: 0, eth:0)

- [ ] 5. swap - btc2ethToken (balance - btc: full, eth:full)
- [ ] 6. swap - btc2ethToken (balance - btc: 0, eth:0)
- [ ] 7. swap - ethToken2btc (balance - btc: full, eth:full)
- [ ] 8. swap - ethToken2btc (balance - btc: 0, eth:0)

**Comment by Pasha8914** [comment]
отправка всех доступных валют
перевод по  валютам осуществлен, данные о транзах записаны в историю, как на странице валюты, так и в май хистори

**Comment by Pasha8914** [comment]
фул воспринял как полный баланс кошелька.
в 1 браузере создавал ордер на весь баланс, во втором через партиал находил офер и проводил обмен
