### ISSUE TITLE
поменять иконку в превью при вставке ссылки на свап онлайн в телегу и тп

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1751]
![](https://screenshots.wpmix.net/Telegram_2019-03-14_07-06-541e841153-88b7-43ec-a280-2a6d9627c49c.png) 

сейчас просто иконка, а надо выводить более понятно, что там по урл. хотя бы вот так https://screenshots.wpmix.net/chrome_2019-03-05_06-37-24aac0efc8-4365-44f7-bcd8-b25c9a6aaed1.png

я прописал og:image мету но походу это не то. нужно разобратся и сделать красивую превьюху, чтоб было понятно, что это обменник

бот для проверки в телеге @WebpageBot

**Comment by Naggertooth** [comment]
![image](https://user-images.githubusercontent.com/24671211/54359204-396ae180-4673-11e9-8377-5a5e4f34f76a.png)
Vk работает
В телеге, вероятно, кэш, сейчас попробую его обновить

**Comment by noxonsu** [comment]
что с этим не так?

**Comment by Naggertooth** [comment]
ПРы тогда не билдились
Сейчас сделаю
