### ISSUE TITLE
Incompleted swaps: не показывает текущие незавершенные свопы

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.react#1752]
В реактивном приложении несерьезно перезагружать страницу для обновления данных на ней.
Необходимо при открытии модалки загружать в нее данные сразу.

![Screenshot_20190314_161939](https://user-images.githubusercontent.com/43396375/54335554-13ded780-4675-11e9-8813-b59f01c62210.png)

**Comment by noxonsu** [comment]
какой естимейте? если 5ть минут то сделать, если час и более то холд
