### ISSUE TITLE
Требуется пополнение фи по биткойну

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1763]
## What is working wrong?

Если начать свап, а у пользователя создавшего ордер больше нет баланса (нехватает), возникает потребность внесения баланса для оплаты фи
## Steps to reproduce

создать ордер
перечислить куда нибудь почти все битки, чтоб осталась сумма, которой не хватит на фи
начать свап с другой стороны

![image](https://user-images.githubusercontent.com/43392281/54407767-d5a3ef80-472a-11e9-97e9-3980a8180a24.png)

**Comment by noxonsu** [comment]
Не давать начать свап если ты маркетмейкер и у тебя нет денег
