### ISSUE TITLE
Orderbook: first click on order is with error, but second is ok

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.react#1768]
Finish first swap btc2eth. 
Go to orderbook and try click on any order btc2eth.
Get this error:

![Screenshot_20190316_222612](https://user-images.githubusercontent.com/43396375/54475252-f8252e00-483a-11e9-9a6d-05c818f26f75.png)

**Comment by Pasha8914** [comment]
##fix https://github.com/swaponline/swap.react/pull/1767

#proof
https://www.useloom.com/share/7a6dca7d4d8d4b25a4ef49da8e6511f0
