### ISSUE TITLE
рефка

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1780]
Noxon, [19.03.19 13:01]
при реге надо чтоб елси передан ?promo=0x123123123 

например swap.online/?promo=0x123123123

Noxon, [19.03.19 13:01]
этот 0x123123123 записывать как referrer в базе у нового пользователя

--- перед футером сделать блок.

"Отправьте или расшарьте ссылку на эту страницу, каждый пользователь который придет по вашей ссылке получит для теста от 0 до 10 SWAP токенов. А вы будете получать бонус в SWAP токенах за его каждый успешный свап (в т.ч. за продажу бонусных токенов)" @DariaPurtova  как правильно

**Comment by VladislavSopov** [comment]
Share or send link on this page: every user who comes via your referral link gets up to 10 SWAP tokens. Moreover, you will earn SWAP tokens for every his ir her succesful swap; including operations with bonus tokens!
