### ISSUE TITLE
Не завершается 7ой шаг

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1786]
## What is working wrong?

...Describe the bug briefly...
![image](https://user-images.githubusercontent.com/43392281/54740433-1c9c5400-4c07-11e9-9e00-d35e0fe7c268.png)

![image](https://user-images.githubusercontent.com/43392281/54740556-7ac93700-4c07-11e9-9bc4-f8856eb272b4.png)

токен - бтс завершается
бтс-токен завершается

**Comment by noxonsu** [comment]
все еще есть этот баг?
