### ISSUE TITLE
Включить production mode у реакта на swap.online

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#179]
React Dev Tools ругается сильно
![image](https://user-images.githubusercontent.com/1909384/43363610-424681c6-9311-11e8-89fa-b836ec1cca8e.png)

И консоль:

![image](https://user-images.githubusercontent.com/1909384/43363618-703bf9e4-9311-11e8-83ec-bff6a27fdcb9.png)
https://fb.me/react-perf-use-the-production-build

**Comment by nikdementev** [comment]
0e26e71cb5e0ea4e6753a01a044bf077d6ac9825
