### ISSUE TITLE
Блокировка partial

### ISSUE THREAD

**Issue by shendel** [swaponline/swap.react#1804]
Архитектурный изъян
Сценарий:
Есть добросовестные участники рынка, продают токен "А" за биток в пропорции 1 к 100, 1 к 200, 1 к 500 с разными объемами (5, 3, 2).
Есть добросовестные покупатели на объемы 5, 3 и 2 - при их объемах - они получают предложения 1:100, 1:200, 1:500 соответственно
Появляется не доброжелатель, который создает предложение в пропорции 1 к 1 и объемом 1000
Добросовестные покупатели видят предложение 1 к 1 как самое выгодное и полностью покрывающее их запрос на спрос - недоброжелатель отклоняет их запросы на свап - как итог - не работающий свап через партиал.

Вариант решения
Блокировать пир, и скрывать его ордера, если он отклонил запрос. Таймаут "бана" минут 10

**Comment by sdwas** [comment]
Окей. В реакте можно банить пир отклонивший запрос.
Тогда нужно обходить блокировкой бота запущенного на нашем сервере.
Есть предложения, как фильтровать пиры? Может быть по ip адресу пира? У бота он не меняется, можно занести в белый лист.

**Comment by shendel** [comment]
Над этим нужно подумать. Можно попробовать не банить, а понижать в приоритете. К примеру если отклонил запрос, то минут 10 - его предложение будет в низу списка после фильтрации. Это все относится только к странице /exchange. Думаю это будет лучшим решением, тогда и бот не пострадает. Если среди маркет-мейкеров будет только бот, и он отклонит запрос, то его предложение все-равно будет доступно

**Comment by sdwas** [comment]
Таким образом бот может долго быть внизу рейтинга, если у него не будет достаточно баланса для принятия запроса или же, если кто-то настойчиво будет пытаться слить SWAP токен по наименьшему спреду. Первое маловероятно, а вот второе будет целой атакой на бота.
Пока считаю фильтрацию по ip лучшим способом.

**Comment by shendel** [comment]
Он будет внизу рейтинга, только для того человека, который получил от него отказ. Для всех остальных он будет на стандартной позиции. "Бан" локальный и можно не сохраняющийся нигде (при перезагрузки страницу обнулять его)

**Comment by Pasha8914** [comment]
у меня вопрос, насколько объективно понятие рейтинга и почему я не могу слив немного рейтинг, создать новый акк и импортировать ключи

**Comment by Pasha8914** [comment]
с айпи тоже вопрос, что если он динамический?

**Comment by Pasha8914** [comment]
почему свап будет неработающий? теперь же только после 4 шага свап заносится в стораж, как исполняющийся

**Comment by Pasha8914** [comment]
можно поставить ограничение на количество активных свапов на аккаунте, а то может возникнуть другая проблема. Кому интересно о чем я в лс

**Comment by Pasha8914** [comment]
есть вариант, сделать таблицу(который можно скролить) и в нем фильтровать ордера в приоритет ставить репутацию(отрицательная или нет), далее по выгоде и выводить в эту таблицу все ордера с доступным  частичным закрытием
