### ISSUE TITLE
лайткоин не выводится

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1807]

**Comment by noxonsu** [comment]
Noxon, [24.03.19 22:03]
привет, получилось лайткоин отправить?

M, [24.03.19 22:05]
привет,
неа,
дождался 6 подтверждений, всеравно не отправлялся,
но уже не мог ждать дольше,
через електрум скинул

M, [24.03.19 22:05]
сейчас распишу порядок действий

M, [24.03.19 22:10]
1) закинул лайт на кошелек (перевод подтвердился),
2) сделал первую отправку на адресс, все прошло отлично,
3) хотел сделать второй перевод, на первом было 2 подтверждения, 
4) нажимаю отправить всю сумму через кнопку MAX на адрес выданный бинансом,
5) справа вверху уведомление выпадает что отправлено, по факту не отправлено,
6) жду 4 подтверждения на первой отправке, повторяю, то же самое,
7) жду 6 подтверждений на первой отправке, повторяю, то же самое


(может кнопка MAX на лайте багованная? неправильно сумму пытается отправить без учета комиссии, ну или формат адреса не подошел)

**Comment by sdwas** [comment]
Все компоненты лайткоина устарели. Нужно актуализировать до уровня битка, как в реакте, так и в коре.

**Comment by noxonsu** [comment]
на холд, проблема с выводом при нажатии на max при анканфермед балансе
