### ISSUE TITLE
транзакция вылазеет за окно(сафари)

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1810]
![image](https://user-images.githubusercontent.com/43392281/54933798-0d036f00-4f69-11e9-8e2d-8c288357c38c.png)

**Comment by noxonsu** [comment]
мы хотели сюда добавить тексту. "Проверить баланс"  со ссылкой на swap.online/Bitcoin-wallet (или другой в зависимости от напрвления). Ссылку на транзакцию сделать так: open in explorer

**Comment by noxonsu** [comment]
уже поправили
