### ISSUE TITLE
Добавлять энтропии с помощью мышки

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#182]
Добавлять к секрету случайные значения с движений мышки, как на https://www.bitaddress.org/

Примечание: Я не уверен, что это работает лучше, чем window.crypto, нужно у кого-то проконсультироваться (или погуглить). Но выглядеть это будет надежно :)

**Comment by 7flash** [comment]
Это же называется биологический датчик случайных чисел - используется в КриптоПРО и считается надежнее, потому что человек непредсказуем, в отличие от компьютера, который может выдавать только псевдослучайные числа.

**Comment by caffeinum** [comment]
Да, но человек будет водить мышку одинаковыми кругами, а это уже не 32 бита энтропии, а меньше
