### ISSUE TITLE
Добавить фильтр на поле ввода сторонего кошелька

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1822]
## What is working wrong?

...Describe the bug briefly...
![image](https://user-images.githubusercontent.com/43392281/55201404-8ec7f680-520e-11e9-8716-11752e17b0ad.png)

# т.е нужно добавить такую же проверку как в импорт кейс модал

![image](https://user-images.githubusercontent.com/43392281/55201452-d2226500-520e-11e9-9046-2e2388cd0af5.png)

**Comment by noxonsu** [comment]
ну просто обвести красным и показать "This is not valid ETH address"
