### ISSUE TITLE
добавим подсказски в обмен? Гайд? пошаговую инстуркцию? нудное объяснение?

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1823]
## What is working wrong?

# Потеряли клиента из за того, что мы не донесли до пользователей далеких, от технической составляющей нашей технологии, да и смарт контрактов в целом.

https://github.com/swaponline/swap.react/issues/1826

## В итоге ему пришлось ждать рефанда ( а мне долго и нудно объяснять, что это такое и как его сделать)

#  Как итог -  они убрали виджет со своей страницы и я так понимаю, что листинг которые они так же хотели у нас заказать тоже сорвался

# Ну и последнее SegWit  чи  шо?
https://github.com/swaponline/swap.react/issues/1827

**Comment by noxonsu** [comment]
ишью созданы
