### ISSUE TITLE
Бот должен работать так, чтоб при повторном входе в свап небыло никаких багов

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1825]
# На данном этапе жизни нашего проекта, когда очень много людей заняты продажами нужно обеспечить

1 - 100% вывод из контракта, если оба зарядили, офлайн втрой участник сделки или не офнлайн 
2 - Никих багов с пополненями и оплатой фи
3- Написать антикраш систему для бота, с комплексом уведомлений на стороне фронтенда (ака опять включить еррор нотивфикейшн), которые будут отрабатывать на случай возникновения ошибки (даже не известной), для того чтоб исключить возникновения багов появившихся в процессе разработки

**Comment by nikdementev** [comment]
Знаю как сделать данный функционал и сюда же будет входить перезагрузка на мобильных и все тп
