### ISSUE TITLE
взять на себя иноформационую функцию?

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1827]
![image](https://user-images.githubusercontent.com/43392281/55202754-7529ad80-5214-11e9-92ed-c9b3c6f827e7.png)

# если конечно, я правильно понял по англ  и вообще на сколько я понимаю что такое SegWit
### (  у данного клиента есть в голове дезинформация о том, что в блокчейне битка важно, каким кошельком пользоваться ( а это на минуточку не просто юзер, который решил вложиться в криптовалюту, а менеджер работающий в ICO)) 
ну или я опять заблуждаюсь)))

p.s да, я немного сначала не понял о чем он, но суть остается та же

**Comment by noxonsu** [comment]
у нас и так написано, что можно присылать с любого кошелька или биржи (в вопросике). надо дописать (segwit and non-segwit no matter)

**Comment by noxonsu** [comment]
пока сегвит не поддерживаем (ждем bitcoin.js)
