### ISSUE TITLE
Кнопка Add gas price после завершения свопа

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#183]
Спасибо, уже не нужно
![image](https://user-images.githubusercontent.com/1909384/43366985-8409574a-934e-11e8-9e5e-cbd1fcf6e921.png)

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/43366991-96cfc760-934e-11e8-8db7-63e0cb083900.png)

**Comment by noxonsu** [comment]
кнопк адолжна быть там где зависла транза а не сверху висеть (к какой транзе она относится? добавить ко всем?
