### ISSUE TITLE
Обменный курс можно обмануть, если сменить валюты, а потом ввести сумму

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#184]
![image](https://user-images.githubusercontent.com/1909384/43367490-76b7e162-9356-11e8-8eb2-15a34add96d4.png)

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/issues/204  https://github.com/swaponline/swap.react/issues/186

**Comment by nikdementev** [comment]
c49c421191341b9edd4274d911c3f7a9cc2e1dff
