### ISSUE TITLE
сплаш скрин появляется в инкогнито мод каждый раз когда заходишь

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1841]
![](https://screenshots.wpmix.net/chrome_2019-04-08_16-50-522915a98a-3432-49b3-a989-d5da046028dd.png)

если нажать на обменник, подписатся (пуши не доступны, подписались через емейл), то если снова зайти на swap.online снова появится окно выбора оменник или кошель

**Comment by shendel** [comment]
На то он и инкогнито - каждый раз с нового листа
Тут даже с ходу и не придумать, как это решить, только "грязные хаки", и то не факт

**Comment by noxonsu** [comment]
хорошо, я скаду по другому, этот баг проявился при мне у клиента не в инкогнито моде, а в хроме. при нажатии на обмен, он перезагружает и снова видит сплаш. 

по поводу каждый раз с новог олиста - я говорю про поведение внутри сессии, т.е. когда локалсторадж не стирается, он стирается только когда закрыть баузер
