### ISSUE TITLE
ETH withdraw - перевести все не работает

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1843]
![](https://screenshots.wpmix.net/chrome_2019-04-08_17-37-45bb06173d-78f7-4af8-8303-d794aefe842e.png) тут зависло, какието ошибки в консоли

**Comment by Pasha8914** [comment]
помнишь, я писал про то что нужно сделать загрузку при отправке, бывает такое, что по какой то причине долго отправляется, а непонятно, что вообще происходит
https://github.com/swaponline/swap.react/issues/1809
