### ISSUE TITLE
Пересечение свапов в виджете

### ISSUE THREAD

**Issue by shendel** [swaponline/swap.react#1852]
## What is working wrong?

Из-за общего localStorage (для домена) есть пересечение свапов...

https://youtu.be/be6SBEhe7sg

## What should happen instead?
Предположительно это всплывающее окно о не завершенном свапе (You have not finished swaps) ...

## Steps to reproduce

Провести успешный свап в виджете на один токене
Перейти в виджет для другого токена
Зайти в кошелек
Нажать кнопку обмена

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...

**Comment by Pasha8914** [comment]
очень маловероятно, что это окно, так как оно проверяет наличие незавершенного свапа в локал стораже. Там идет проверка по валюте, т.е если валюта не та что в незавершенном свапе то не срабатывает

**Comment by Pasha8914** [comment]
там же в консоле ясно написано, что из за того, что этого токена нет в общем списке, он ищет уникальный флоу, который не может найти
