### ISSUE TITLE
Настроить exchange rate

### ISSUE THREAD

**Issue by nikdementev** [swaponline/swap.react#186]
1.  Настроить API и убрать константы из конфига

2.  Для чего нужна ?
a) улучшение UI

b) исправить ошибку

3.  Где ? 
a) Фронт

b) Создание предложения

4.  30 минут

5.  
<img width="479" alt="2018-07-29 22 50 58" src="https://user-images.githubusercontent.com/17093843/43370111-e2497f96-9381-11e8-8b03-03087f3f09b1.png">
.

**Comment by noxonsu** [comment]
константы можно оставить, это уровень торгов на старте. апи не нужно внешнее вообще, курс будет братся исходя из текущего ордербука. если текущего нет то константа.

**Comment by noxonsu** [comment]
пусть сделает леха одновременно с https://github.com/swaponline/swap.react/issues/204

**Comment by nikdementev** [comment]
c49c421191341b9edd4274d911c3f7a9cc2e1dff
