### ISSUE TITLE
custom build atomicswapwallet.io

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1871]
Add this erc20 and make custom build for domain atomicswapwallet.io

Maker (MKR)
0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/1518.png

Basic Attention Token (BAT)
0x0d8775f648430679a709e98d2b0cb6250d2887ef
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/1697.png

Augur (REP)
0x1985365e9f78359a9B6AD760e32412f4a445E862
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/1104.png

OmiseGo (OMG)
0xd26114cd6EE289AccF82350c8d8487fedB8A0C07
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/1808.png

Holo (HOT)
0x6c6ee5e31d828de241282b9606c8e98ea48526e2
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/2682.png

Chainlink (LINK)
0x514910771af9ca656af840dff83e8264ecf986ca
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/1975.png

0x (ZRX)
0xe41d2489571d322189246dafa5ebde1f4699f498
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/1896.png

Zilliqa (ZIL)
0x05f4a42e251f2d52b8ed15e9fedaacfcef1fad27
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/2469.png

Golem (GNT)
0xa74476443119A942dE498590Fe1f2454d7D4aC0d
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/1455.png

Cointorox (OROX)
0x1c5b760f133220855340003b43cc9113ec494823
Logo: https://i.imgur.com/oQx3IhF.png

STABLE TOKENS:

USDC (USDC)
0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/3408.png

TrueUSD (TUSD)
0x0000000000085d4780B73119b644AE5ecd22b376
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/2563.png

Dai (DAI)
0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/2308.png

**Comment by leonatcointorox** [comment]
Logos for atomicswapwallet.io

100px x 100px: https://i.imgur.com/fyv6ZuA.png
300px x 300px: https://i.imgur.com/XM60EYa.png
500px x 500px: https://i.imgur.com/kl8yI0H.png

**Comment by Naggertooth** [comment]
https://github.com/swaponline/swap.react/tree/atomicswapwallet.io-custom-build

**Comment by Naggertooth** [comment]
[build-mainnet.zip](https://github.com/swaponline/swap.react/files/3122636/build-mainnet.zip)

**Comment by leonatcointorox** [comment]
It doesn't seem to load.

https://atomicswapwallet.io/wallet

1. The title of the webpage needs to be changed from Swap.Online -> AtomicSwapWallet.io
2. Logo on the loading page needs to be changed with all Swap.Online texts changed as well

**Comment by noxonsu** [comment]
lets continue here  https://github.com/cointoroxecosystem

**Comment by noxonsu** [comment]
https://github.com/cointoroxecosystem/swap.react/issues/1
