### ISSUE TITLE
Новый дизайн в виджете

### ISSUE THREAD

**Issue by shendel** [swaponline/swap.react#1890]
Билд виджета с новым дизайном
https://shendel.github.io/swap.widget.testbuilds/build-testnet-widget/
Старый билд виждета 
https://seven.swap.online/widget-service/livedemo/0x0d9e614937a308438337a2999acf64fc86bf098a/8a954562-2327-40b9-8b92-4dd4594183b6/

В режиме виджета, в конфигурации доступно config.isWidget

const isWidgetBuild = config && config.isWidget

Для запуска отладки в режиме виджета используй эту комманду
npm run dev:mainnet-widget do 0x14a52cf6B4F68431bd5D9524E4fcD6F41ce4ADe9 swap 18 SWAP

**Comment by noxonsu** [comment]
ок получается надо все скрыть кроме самой формы  и будет ок
