### ISSUE TITLE
сделать возможность пошерить результат свапа 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#1906]
после того как свап завершен снизу (ниже рамки и отладочной инфы) сделать так. "Поделитесь результатам свапа в социальных сетях" ниже текстареа с текстом "Я только что обменял 1 BTC на 10 ETH через https://swap.online/exchange/btc-to-eth/?promo=0x123123123123 за 30 секунд #AtomicSwap #DEX #blockchain " где 0x123123123 адрес юзера, суммы и время подставлены из свапа. 

ниже кнопки шера телеграм https://telegram.me/share/url?url=<URL>&text=<TEXT>

такие же ссылки есть для твиттера и для фейсбука

**Comment by DariaPurtova** [comment]
Share your experience with swap online on social media "I've just exchanged 1 BTC for 10 ETH within 30 seconds! Check it out  https://swap.online/exchange/btc-to-eth/?promo=0x123123123123 #AtomicSwap #DEX #blockchain"
