### ISSUE TITLE
bch не получает полный объем данных

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1916]
![image](https://user-images.githubusercontent.com/43392281/57682307-e1e9f180-7674-11e9-9109-04d56ea1c80d.png)

После чистки кэша браузера все кк

**Comment by noxonsu** [comment]
очистка кеша не выход, так как обычных пользователей это не должно касатся, пока просто скрыть кеш у тех у кого он не может работать (у старых юзеров)

**Comment by noxonsu** [comment]
https://screenshots.wpmix.net/chrome_xDgixTjXAeGoh1Tor9uVY7jJgWoBwuSw.png где то тут ошибка (ундефайнед)
