### ISSUE TITLE
Рефанд биткоина

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#192]
три часа или два часа?

**Comment by caffeinum** [comment]
https://live.blockcypher.com/btc-testnet/tx/a52b6965f6c096b40cbeca2f18bbcd5d9aa9d636c47980b8672ebbbfd282b062/

locktime: 1532978976

![image](https://user-images.githubusercontent.com/1909384/43417974-35d2ba06-9445-11e8-9939-73f4ed17e741.png)

**Comment by caffeinum** [comment]
https://live.blockcypher.com/btc-testnet/tx/30e39923cd46a3834b7a34970f9fd7f7b7f9b0f0543ce92b5b39a7474de4c476/

вот эту самбитнул вручную после локтайма (1532979323)

**Comment by noxonsu** [comment]
она не подтверждается, значит что то с локатоймом не так. блокчипер принимает тарнзы но они тупо не майнятся нодами http://joxi.ru/823zyKpCJ3Leym

fee в транзе нормальный

**Comment by noxonsu** [comment]
короче проверил рефанд работает, но non final все время и реально еще час ждать надо

**Comment by caffeinum** [comment]
значит ставить локтайм 2 часа вместо трех? а писать три

**Comment by caffeinum** [comment]
короче наверное так и сделаем

**Comment by caffeinum** [comment]
нужно заменить, а потом проверить, что это правильно работает
