### ISSUE TITLE
UX процесса свопа, вывести оверлей с процентами просто

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#193]
Сделать сереньким будущие шаги

**Comment by caffeinum** [comment]
скачать фотошоп

**Comment by noxonsu** [comment]
какой еще фотошоп))

**Comment by caffeinum** [comment]
https://github.com/swaponline/swap.react/pull/200/files

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/pull/339
