### ISSUE TITLE
Ошибка firebase при возобновлении незавершенного свапа

### ISSUE THREAD

**Issue by shendel** [swaponline/swap.react#1931]
Если из кошелька (имея не завершенный свап) нажать "Обмен"
Покажет окно с предупреждением
![image](https://user-images.githubusercontent.com/1880211/57956761-cbf16080-7902-11e9-8f6f-45d1c747d061.png)
При нажатии "перейти к свапу" - белый экран и ошибка
![image](https://user-images.githubusercontent.com/1880211/57956791-ddd30380-7902-11e9-99fe-da8003d6d446.png)
При перезагрузки страницы - все ок - мы на странице свапа
![image](https://user-images.githubusercontent.com/1880211/57956825-f6431e00-7902-11e9-883c-5f0370634753.png)

**Comment by noxonsu** [comment]
предлагаю просто в этом случае переходить на свап с перезагрузкой страницы (т.е. как по обычной ссылке)
