### ISSUE TITLE
тест с мобилы

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#1940]
начал обмен (первый на аккаунте), проблемы:
 -так и не подключился бот;
![image](https://user-images.githubusercontent.com/43392281/58136269-d39d6600-7c70-11e9-92e1-914a7d9fbe7f.png)

-сложно держать мобилу при длительном ожидании с включенным экраном(с выключенным уходит в офлайн, как и бот)
![image](https://user-images.githubusercontent.com/43392281/58136279-dd26ce00-7c70-11e9-86cb-459c580c7f7a.png)

 -из за первого незавершенного свапа во втором бот за меня не стал платить комиссию (потому что он платит только 1 раз, если я правильно понимаю, как он работает)
![image](https://user-images.githubusercontent.com/43392281/58136324-0cd5d600-7c71-11e9-8632-ac0786fdb6d2.png)

но я даже не мог об этом узнать, до тех пор пока не перезагрузил страницу
![image](https://user-images.githubusercontent.com/43392281/58136383-33940c80-7c71-11e9-9dec-d66999ade137.png)
(сломанная верстка, + обновление компонента (раньше работало))
перевернул экран, а в это режиме вообще видимо никто ничего не делал для красоты
![image](https://user-images.githubusercontent.com/43392281/58136471-7ce45c00-7c71-11e9-830d-1dbf3a23f4d9.png)

в итоге мне нужно уйти с swap.online чтоб где то купить фи
## может предлагать купить эфир прям у нас, во время обмена?
есть и положительный момент) рефанды работают
![image](https://user-images.githubusercontent.com/43392281/58136908-3a238380-7c73-11e9-8821-114992c44fdd.png)

**Comment by noxonsu** [comment]
уже многое поправили
