### ISSUE TITLE
Обновить babel до 7й версии и добавить поддержку TypeScript

### ISSUE THREAD

**Issue by shendel** [swaponline/swap.react#1959]
Под unix-системами свежая библиотека ipfs подтягивает mortice версии 1.2.2, у которой в зависимостях p-query версии 5
В этой версии (p-query) используется TypeScript (начиная с версии 3.х.х), или раз-рабы поленились делать релиз на VanilaJS https://github.com/sindresorhus/p-queue/releases

Для того, чтобы использовать только свежие модули, нужно обновить babel до 7й версии (в 6й нет поддержки preset-typescript) и соответственно поправить конфиги WebPack

Как выполнять таск:
Нужен чистая unix-like система (под Windows подтягивает другие зависимости)

Разворачиваем react по схеме ниже

`git clone https://github.com/swaponline/swap.react.git`
`cd ./swap.react`
`git checkout develop`
`git fetch origin`
`git submodule init`
`git pull --recurse-submodules`
`git submodule update`

В package.json убираем нижнюю строчку в зависимостях (mortice) https://github.com/swaponline/swap.react/pull/1958/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R196

Устанавливаем зависимости

`npm i`

Собираем билд
`npm run build:testnet`
Получаем на выходе ошибку вида
![image](https://user-images.githubusercontent.com/1880211/58988062-8204e780-87e9-11e9-84ee-dc630e8ab603.png)

Обновляем babel, добавляем TypeScript, правим конфиг Web-packa, исправляем баги сборки, пока не будет успешно выполнен npm run build:testnet

На выходе в пуле должно быть:
Обновленный package.json
Обновленная конфигурация webpack-а

Сухой мануал по миграции с 6-7 babel https://babeljs.io/docs/en/v7-migration

**Comment by noxonsu** [comment]
на холд
