### ISSUE TITLE
Идея юзабилити. Осмыслить такой нюанс.

### ISSUE THREAD

**Issue by apelsin555** [swaponline/swap.react#198]
Пока тестил функционал, вот по юзабилити мысль появилась. 
Суть в том, что создавший заявку на обмен, должен нажать галочку сверху в правом углу, иначе обмен не запуститься. Вытекает изъян. Таким образом, создавший заявку на обмен должен 
следить за браузером, не закрывать его и быть в онлайне, и отойти от компа или заняться своими делами в этом время нельзя (иначе обмен не запустишь). А если никто откликаться не будет 3 часа, 6 часов или пол дня, получается, что облом или сиди жди пол дня в онлайне на бирже, или уходи по своим делам, но тогда обмен не получится. И в часы, когда на сайте мало народу или на первых порах, когда только начнётся раскрутка, время ожидания довольно большое. 
Может подумать вот в каком направлении. Раз человек создал заявку на обмен, к примеру, ЕТХ 1 за 2 BTC по комиссии такой-то, то значит его всё устраивает в условиях обмена. 
И нужда нажать на галочку, только привязывает человека, чтобы он в онлайне сидел и мониторил, когда откликнутся. 
Не лучше ли будет вот как. Типа, создал заявку, и всё, ушёл спать/делами своими заниматься, а потом когда кто-то откликнется на заявку, то весь обмен пройдёт автоматом без участия человека?

**Comment by caffeinum** [comment]
мы хотим добавить автопринятие на таймауте. типа есть 10 секунд

**Comment by apelsin555** [comment]
ок

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/issues/130

Апельсин, научись в заголовке ишью  писать важное. не "осмыслить такой ньюанс", а "сделать принятие заявок на свап автоматическим для маркетмейкера"
