### ISSUE TITLE
Баг. Не работает обмен в направлении noxon - swap и наоборот.

### ISSUE THREAD

**Issue by apelsin555** [swaponline/swap.react#201]
Не работает направление обмена noxon - swap и наоборот. Ордер создаётся успешно. Но когда я нажимаю на его запуск (начать обмен), то в двух браузерах уходит страница в индикатор бесконечной загрузки http://prntscr.com/kcyyhc и не отвисает.
От сумм обмена не зависит, не работает при любых суммах и даже если меняем направление обмена с noxon - swap и наоборот. Стабильно повторяется из раза в раз. Проверено в фирефокс и опера свежих версий.

**Comment by nikdementev** [comment]
сейчас нет направления такого
