### ISSUE TITLE
Не работает свап с пустого кошелька. BTC-ERC20(EURS)

### ISSUE THREAD

**Issue by josbronstein** [swaponline/swap.react#2011]
Попытались сделать обмен BTC-EURS. Я покупал евросы за биткоин, на балансе кошелька было 0 всего. Открыл оредрбук, выбрал оффер, выполнил. Все зависло на этом экране.
<img width="1436" alt="Screenshot 2019-06-26 at 14 57 38" src="https://user-images.githubusercontent.com/36883571/60178140-69ee1a00-9823-11e9-8cbb-53fd87fc6bd4.png">
В консоли пишет, что недостаточно денег, но интерфейс не предлагает закинуть битков на скрипт

**Comment by noxonsu** [comment]
уже отладили, работает
