### ISSUE TITLE
Не работает обмен ERC20 (EURS) - BTC

### ISSUE THREAD

**Issue by josbronstein** [swaponline/swap.react#2014]
Пытался сделать обмен. НЕ сработало. Все с нашего кошелька - есть и BTC и ETH и EURS
![image](https://user-images.githubusercontent.com/36883571/60195902-ada54b80-9844-11e9-9017-ab79a2e8ba01.png)
Повторяется такая ошибка
Cant finish step wait-lock-btc = 2 when on step 5
Утром работали обмены

**Comment by noxonsu** [comment]
а во втором бразуере че

**Comment by noxonsu** [comment]
у меня работает, нужно больше инфы, какие уловия приводят к ошибке
