### ISSUE TITLE
Поменять UI кошелька для новых пользователей (небольшие правки)

### ISSUE THREAD

**Issue by josbronstein** [swaponline/swap.react#2018]
Убрать все токены для новых пользователей, оставить только Bitcoin, Bitcoin Cash, Ethereum, Eos, Litecoin, USDT, SWAP, EURS - в таком порядке. 
SWAP и EURS должны быть большими буквами
Кнопку Hidden coins заменить на Hide/Add Coins

**Comment by noxonsu** [comment]
надо ввообще все erc20 делистнуть, заманали
