### ISSUE TITLE
Не работает рефанд

### ISSUE THREAD

**Issue by josbronstein** [swaponline/swap.react#2019]
Повисло два свопа. Рефанд не работает
Вот первый
![image](https://user-images.githubusercontent.com/36883571/60257481-34593780-98dc-11e9-8e22-a7421663c298.png)

Вот второй
![image](https://user-images.githubusercontent.com/36883571/60257530-4aff8e80-98dc-11e9-962d-e2b38a420070.png)

**Comment by noxonsu** [comment]
а биткоинн туда ушел?

**Comment by sdwas** [comment]
Что пишет в консоли во время клика по кропке try refund?

**Comment by noxonsu** [comment]
@josbronstein нажми там debug information и скинь сюда

**Comment by sdwas** [comment]
Важно посмотреть в консоль, так как там отлавливается ошибка, и чаще всего там просто варнинг о том, что не успел разлочиться скрипт и нужно попробовать позже. 
Я хочу еще добавить в саму кнопку это сообщение, в отдельном ишью.
