### ISSUE TITLE
не могу вывести биткоин с баланса

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#203]
http://joxi.ru/Vrwbk9lCOkExgA

**Comment by noxonsu** [comment]
давай так, если битпей лежит выдавать hex транзакцию со текстом "test-insigth.bitpay.com is down. Broadcast this transaction via another public node: xcvxcvxcv" и hex транзакции. в общем желательно показывать hex транзы

**Comment by nikdementev** [comment]
#170

**Comment by nikdementev** [comment]
#170
