### ISSUE TITLE
улучшение формы добавления ордера (поле купить у него NaN. он вводит в поле купить сумм 2 и Sell сбивается на NaN)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#204]
человек хочет купить 2 эфира за 0.005 биткоина. он вводит в поле продам 0.0005 btc. А в поле купить у него NaN. он вводит в поле купить сумм 2 и Sell сбивается на NaN. Надо чтоб в этом случае курс сам высчитывался.

**Comment by nikdementev** [comment]
c49c421191341b9edd4274d911c3f7a9cc2e1dff
