### ISSUE TITLE
отправлять данные по введенным в форму суммам

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#2041]
если человек ввел какуюто сумму то надо отправлять сумму которую он ввел и валюту которую и сколько ему посчитала форма и адрес человека  на https://wiki.swap.online/stat.php 

тоесть когда у нас пересчитывается сумма к отправке ик  полчению обе этих суммы надо отправлять на бэк, мы будем анализировать потом это.

**Comment by sdwas** [comment]
Какой формат(body) запроса должен быть?

**Comment by noxonsu** [comment]
да любой, какой проще, ну пост запрос например
