### ISSUE TITLE
все чеки балансов засунуть в setinterval

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#206]
иногда чек баланса (чек скрипта, чек баланса адреса бтс или эфира) не проходит, нужно через некоторое время повторить запрос, но этого не происходит и свап зависает. помогает только обновление страницы

**Comment by noxonsu** [comment]
где комит?

**Comment by nikdementev** [comment]
9fdf35065edbefbce92be387f8d4aa7ea62951af
