### ISSUE TITLE
setinterval для отправки транзакций

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#207]
если апи в дауне (битпей ошибка 525 ) то надо через некоторое время повторно пытатся отправить транзу. сейчас нужно обновлять страницу для  этого

**Comment by noxonsu** [comment]
так и что с этим  ишью?

**Comment by caffeinum** [comment]
я думаю, лучше показывать кнопку "переотправить" транзакцию, если была ошибка запроса
