### ISSUE TITLE
запретить начало свапа на мобиле

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#2082]
когда человек пытается начать своп показывать ошибку, своп не начинать

"Мы рекомендуем использовать десктопный браузер, т.к. мобильные браузеры не стабильные. Пожалуйста, используйте десктопный браузер"

"We recommend using a desktop browser, because in a mobile browser the swap may suddenly stop (someone will call or the screen will go out). Please use the desktop browser"

**Comment by noxonsu** [comment]
пока на холд, с мобилы норм свапается, проблема с btc только, потом в общем подумаем как лучше

**Comment by DariaPurtova** [comment]
We recommend using a desktop browser. By using a desktop browser you will ensure that your swap won't be interrupted by an incoming call or the screen lock. Please use the desktop browser.
