### ISSUE TITLE
вытащить биткоин с застрявших свопов в сторону бота

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#2086]

**Comment by noxonsu** [comment]
своп номер одиин https://screenshots.wpmix.net/Telegram_bIHbWRKNmWO0GjTOxhp4IvNF88ZBGg4r.png
секрет - https://screenshots.wpmix.net/Telegram_diRvHNrytRkNbuYBmmNf782J7Mcnuwce.png (придется со скрина перепечатывтаь хех)

**Comment by shendel** [comment]
https://www.blockchain.com/ru/btc/tx/172c791e1ad0f32cf55679b5e9706d48e71d6a00455b887e5ecf1178bf4e88fa

**Comment by noxonsu** [comment]
ты только с одного вытащил, там два застралоя

**Comment by shendel** [comment]
https://www.blockchain.com/ru/btc/tx/6b2b151c59dee07432888a67177a83486ec7d1f32b7615e8904b65eefcfb5a39
