### ISSUE TITLE
в свапе чекатть потрачены ли деньги уже с контракта битка чтоб не давать делать рефанд если он сделан или выведены средства другим способом

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#214]
http://joxi.ru/l2ZlwQ6cwawBar в этом случае надо писать, что адрес контракта пуст и нельзя сделать ни транзакцию на рефанд ни собсно наать на трай рефанд. "maybe the refund is already executed"

**Comment by nikdementev** [comment]
af88b4e4908179e672d2d5c01bd9432eccbefbb6
