### ISSUE TITLE
в истории нерпаивльно показывается сумма битконв

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#215]
http://joxi.ru/nAybyM8CYWY4dr там просто много выходов, только один из них связан с нашим адресом. а в данном случае показан другой выход, не наш адрес

**Comment by vasyan** [comment]
@noxonsu скриншот протух.

**Comment by noxonsu** [comment]
@ivan-khludov http://joxi.ru/12MZwNjHML0BnA транза https://insight.bitpay.com/tx/e14c463150ee8fd60070cbb75c3809ff23ee6be5c068ed73e89b4e3ac67e81ac выводится первый аутпут по порядку, а их там много, надо выцепить с нужным адресом
