### ISSUE TITLE
Обмен btc-erc20 вылезла непонятная ошибка

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#2157]
## What is working wrong?

вылезла ошибка 
Error in the execution of the token contract!

Perhaps there is an additional commission on the contract side or the error occured for another reason

## перезагрузил страницу))
свап дошел до конца))) WATTTT? к чему тогда ошибка))
https://insight.bitpay.com/tx/3b2b4baf7cfa6174c8e16842fe358ccc68d6be5cb5b3e0ae317233b1805db1cf

![image](https://user-images.githubusercontent.com/43392281/62849114-bcc35880-bd21-11e9-81f2-d68c28d06e82.png)
еще неизвестные мне подарили эфира)) чуток правда
![image](https://user-images.githubusercontent.com/43392281/62849148-e5e3e900-bd21-11e9-8cb8-96fd77a35619.png)
но на несколько свапов

**Comment by shendel** [comment]
Тоже пару раз проскакивала такая ошибка, но у меня она сама через секунд 10 изчезала и продолжался свап
Я больше склоняюсь, что это связано с загруженностью блокчейна эфира, не удалось вызвать createSwap,

**Comment by noxonsu** [comment]
не неизвестные, это кран тебе подарил немного эфира и восклицательный знак видимо появился потому что не хватало эфира
