### ISSUE TITLE
провести свап в мейннете с двух окон и записать это на видео

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#217]
записать скринкаст, что все работает. показать историю, что балансы поменялись, в истории отобразилось, показать в публичных експлорерах, что все прошло и тп. в общем полная запись пруфа что система работает. прикрепить сюда.

**Comment by nikdementev** [comment]
[сам свап](https://www.youtube.com/watch?v=2HrbkWXM9wc&feature=youtu.be)
[показываю историю и все тп](https://www.youtube.com/watch?v=8S64HpJPR-I&feature=youtu.be)
лучше смотерть в 2х
была 1 проблема на 5 шаге проверил баланс до того как он обновился, пришлось перезагрузить 1 страницу

**Comment by noxonsu** [comment]
не принимается, проблему надо исправить, так же http://joxi.ru/Vm69NR7FDXQZlr

**Comment by noxonsu** [comment]
https://etherscan.io/tx/0x04182e769b1ccf33bd61d3508dd0a226e2b76e2aa86084060f7aca1497e145f7
