### ISSUE TITLE
Вывод денег на максимальную сумму не у каждой валюты работает

### ISSUE THREAD

**Issue by apelsin555** [swaponline/swap.react#220]
Вывод денег на максимальную сумму, которая есть на балансе, не работает при выводе эфира, биткойна, свапа. А у ноксонов норм работает.  Под максимальной суммой подразумеваю всю сумму, какая есть на балансе. Кнопка "трансфер" просто не нажимается. Стоит немножко уменьшить сумму вывода и вывод денег проходит успешно.

**Comment by nikdementev** [comment]
не может быть такого) эфир да весь ты не выведешь тебе комиссия нужна на вывод с бтс тоже самое с токенами тебе надо чучуть эфира для вывода

**Comment by apelsin555** [comment]
Тогда надо подписать во всплывающем окошке или где-то, что комиссия на вывод столько-то процентов и сумма составляет столько-то.  А то у нас не подписано ничего нигде.
