### ISSUE TITLE
Баг. Обмен застопорился на 6 шаге

### ISSUE THREAD

**Issue by apelsin555** [swaponline/swap.react#222]
Продавал 0.2 BTC за 0.01096312 ETH. В браузере, где создавал заявку на обмен он прошёл успешно все шаги (всё ок, проверяйте баланс), а во втором браузере (опера свежая версия) даже за 9 минут дальше 6 шага не сдвинулось (BTC Owner successfully took money from ETH Contract and left Secret Key. Requesting withdrawal from BTC Script. Please wait). В консоли есть ошибки. Видео ошибок https://yadi.sk/i/pkmYbyqa3ZqBMu

UPD
сейчас тестил другие разы, после нескольких успешных разов, ошибка ещё раз повторилась и снова во втором браузере, который откликается на чужую заявку на обмен (по совпадению снова в опере свежей версии)! Тоже на 6 шаге. Ошибки чуть другие в консоли https://yadi.sk/i/ldZbCdom3ZqHXB

**Comment by apelsin555** [comment]
UPD
сейчас тестил другие разы, ошибка ещё раз повторилась и снова в том браузере, который откликается на чужую заявку на обмен! Тоже на 6 шаге. Ошибки чуть другие в консоли https://yadi.sk/i/ldZbCdom3ZqHXB

**Comment by nikdementev** [comment]
отлетел API битпей по этому так
