### ISSUE TITLE
Баг. Зависла кнопка во втором браузере

### ISSUE THREAD

**Issue by apelsin555** [swaponline/swap.react#223]
Пробовал продать 1 BTC за 0.05481614 ETH. Во втором браузере зависла кнопка Sign вот в таком состоянии http://prntscr.com/kdtjeb а потому обмен не состоялся.
Обращаю внимание, она именно зависла вот в таком состоянии на 8 секунде и таймер не отсчитывается  в меньшую сторону, 
а нажатия на  данную кнопку тоже ни к чему не приводят. Много минут прошло не отвисло. Из консоли ошибки https://yadi.sk/i/_VzeEwqP3ZqF7J (то есть речь не идёт о том, что я забыл на неё нажать). Ранее такого зависания этой кнопки не встречал ни разу.

**Comment by nikdementev** [comment]
у тебя есть незавершенный свап на этом аккаунте по этому новый ты начать не можешь нужно закрыть прошлый или сделать рефанд
