### ISSUE TITLE
Единичный баг. Остновка обмена на 5 шагах. 

### ISSUE THREAD

**Issue by apelsin555** [swaponline/swap.react#224]
Пробовал продать 1 BTC за 0.05481614 ETH. Остановился обмен в двух браузерах на 5 шаге (10 минут ждал, к след шагу не переходит)! 
В браузере, в котором создавал заявку на обмен есть ошибки в консоле (опера свежая), а в браузере в каком принимал заявку, ошибок нет (фирефокс свежая).
Видео консоли https://yadi.sk/i/_oRoXvXs3ZqBV2 Перепроверил всё с аналогичными параметрами, во второй раз прошло без остановки на данных шагах

**Comment by nikdementev** [comment]
у тебя не хватает баланса ефиров что бы снять деньги с контракта

**Comment by apelsin555** [comment]
Вообще то там, во втором браузере, было на балансе ETH 1.7944193650911429 Так что эфира точно хватало.

**Comment by nikdementev** [comment]
да не продажа а тот человек который его покупает должен снять эфир с контракта но у него нет ефира по этому так
