### ISSUE TITLE
Если я потерял файл бэкапа, сделать кнопку для повторного скачивания

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#231]
#  Job. What we need to do
Если я потерял файл бэкапа, сделать кнопку для повторного скачивания

# Purpose. 
Чувак нажал "Да", но ничего так и не скачал. А потом хватился и хочет сохранить приватники

# Where 
swap.react

# Estimate time 
30 минут

# Additional
Я думаю лучше всего это сделать внизу, где на тестнете кнопка Exit

**Comment by nikdementev** [comment]
cd79a7faf5c585839d3c7ac868808a24b06e46ec
