### ISSUE TITLE
Поправить форму инвойса btc

### ISSUE THREAD

**Issue by DariaPurtova** [swaponline/swap.react#2354]
![Screen Shot 2020-01-27 at 8 13 00 PM](https://user-images.githubusercontent.com/40612252/73199532-0ecc2f00-4146-11ea-9f55-8a56967f79d9.png)
1. Поплыли строки
2. Ваш контакт = Your contact
3. В описании комментария можно написать: Пожалуйста уточните за что выставлен счет "Please specify the purpose of the invoice"
4. В описании суммы уточните валюту “Enter the amount in BTC”
_(В старой версии было удобно то, что сумму можно было вводить в валюте (руб/долл) и форма сама конвертировала эквивалент в крипте)_  
5. Шрифты названия строк и данные, которые туда вводятся сделать разными (сейчас и то и то жирным черным - не симпатично)

“Address for invoicing” можно скрыть или показывать опционально, если на него кликнуть

**Comment by trubnikovr** [comment]
Эту задачу сделал другой программист
