### ISSUE TITLE
ошибки ! даже ошибки с другой стороны. Нельзя тупо сидеть и ждать

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#237]
если завис свап больше чем на 5ть минут попытатся выяснить в чем дело. как минимум пингануть вторую сторону, если она офлайн то показать человеку "человек ушел в офлайн"

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.core/pull/101/commits/e1c5f885eecab747daaa3ce44409c72d9b9b9d23

**Comment by noxonsu** [comment]
помойму ipfs может сказать что пир офлайн, давайте это сделаем самым топорным способом 
![](https://airdb.wpmix.net/Telegram_2018-12-03_08-08-51ef8a23a1-fec2-42ed-8f5a-f64d80de0b12.jpg)

**Comment by noxonsu** [comment]
- [ ] открыть браузер алисы и боба, запустить свап.
- [ ] в обоих браузерах показано что онлайн
- [ ] во время свапа выключить фладку боба, у алисы должно быть показано что второй offline
- [ ] боб снова возвращается в свап (или просто онлайн) у алисы показывается что online
- [ ] алиса закрывает браузер, у боба показывается offline
