### ISSUE TITLE
Не показывать столько десималс в балансах

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#249]
![image](https://user-images.githubusercontent.com/1909384/43798716-17efc7d6-9a94-11e8-8cc9-c14c3884b7b7.png)

**Comment by vasyan** [comment]
@caffeinum Какое количество оставить?

**Comment by caffeinum** [comment]
@vasyan я думаю 8, но можно показывать при наведении все остальные (@nikdementev что думаешь)

**Comment by nikdementev** [comment]
31bd7b68db245fd3f34097867ce6a2ab0b1f9b77
