### ISSUE TITLE
ссылка на конкретный ордер

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#252]
Noxon ⚡️, [09.08.18 10:05]
http://joxi.ru/p27bJ37CoDQDYm добавь сюда значек линка, линк на свап. чтоб я могу копирнуть ссылку и скинуть другому человеку

Noxon ⚡️, [09.08.18 10:06]
ссылка будет вида https://testnet.swap.online/exchange/btc-eth#id и ведет на тот же список но мой ордер подсвечен

+значек крестика стал обьемным (сам крестик верни в центр круга)

**Comment by nikdementev** [comment]
3528bca4a61cb5f6bb3549a0dcc86b010692d1bf
