### ISSUE TITLE
сделать проверку чтоб при попытке начать свап если денег недостаточно (временно) не давать начать свап

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#253]

**Comment by nikdementev** [comment]
f427b2806ee38348ac8bd8efc138ba8b3b7ed85d

**Comment by noxonsu** [comment]
не учитывается unconfirmed транзакции. у меня на блансе битка есть бабки, но есть unconfirmed и свап запустился (и залип на создании скрипта битка)

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/ed82b2d5a22d309d27c3ff8a4cf69b80c9171863
