### ISSUE TITLE
SEO задача усовершенствовать структуру главной страницы

### ISSUE THREAD

**Issue by 1maxim** [swaponline/swap.react#256]
Немного изменить структуру главной страницы, чтобы она содержала полезную информацию с нужными ключевыми фразами, для того чтобы ее заметил поисковик | https://wireframe.cc/8WBBzq

Вопросы или обсуждения https://t.me/userpick

**Comment by indapublic** [comment]
@1maxim @noxonsu Будет ли переработана структура вайрфрейма при условии, что концепция поменялась с биржи на кошелек?

**Comment by 1maxim** [comment]
@indapublic @noxonsu 
по вайрфрейму фактически изменений от меня нет, так как просто сетка заказов заменяется на данные по кошельку, весь остальной контент будет тем же (желательно)
