### ISSUE TITLE
Проверить возможность быстрой конвертации в приложение на мобилы

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#269]
ресерч, сколько  будет стоить сделать приложение (которое пройдет в сторы). делает @Eljoy

**Comment by caffeinum** [comment]
это быстро, мы делали за пару вечеров приложение для радио (нативное)

**Comment by Eljoy** [comment]
Если главная цель переиспользовать большую часть наработанной логики то лучшим решением будет использовать [React Native](https://facebook.github.io/react-native/). SounCloud утверждают, что их команда разработчиков, смогла[ переиспользовать 85 процентов кода](https://developers.soundcloud.com/blog/react-native-at-soundcloud) при написании мобильного приложения, используя ReactNative.

Вещи, которые придется изменить:

1. Верстка. React Native использует [ Yoga layout](https://github.com/facebook/yoga) для позиционирования элементов и стилей. Никакого CSS. [Подробнее](https://facebook.github.io/react-native/docs/flexbox). Так что всю верстку элементов придется переписать. Плюс в том, что yoga использует в основе flexbox, который используется в swap.react, что упростит переписывание. 

2. Ряд методов, которые недоступны в React Native. Например localStorage придется заменить на [AsyncStorage](https://facebook.github.io/react-native/docs/asyncstorage.html). А все анимации реализуются, используя [Animated API](https://facebook.github.io/react-native/docs/animated).

3. Дизайн. Его нужно адаптировать под малые экраны. С другой стороны, возможно для каждой из платформ стоит сделать его вид более нативным. То есть так, чтобы приложение соответствовало гайдлайнам [Apple](https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/) / [Google](https://material.io/) соответственно (не обязательно). 

Что будет круто настроить:

1. [React-over-the-air-updates](https://facebook.github.io/react-native/docs/animated) позволит обновлять js часть приложения минуя стандартную процедуру рассмотрения изменения Google/Apple.

С учетом закона Мерфи, моя оценка трудозатрат: 30-40 часов. 

Интересные ссылки:

1. [NativeBase](https://docs.nativebase.io/) качественный ui framework для ReactNative
2. [Инструкция](https://gist.github.com/dougbacelar/29e60920d8fa1982535247563eb63766) как настроить Ethereum JS API для ReactNative.
3. [Список приложений](https://facebook.github.io/react-native/showcase.html), которые используют ReactNative.

**Comment by Eljoy** [comment]
Проверил библиотеку [bitcoinjs-lib](https://github.com/novalabio/react-native-bitcoinjs-lib). Работает. Вернее не сама она, а ее форк [react-native-bitcoinjs-lib](https://github.com/novalabio/react-native-bitcoinjs-lib).  Проверяю web3 и ipfs pub sub

**Comment by Eljoy** [comment]
Проверил web3, удалось подключить согласно [инструкции](https://gist.github.com/dougbacelar/29e60920d8fa1982535247563eb63766). 

Проверяю ipfs pub sub

**Comment by Eljoy** [comment]
Мне удалось запустить ipfs js внутри React Native используя [nodejs-mobile](https://code.janeasystems.com/nodejs-mobile/getting-started-react-native). 
То есть обращение к либе ipfs происходит не напрямую, а через мост в асинхронном режиме, который связывает React Native код и NodeJS код.

Подводя итог: получилось запустить все три испытуемые библиотеки с некоторыми особенностями, которые указал в этом треде выше.
В итоге, чтобы запустить swap.core/swap.react на мобильные платформы используя React Native, необходимо будет сделать, что то вроде react-native-swap.core, react-native-swap.react, где будут внесены изменения в работе касательно этих библиотек и другого функционала, который нельзя использовать напрямую в окружении React Native.

**Comment by Eljoy** [comment]
Касательно WebView решений, таких как [Apache Cordova ](https://cordova.apache.org/)/ [PhoneGap](https://phonegap.com/).
Новость, что Apple планирует удалять гибридные приложения, использующие WebView, оказалось [уткой](https://jzeferino.wordpress.com/2017/12/19/apple-spoofed-email-with-review-policy/).

Вот [примеры](https://phonegap.com/app/) гибридных приложений, использующих WebView и допущенных в сторы. С другой стороны, Apple может не пустить в стор приложения, которые являются чистыми портами веб сайтов. 

> 2.12 Apps that are not very useful, are simply web sites bundled as apps, or do not provide any lasting entertainment value may be rejected

Подробнее [тут](https://www.quora.com/Is-it-possible-for-a-web-app-to-be-accepted-on-Apples-App-Store).


Проблемы таких решений:

1. Производительность: приложения, использующие WebView кажутся тормознутыми, задержка отклика на действия заметна. Судя по отзывам к опубликованным приложениям они падают довольно часто.

2. Различие между движками WebView на андроиде и IoS. 
> The JavaScript code included in our Hybrid app runs in a WebView, which is essentially a native browser bundled with app. On Android, our code runs in a modern Chromium-based WebView that for the most part works exactly as it should. On iOS, we have the choice of running our code in one of two WebViews: UIWebView or WKWebView.

Подробнее, вместе с тем, к чему это приводит можно прочитать [тут](https://hackernoon.com/if-it-werent-for-apple-hybrid-app-development-would-be-the-clear-winner-over-native-ae64fa37ad48).

3. Google начнет блокировать OAuth requests, исполняемые из WebView. Это может коснуться и  Firebase Cloud Messaging. Вряд ли это приговор, но головной боли может добавить. [Подробнее](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html).

4. Непонятная ситуация насчет ipfs. [Runtime Support: Cordova #834](https://github.com/ipfs/js-ipfs/issues/834)

Лично я бы использовал React Native, из за производительности, большей прозрачности насчет допуска в сторы и комьюнити. Там все равно большую часть уже написанного кода можно будет переиспользовать.
