### ISSUE TITLE
Identicon для свопов

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#273]
В списке истории невозможно понять, чем один свап от другого отличается. Я думаю, это можно решить, если добавить:
- четкие даты и время (напр. "начат 15 минут назад")
- идентиконы для каждого свапа

**Comment by noxonsu** [comment]
ну и не доабвлять в свапы если нет хендшейка (таких у меня большинство, там ничего никто не заморозил но они висят)

**Comment by meati** [comment]
взял себе

**Comment by nikdementev** [comment]
@Nevermind2121
