### ISSUE TITLE
До следующего шага осталось примерно 12 секунд...

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#274]
### Предложение

Выводить таймер "осталось примерно 30 секунд до следующего шага"

**Comment by meati** [comment]
взял себе

**Comment by noxonsu** [comment]
давайте продключим даталейер, мне нужен гуглак я добавлю в гугл аналитикс. 

нужно учесть что даталейер может быть не доступен. обязательно проконсультироватся с  (телега) @chromebookman он всю эту стату собирает и настраивает тоже

**Comment by chromebookman** [comment]
Здесь внизу новые события, их нужно добавить в JavaScript проекта.
Важно: в местах, где нужен указать валюту, например в графе Event Label или в Яндекс метрике {пользовательские параметры}, там есть такие пункту как BTC or USDT, ETH or ERC20 и тд.

Нужно сделать так, чтобы в момент передачи этих событий, передавалась именно та валюта, с которой происходит Swap у юзера. В событиях не должно быть "или то, или то", должна быть только конкретная валюта. Тогда мы сможем что-либо отслеживать в аналитике.

https://docs.google.com/spreadsheets/d/1l-O0IujhokEseMTwmT49DgvNPZrzY25TPRYISKmrbK0/edit#gid=256167239

![image](https://user-images.githubusercontent.com/38112180/44726332-2c740f80-aae0-11e8-9da3-521703c174be.png)

**Comment by chromebookman** [comment]
Кстати, Яндекс метрику же я сам настраиваю, так что всё ок :)

**Comment by chromebookman** [comment]
```
yaCounter48876458.reachGoal('swap-sign', {currency: ETH or ERC20 or BTC or EOS});

ga('send', {hitType: 'event', eventCategory: 'Swap', eventAction: 'swap-sign', eventLabel: 'ETH or ERC20 or BTC or EOS'});
```

Вот смотрите, пример кода, который вы дорогие разработчики должны засунуть в JS код вашего приложения.

Вот где написано 
`**eventLabel: 'ETH or ERC20 or BTC or EOS'**`
или

` **{currency: ETH or ERC20 or BTC or EOS}**`

Там должно быть что-то одно, одна валюту, которую меняет пользователь

**Comment by chromebookman** [comment]
Опытным путем выяснили, что работает такой код
`tracker.send({hitType: 'event', eventCategory: 'Swap', eventAction: 'swap-sign', eventLabel: 'currency'});`

Перед этим нужно вызывать 1 раз такой код (при загрузке сайта)
`tracker = ga.getAll()[0];`

**Comment by chromebookman** [comment]
Короче где currency, нужно подставлять актуальную валюту, на которую происходит обмен у юзверя
и у ГА, и у Яндекс Метрики коллеги
yaCounter48876458.reachGoal('swap-sign', {currency: currency});

**Comment by noxonsu** [comment]
пока прсото собираем аналитику, сам атймер не выводим

**Comment by chromebookman** [comment]
Окей понял

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/2862a031f458fbb1c4683d8a6a509fad7c839595
