### ISSUE TITLE
Перепрыгнул шаг с получением секрета, теперь в разломанном состоянии

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#275]
## What is working wrong?

При обмене каким-то образом перескочил шаг получения секрета, и теперь браузер пытается снять деньги со скрипта, не зная секрет. Перезагрузка не поможет, потому что мы уже на лишний шаг впереди.

## What should happen instead?

Нужна возможность забрать деньги, зная секрет. Его хотя бы можно получить вручную через блокчейн.

## Steps to reproduce

У меня получилось, когда я запустил два свапа в браузере одновременно, но думаю, что дело не в этом.

## Your system charateristics

- Browser: Google Chrome latest
- OS: OS X High Sierra
- Mainnet or Testnet: Testnet

## Does this affect atomic swap flow?

- [x] yes
- [ ] no

## Are real funds at risk?

- [x] yes
- [ ] no

## Screenshots

![image](https://user-images.githubusercontent.com/1909384/43997635-979d3a10-9de9-11e8-8188-f068b0691e3d.png)

```
{
    "step": 7,
    "signTransactionHash": null,
    "isSignFetching": true,
    "isMeSigned": true,
    "secretHash": "4941cf5b2ca5372124e350726fccff315b409ac4",
    "btcScriptValues": {
        "secretHash": "4941cf5b2ca5372124e350726fccff315b409ac4",
        "ownerPublicKey": "03710d8c8dcb34d83e0d74ba40e3703419aff760bf39de25a615496f31ef120185",
        "recipientPublicKey": "03994251b69f775aeb2fbbfa654e0870bdeff604dc0098e54d0d0e19ed45e7ff29",
        "lockTime": 1534047688
    },
    "btcScriptVerified": true,
    "isBalanceFetching": false,
    "isBalanceEnough": true,
    "balance": 5.49837791259855,
    "btcScriptCreatingTransactionHash": "6ab99c04362c018fdf4c226b33861148bdc7772272d406a4dca7688f57967740",
    "ethSwapCreationTransactionHash": "0xbad76da322c89e9b48d9c08168e9fa0e00f95ce82f82a074111fbf92152351f0",
    "isEthContractFunded": true,
    "secret": null,
    "isEthWithdrawn": true,
    "isBtcWithdrawn": false,
    "refundTransactionHash": null,
    "isRefunded": false,
    "isFinished": false
}
```

## Additional info

Создание контракта:
https://rinkeby.etherscan.io/tx/0xbad76da322c89e9b48d9c08168e9fa0e00f95ce82f82a074111fbf92152351f0

ID свопа: https://testnet.swap.online/swap/ETH-BTC/Qmc68vMus87Whv2zqogQEF2bskNzHPpSS4EWQkaeC1iqu8-1534036336438

Данные свопа: (секрет уже публичен, деньги забрали!)
```
<input> (address)
0xf6f3da1f5d91dcdd596f7d3bbf41f59f112ffa58
<input> (address)
0x75c1008c73a1c5f8015e9640e917f5acb86de81f
 secret bytes32, secretHash bytes20, createdAt uint256, balance uint256 

[ swaps method Response ]
  secret   bytes32 :  0x08d94fc6076cf5c453643808f91a44d529ab6d156811135167afeb213fb1fe80
  secretHash   bytes20 :  0x4941cf5b2ca5372124e350726fccff315b409ac4
  createdAt   uint256 :  1534036913
  balance   uint256 :  0

```

**Comment by noxonsu** [comment]
никита вроде исправлял этот баг (проблема с улевым секретом, надо пытатся брать его из нескольких местт)

**Comment by nikdementev** [comment]
такого бага не будет больше, закрой это ишуе, но сделай в core дополнительный метод получения секрета

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.core/pull/101
