### ISSUE TITLE
перенести футер из лендинга в реакт

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#281]

**Comment by noxonsu** [comment]
http://landing.swap.online

**Comment by noxonsu** [comment]
желательно не переносить лишние стили и другой мусор

**Comment by noxonsu** [comment]
на мобиле треш какойто, убрать вообще на мобиле стики

**Comment by Spoki4** [comment]
@noxonsu Если всё ок, то можно закрывать
