### ISSUE TITLE
Более детальный рефанд, при свапе на контракте 

### ISSUE THREAD

**Issue by nikdementev** [swaponline/swap.react#286]
nk, [15.08.18 10:46]
заходят два пользователя на сайт начинают свап
- им пишет пожалуйста сделайте рефанд так как ваш прошлый свап не завершен,
1 случай
- оба нажимают рефанд 
2 случай
- только бтс нажимает рефанд мы это можем посмотеть из состояния свапа,
3 случай
- бтс нажал рефанд а эфир нет
тогда бтс надо говорить подождите необходимо что бы другой человек сделал рефанд

nk, [15.08.18 10:47]
когда нажимаешь рефанд
надо что бы появляся лодер с хешем транзакции 
он есть такой если сделаешь withdraw на странице wallet увидишь пример

**Comment by nikdementev** [comment]
#285 #242 #276

**Comment by nikdementev** [comment]
#276

**Comment by noxonsu** [comment]
>бтс нажал рефанд а эфир нет тогда бтс надо говорить подождите необходимо что бы другой человек сделал рефанд

Зачем? если кто то не нажал рефанд то это его проблема

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.core/pull/101/commits/f2112a5b5ecfeb9b1e7fb8254a5255f5190cb8d5
