### ISSUE TITLE
Multiple profiles

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#287]
@vladiuz1 commented on [Wed Aug 15 2018](https://github.com/swaponline/swap.core/issues/89)

Ok

Another important invention.

## Multiple profiles. 

Each user must have multiple profiles in the browser.

A profile is basically a root key. Identifier of the profile is its ecdsa public key. Handle - a name of profile.

The profile is basically a localstorage prefix where the data is saved. Data being - the root prv/pub keys, list of wallets created (ethereum, bitcoin, eos?). We don't have to create wallets for cryptos guy is not going to use.

![screenshot_2018-08-15 edit fiddle - jsfiddle](https://user-images.githubusercontent.com/22708849/44141121-dc964fb0-a084-11e8-9102-0fdc7d625e4d.png)

To access the profile option or change profile, or create new, or import you will need to clikc on the profile gravatar.

I suggest adding a few options to profile handling:

 * Adding profile
 * Backing it up (writing down seed phrase).
 * Importing profile (using a seed)
 * Locking/unlocking profile (decrypting private keys). Profiles are always locked by default.

![image](https://user-images.githubusercontent.com/22708849/44142521-0f244ffa-a089-11e8-8119-360d7f1a369e.png)

The above are basic features.

### Possible future features

 * Changing profile metadata (for example we can add photo, name, contacts to profile, so they can be encrypted with profile keys and uploaded to ipfs. So one could share his profile if we decide to add such functionality
 * Sharing encrypted metadata in IPFS? The meta is encrypted with a derived AES256 symmetric cipher, each item with a separate key. So you can selectively share the keys with friends
 * Two types of profiles: mainnet and testnet. So instead of having testnet.swap.online, you would just create a testnet profile
 * Profiles accessed through links. Let's say you visit our homepage https://swap.online. First it checks what profile was used last, let's say @noxonsu ... Now this profile's identifier (pubkey) 0x23847082467203947293478230497. On the visit it redirects to https://swap.online/#0x23847082467203947293478230497 - now you can just send this link to a friend, and if this profile is shared somewhere, the friend can see all your wallets and balances. Cool feature.

**Comment by vladiuz1** [comment]
почему после запуска? а как же backwards compatibility?
