### ISSUE TITLE
storageVersion parameter

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/swap.react#288]
1.  Implement version parameter in localStorage

2.  The localStorage contains important data such as private keys, client ids, etc. The Swap.Online protocol will continue changing and the format of localStorage, (for example the key format) will change with time too.  In order for swap.online to provide backward compatibility, the localStorage must contain `storageVersion` parameter. In order to 

a) Client receives backward compatibility and convenience of upgrading his storage format, or using older version of swap.online wallet and exchange.

b) We can findout what version of storage a client is using before loading protocol logic, and we may for example load the version that supports current version.

c) We can implement storage version upgrade mechanism if keys become outdated, or ask user to create a new profile that loads corresponding version and transfer all assets to the profile's wallets

3.  Frontend/localStorage

b) swap.react

4.  1 hour?

5.  Evidences.

**Comment by vladiuz1** [comment]
I suggest using https://semver.org/ for format of the version

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/pull/439
