### ISSUE TITLE
добавить фейсбук превью на главную

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#294]
https://i.imgur.com/z3Ezvla.png сейчас вообще ничего нет. нужна какая то картинка привлекающая

**Comment by indapublic** [comment]
@noxonsu Сейчас на всех страницах в `opengraph:image` выводится [логотип](url=https://wiki.swap.online/wp-content/uploads/2018/04/logo-1.png)

**Comment by indapublic** [comment]
https://wiki.swap.online/wp-content/uploads/2018/04/logo-1.png

**Comment by indapublic** [comment]
Потом надо будет подобрать хороший вариант и поменять

**Comment by indapublic** [comment]
![screen shot 2018-09-05 at 21 47 13](https://user-images.githubusercontent.com/856260/45091525-13113a00-b156-11e8-90b0-f128b3efcbc8.png)
![screen shot 2018-09-05 at 21 46 46](https://user-images.githubusercontent.com/856260/45091529-160c2a80-b156-11e8-924a-162cf9a077ed.png)

Facebook @noxonsu
