### ISSUE TITLE
Оптимизация перерисовки таблицы

### ISSUE THREAD

**Issue by Spoki4** [swaponline/swap.react#298]
Необходимо избавится от ненужных ререндеров таблицы, как пример произошло обновление в футере, оно затронуло и таблицу. таким образом страница фризится на некоторое время(про страницу History).

Как они были обнаружены:
При выполнении issue #281, при выполнение setState в Footer, происходил перерендер всей страницы. По времени это занимало от 100мс до 170мс
![image](https://user-images.githubusercontent.com/2562688/44206366-2d14b980-a162-11e8-95d5-acc4ef5eda3f.png)

Данные при этом не менялись. 
Что можно сделать:

1. Выставить нормальные key-prop а не по индексу строки.
2. Делать проверку на то что изменились только те props которые должны вызывать перерисовку
3. Сделать infinity scrollling.
4. Использовать виртуализированные таблицы, когда в реальном DOM будет только условных 10 элементов, остальные добавляются\удаляются в процессе скролла, и не будет лишних пересчетов элементов которые не видит пользователь https://github.com/bvaughn/react-virtualized

При выполнение 1 и 2 пункта уже я смог добиться вот такой картины:
![image](https://user-images.githubusercontent.com/2562688/44206426-6b11dd80-a162-11e8-8cdd-b1527c191783.png)

Если будет нужно, готов оформить PR

**Comment by nikdementev** [comment]
Делай без 4 пункта,

**Comment by Spoki4** [comment]
Думал сделать пока что только первые два, а следующие по надобности
