### ISSUE TITLE
Падает в microsoft edge

### ISSUE THREAD

**Issue by Spoki4** [swaponline/swap.react#310]
В браузере Microsoft Edge IPFS падает.
Ошибка:
```
IPFS error! Error: Не удалось завершить действие. Ошибка 80700011.
```

**Comment by noxonsu** [comment]
в микрософ едж сделать заглушку "используйте другой браузер" кроссбраузерность не нужна нам

**Comment by noxonsu** [comment]
закрыто как неважный
