### ISSUE TITLE
mobile hotfix выпадающий список направления обмена

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#313]
сейчас выглядит жутковато 

![](https://i.imgur.com/VuYD9Ik.png)

сделать любым способом более компактно, например кнопка "выбрать направление обмена" которая собсно уже показывает, ну или другим способом.

**Comment by indapublic** [comment]
![testnet swap online_ pixel 2](https://user-images.githubusercontent.com/856260/44760649-2b47ee80-ab83-11e8-80e4-f08a96d6ad8d.png)

@noxonsu Можно закрывать?
