### ISSUE TITLE
при апруве показывать ссылку на транзакцию

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#314]
так же убрать апрув со страницы балансов а показывать при нажатии на sell (если не апрувленно).  или если пытаешься выполнить чужой ордер где ты продавец токенов

**Comment by nikdementev** [comment]
e2bd8655ce30624d906bfcc95617101fdff5ffc0
ссылку сделал осталось сделать разделение sell/buy вместо trade и перенести туда кнопку approve

**Comment by nikdementev** [comment]
52b4c960d73e3619189ef887e8c205aa605759f4
