### ISSUE TITLE
Удваивание заявок с одинаковыми ключами.

### ISSUE THREAD

**Issue by momonomonoto** [swaponline/swap.react#32]
https://www.useloom.com/share/9947e7012b7641ebacfa4b71be1c2533
Переключаем с Orders на Balances и добавляется order. id одинаковые у order.

**Comment by nikdementev** [comment]
Убрал actions, reducers все работает через core, этого больше нет.

**Comment by nikdementev** [comment]
Убрал actions, reducers все работает через core, этого больше нет.

**Comment by momonomonoto** [comment]
@nikdementev сейчас если добавить новую заявку и переключиться на баланс, то  удвоение произойдет.[https://www.useloom.com/share/fbcb2f8f7ff14e9a8ef64542fca7ecf9](url)
