### ISSUE TITLE
в таблице показывается ордер хотя его уже по факту нет

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#322]
## What is working wrong?
иногда в таблице показывается ордер хотя его уже по факту нет. при нажатии на плей возникает бесконечная загрузка ![](https://i.imgur.com/YLzbg5K.png) вот что в консоли

...Describe the bug briefly...

## What should happen instead?
если ордер удален и всетаки кто то успел нажать на плей то ему должна показыватся ошибка "order does not exists anymore" 

ну и собственно если ордера нет то он не должен показыватся в ордербуке. кто то говорит что это ошибка реакта и надо смотреть что там в стейте (?)

...Describe what do you think should happen instead in this situation...

## Steps to reproduce
-разместил ордер с мобилы (хром)
-он появился в ордербуке на хроме на компе
-где то минут через 15 я попереключал направление (нажав на значек двух стрелок)
-оредр все еще был в ордербуке, я надал на плей
-получил бесконечный лоадинг

## Your system charateristics

хром, винда (и андрож) тестнет

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...

**Comment by nikdementev** [comment]
теперь будет перенаправлять на страницу оредеров
