### ISSUE TITLE
добавить екшен "resell" после свапа

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#323]
# Problem
после того как прошел своп, что делать человеку? 

# Task
предлагать заработать клиенту выставив ордер с наценкой в 5-100% 

# Purpose

# Area

![](https://i.imgur.com/uCcZGKX.png)

в этом месте после сенкю сделать кнопку ressell with 20% (выпадающий список можно накинуть 5-100%) profit при нажатии открывается окно add order где поля заполнены таким образом, что стоимость актива выше в пользу клиента

# Estimate time of implementation
2 hours

# Additional data

**Comment by nikdementev** [comment]
Кто его оредер купит ?

**Comment by noxonsu** [comment]
купят, если все дешевые выберут
