### ISSUE TITLE
на андроиде не получается перезагрузить страницу свапа, и почемуто каждый раз свап добавляется в историю

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#328]

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/84d6ee538f6461a87541a9c2a57def8263876e77#diff-9daa8cd3373f7e6fc97fc33a4a1fd082L46

**Comment by nikdementev** [comment]
b743632500cc3102893491377f740f33bffddeaf
