### ISSUE TITLE
Неверный способ ввода суммы

### ISSUE THREAD

**Issue by Spoki4** [swaponline/swap.react#333]
## What is working wrong?

Можно поставить более одной `.` в поле ввода суммы

## What should happen instead?

После первого ввода точки, следующая не должна ставится.

## Steps to reproduce
Открыть модалку создания офера и ввести в любое поле `123.123.123`, на скриншоте показал.

## Your system charateristics

- Browser: Vivaldi 1.15.1147.64 (Stable channel) (32 бит) Chrome/65.0.3325.183
- OS: Windows 10
- Mainnet or Testnet: Testnet

## Does this affect atomic swap flow?

- [ ] yes
- [X] no

## Are real funds at risk?

- [ ] yes
- [X] no

## Screenshots

![image](https://user-images.githubusercontent.com/2562688/44433374-aa9b5800-a5ae-11e8-904f-037878fef897.png)

## Additional info
Всё сказано выше ^

**Comment by Spoki4** [comment]
Можно заблокировать кнопку `NEXT` при `NaN` в любом из полей.
Либо, убрать возможность ставить больше чем одной точки.

**Comment by noxonsu** [comment]
на самом деле эту форму нужно еще много как улучшать. например иногда если стереть поле то остальные тоже стираются и тп. ок пока исправь точки
