### ISSUE TITLE
при нажатии download keys на айфоне файл не скачивается а открываетя прямо во владке

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#334]
файл долджен скаичватся, типа ключи сохранились. а на айфоне они открываются приходится изощраятся чтоб сскопировать в заметки и тп

**Comment by Spoki4** [comment]
@noxonsu у меня нет iphone, тестить не смогу. Но можно попробовать сделать через эту [либу](https://github.com/eligrey/FileSaver.js). У iOS есть косяки на разных версиях с сохранением файлов.
Для изображений раньше использовал этот сниппет кода. Но работает вроде не для всех типов файлов
```js
if (browser.os === 'iOS') {
      const link = document.createElement('a')

      link.href = 'url'
      link.setAttribute('download', 'file.jpeg')
      const event = document.createEvent('MouseEvents')

      event.initEvent('click', false, true)
      link.dispatchEvent(event)
}
```

**Comment by noxonsu** [comment]
вставь, попробуем

**Comment by caffeinum** [comment]
на айфоне нельзя скачивать файлы, нужно просто написать "нажмите скачать, а потом поделиться"

**Comment by caffeinum** [comment]
проверил либу FileSaver.js, она тоже просто открывает файл.
Это нормально, надо просто объяснить юзеру, что с этим делать

**Comment by Spoki4** [comment]
@caffeinum а кусок кода пробовал?

**Comment by caffeinum** [comment]
@Spoki4 не пробовал, но там по сути ссылка `<a download="file.jpeg"></a>`, так?

**Comment by caffeinum** [comment]
https://caniuse.com/#search=download

**Comment by noxonsu** [comment]
при попытке скачать на айфоне писать.

**Comment by Pasha8914** [comment]
#1075
