### ISSUE TITLE
форма создания ордера: я хочу продать 100 токенов за 1 биткоин. ввожу в поле sell 100 токенов, в поле buy 1 биткоин - все ломается

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#335]
или например я хочу продать 100 токенов за 1 биткоин. ввожу в поле sell 100 токенов, в поле buy 1 биткоин - все ломается. 

никита говорит, что это не баг. конечно не баг, задумано, что ты должен знать курс и обратный курс. но можно сделать более юзабельно, чтоб то поле которое дольше всего не обновлялось было зависимым от того, которые ввели последним или предпоследним

**Comment by Spoki4** [comment]
Предлагаю сделать так:
Первое поле пустое.
Ты пишешь во второе, первое обновляется в зависимости от курса. При этом первое блокируется для ввода.
Если хочешь указать в первое поле вручную, то удаляешь из второго и первое снова разблокируется. И ты снова можешь выбрать в какое поле писать

**Comment by nikdementev** [comment]
надо сделать что бы все не активный поля подстраивались под одно активное, как я понял Саша так хочет

**Comment by Spoki4** [comment]
То что я предложил мне кажется будет более понятно пользователю

**Comment by caffeinum** [comment]
Согласен, что если в поле введены данные пользователем, их больше никогда менять нельзя.

Вообще, можно сделать по-другому – выбирать, создаешь лимитный ордер или рыночный. В первом случае вообще никаких подсказок нет и ты сам вводишь все поля, во втором случае –  блокируется курс, и поменять его нельзя

**Comment by meati** [comment]
В последнем своем состоянии, проблема не воспроизводится

**Comment by noxonsu** [comment]
https://drive.google.com/file/d/1uh4b1SaktO55KvEfpgeNEbgEqXka0LS5/view не вижу

**Comment by Spoki4** [comment]
@noxonsu тут можно поставить галочку, `выставить значения вручную`. Тогда будет автоматически считаться только поле exchange rate
