### ISSUE TITLE
добавить граватар овнера в список ордеров (пока просто для теста)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#346]
# Problem
у меня могут быть любимые менялы, по граватару я узнаю, что это тот самый, ну и вообще более человечно будет. не факт что

# Task
![](https://i.imgur.com/rPbV8XQ.png) 
в этих местах должны быть граватары создателя (ну и следовательно вверху мой собсвтенный)

# Purpose
более приятный для глаза ux

# Area
в списке ордеров

# Estimate time of implementation
2 часа

# Additional data

**Comment by noxonsu** [comment]
граватар берется из ipfs peer id

**Comment by indapublic** [comment]
@noxonsu Идентикон (который уже используется в проекте) устроит?
> граватар берется из ipfs peer id
Что использовать для аватара залогиненного пользователя?

**Comment by noxonsu** [comment]
да конечно

**Comment by indapublic** [comment]
@noxonsu 

Что использовать для аватара залогиненного пользователя?

**Comment by noxonsu** [comment]
закрываю но либа граватаров дно
