### ISSUE TITLE
зависло на 5ом шаге свапа из за того что очень мало эфира на балнсе

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#349]
на пятом шаге когдя алиса пытается забрать биткоин из коробки боба но не хватает эфира на газ. в консоли ошибка от веб3 Error: Returned error: insufficient funds for gas * price + value 

необходимо показать ее пользователю и попросить переветси на баланс 0.002 эфира еще и перезагрузить страницу

**Comment by noxonsu** [comment]
более просто, не давать запустить свап если у юзера на балансе мнеьше чем сумма свапа +0.02 ETH

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/14676c3a517204a51a3aae5a3ed71d991cfea4d6
