### ISSUE TITLE
FAIL! Secret: null при попытке забрать биток из контейнера алисы

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#350]
## What is working wrong?
боб с андроида не может забрать биткоин, алиса эфир забрала.. юзеру показывается бесконечная загрузка на 6ом шаге

## What should happen instead?
свап должен нормально закончится. если значение секрета null возможно предложить юзеру самому ввести

## Steps to reproduce
1. создал ордер на андроиде о продаже  эфира за биткоин
2. очень долгождал, ордер висел онлайн часа два
3. принял его с компа
4. во время свапа у алисы не было эфира, пришлось докидывать перезагружать страницу
5. после докидывания мелочи на газ. транзакция на забирание эфира из коробки прошла успешно
6. на андроиде пошел последний шаг который не выполнился

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [x] yes
- [ ] no

## Are real funds at risk?

- [x] yes
- [ ] no

## Screenshots
![](https://i.imgur.com/LLmfHan.png) непонятно почему, но секрет не вытащился. нужно продублировать фунционал вытаскивания секрета или как то устранить это

## Additional info

инфа о свапе
`{
    "step": 7,
    "signTransactionHash": null,
    "isSignFetching": false,
    "isParticipantSigned": true,
    "btcScriptCreatingTransactionHash": "00213442230cbcfe46e136abc0672ef2d81b743f8a6743d87f794779b9e2b6cb",
    "ethSwapCreationTransactionHash": "0x982c72ca1992cd1ca04fead0673cd50c083d3db0052b4bd08e72f6d9c4935be5",
    "secretHash": "715c5734a94d0c8ad356fee05f7189cbe4ee87f4",
    "btcScriptValues": {
        "secretHash": "715c5734a94d0c8ad356fee05f7189cbe4ee87f4",
        "ownerPublicKey": "033587f9e0cbe1d5ffa28efd7f6d3351da1fc1ac4655f2c23006911b18f3f142ea",
        "recipientPublicKey": "0218ed14397d6fd9e68dfaf548054db14308badfbbe7f4a12ae3d48792dfc963fe",
        "lockTime": 1535009721
    },
    "btcScriptVerified": false,
    "isBalanceFetching": false,
    "isBalanceEnough": true,
    "balance": 0.00467544,
    "isEthContractFunded": true,
    "ethSwapWithdrawTransactionHash": "0xc71487ab06d3a631160459c98fce2a99a7918469b70b61bdd932f7122df6051c",
    "isEthWithdrawn": true,
    "refundTransactionHash": null,
    "isRefunded": false,
    "refundTxHex": null,
    "isFinished": false,
    "secret": "04f391385cb9448afae0f22d540c1a2170d3fb5e43b6e1cfc31c33c009bcfcd6",
    "isBtcScriptFunded": true
}`

**Comment by caffeinum** [comment]
Странно, секрет-то есть. Обычно такое возникает, когда секрета нет, тогда и перезагрузка не помогает.

Если перезагрузить страницу, не сработало?

**Comment by noxonsu** [comment]
Конечно пробовал - не сработало

**Comment by noxonsu** [comment]
Это инфа о свапе от Алисы

**Comment by noxonsu** [comment]
как минимум нужно написать как вручную завершить свап на вики. Никита сегодня как то сделал, нужно написать иинструкцию на инглише и выложить на вики, а ссылку в 5ый шаг воткнуть .

**Comment by noxonsu** [comment]
ссылку на комит, в другом репо тоже можно

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.core/pull/101
