### ISSUE TITLE
window.onerror показывать красным снизу окна

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#351]
я думаю, если красные ерроры из консоли выводить кудато пользователю то будет проще отлавливать ошибки с которыми они столкнутся, а у нас не будет возможности их отладить. а так они сразу будут пистаь "свап завис, а в углу красным написано error gas + value..." и сразу станет понятно, что там случилось

**Comment by nikdementev** [comment]
@Nevermind2121

**Comment by noxonsu** [comment]
где комиты, где смотреть то
