### ISSUE TITLE
человекопонятные урл вида swap.online/bitcoin

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#352]
1. при добавлении новой крипты она появляется по адресу swap.online/cryptoname 
2. без тикера а полное имя.
3. на главной странице кроме send есть кнопка swap которая и ведет на страницу п.1
4. на странице swap.online/cryptoname есть тайтл, маленькое описание крипты, ниже идет список вида

change cryptoname to bitcoin > https://swap.online/cryptoname-to-bitcoin
change bitcoin to cryptoname > > https://swap.online/bitcoin-to-cryptoname

**Comment by nikdementev** [comment]
@Nevermind2121

**Comment by noxonsu** [comment]
не до конца сделано на главной при клике на swap нужно переходить на https://testnet.swap.online/bitcoin а сейчас преходит на старый https://testnet.swap.online/btc (короткое название)

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/f39d2f1914a1aa0f2643d5c860f20f63b9a03213

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/54e5fb83d1c12b6e5bb9233bfd32d933fa8afad6
