### ISSUE TITLE
proofread https://wiki.swap.online/about-swap-online/

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/swap.react#353]
# Problem

English sucks

# Task

Proofread the page: https://wiki.swap.online/about-swap-online/

# Purpose

It solved the problem that our texts look terrible

# Area

frontend / wiki

# Estimate time of implementation
1 day

# Additional data

https://wiki.swap.online/about-swap-online/

**Comment by noxonsu** [comment]
Issue moved to [swaponline/Office #395](https://github.com/swaponline/Office/issues/395) via [**ZenHub**](https://www.zenhub.com/)
