### ISSUE TITLE
разобратся и добавить превьюхив в соц сетях

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#359]
![](https://i.imgur.com/7LoTBl2.png) 

пока белый экран при отправке в линкедине, проверить в остальных

**Comment by indapublic** [comment]
@noxonsu Есть файл с логотипом в PSD?

**Comment by noxonsu** [comment]
в psd нету. https://drive.google.com/open?id=1CoYvgGWOgiBEL7tTpls56Utxf5EYkWnL

**Comment by indapublic** [comment]
![screen shot 2018-09-05 at 21 51 56](https://user-images.githubusercontent.com/856260/45091493-f8d75c00-b155-11e8-90fb-812a55ce5f00.png)
![screen shot 2018-09-05 at 21 50 00](https://user-images.githubusercontent.com/856260/45091505-01c82d80-b156-11e8-9742-186e9cffed55.png)

Linkedin @noxonsu
