### ISSUE TITLE
Неверно считается exchange rate при смене валюты на противоположную

### ISSUE THREAD

**Issue by Spoki4** [swaponline/swap.react#361]
## What is working wrong?

Неверно считается exchange rate при смене валюты.

## Steps to reproduce

Ввести `1` в первое поле где ETH (скрин 1)
Выбрать токен NOXON в первом поле (скрин 2)
Удалить `1` и ввести заного (скрин 3)

## Your system charateristics

- Browser: Vivaldi 1.15.1147.64 (Stable channel) (32 бит) Chrome/65.0.3325.183
- OS: Windows 10
- Mainnet or Testnet: Testnet

## Does this affect atomic swap flow?

- [X] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [X] no

### Скрин 1
![image](https://user-images.githubusercontent.com/2562688/44559037-123cd900-a750-11e8-8f50-77ec7bf83ced.png)
### Скрин 2
![image](https://user-images.githubusercontent.com/2562688/44559049-1e289b00-a750-11e8-8838-207dbaa20a4c.png)
### Скрин 3
![image](https://user-images.githubusercontent.com/2562688/44559074-43b5a480-a750-11e8-961a-52d61c772997.png)

**Comment by Spoki4** [comment]
Происходит это из-за асинхронной функции `getExchangeRate`. И на следующей строке запрашивается из state exchangeRate, который на деле еще не обновился.

**Comment by nikdementev** [comment]
@Nevermind2121

**Comment by meati** [comment]
Уже не воспроизводится

**Comment by Spoki4** [comment]
Исправил @Nevermind2121 в #377
