### ISSUE TITLE
Алиса начинает обмен без подтверждения от Боба

### ISSUE THREAD

**Issue by shendel** [swaponline/swap.react#363]
![image](https://user-images.githubusercontent.com/1880211/44559791-f5ef6b00-a754-11e8-9fb6-0e06ebfa19ce.png)
![image](https://user-images.githubusercontent.com/1880211/44559801-00116980-a755-11e8-8b09-fa077b6e4bb5.png)
Как то так.
1. Боб создал ордер
2. Алиса нажимает "Начать сделку"
3. Алиса попадает на страницу обмена
4. У Боба появляется уведомление о входящем запросе
5. Боб нажимает "Отмена"
6....
7. Алиса долго смотрит в монитор

**Comment by nikdementev** [comment]
@Nevermind2121
