### ISSUE TITLE
"Such error"???

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/swap.react#367]
## What is working wrong?

Text on error message sucks

## What should happen instead?

SHould have text in english

## Steps to reproduce

go to home page and wait for this error to apper

## Your system charateristics
doesnt matter

## Does this affect atomic swap flow?

- [ ] yes
- [*] no

## Are real funds at risk?

- [ ] yes
- [*] no

## Screenshots

![screenshot_2018-08-24 swap online - cryptocurrency wallet with atomic swap exchange](https://user-images.githubusercontent.com/22708849/44582103-0f220700-a7a9-11e8-9504-49cba34b9784.png)

## Additional info

This should say (subject to proofreading):

------

#### Multiple tabs error:
Swap.Online can not be open in multiple tabs, please close this tab and switch to the other tab where you have it open.

------

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/issues/326
