### ISSUE TITLE
Expected property "1" of type o, got Number -715000

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#37]
```
Unhandled promise rejection f
{message: "Expected property "1" of type o, got Number -715000", __label: undefined, __property: 1, __type: ƒ, __value: -715000, …}
message: "Expected property "1" of type o, got Number -715000"
```

![image](https://user-images.githubusercontent.com/1909384/41045340-e6eb55ba-69b0-11e8-8252-4cb6b89bf949.png)

Возможно, связано с swaponline/swap.core#6

Из браузера совершал обмен BTC -> ETH, баланс BTC больше 0.007 BTC, но меньше 7 BTC.

![image](https://user-images.githubusercontent.com/1909384/41045555-410a30c0-69b1-11e8-89f9-dffdf1292e77.png)

**Comment by noxonsu** [comment]
ошибка повторяется http://joxi.ru/p27bJ37CoWbvGm

**Comment by nikdementev** [comment]
@noxonsu @caffeinum это потому что он создает обратный свап и просит баланс другой валюты. 
сейчас все свапы проходят но они все наоборот ((

**Comment by nikdementev** [comment]
@noxonsu @caffeinum 
![image](https://user-images.githubusercontent.com/17093843/41146286-30440fc2-6b46-11e8-965b-2c42519e0242.png)
Почему то в flow кладется не тот адрес, соответственно проверяется не тот баланс и ошибка.
