### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by nikdementev** [swaponline/swap.react#372]
1. - [ ] Confirm - сделать модальным окном
2. - [x] ButtonsIsRow - удалить из за ненадобности
3. - [x] ReloadBtn и RemoveBtn сделать как Flip
4. - [x] TimerButton декомпозировать 
5. - [x] Filter перенести в History
6. - [x] Feed перенести в Listing
7. - [x]  Line сделать отдельным компонентом (убрать из компонента Info)
8. - [x] Links, Social генерировать из config
9. - [ ] Input декомпозировать
10. - [ ] Menu перенести в конфиг из reducers
11. - [ ] AddOffer декомпозировать
12. - [ ] UserTooltip декомпозировать, и передавать туда мои оредера фильтрованные по предложению
13. - [ ] В модальных окнах убрать scroll у body
14. - [ ] Layout сделать адаптивным
15. - [ ] Modal упростить и сделать через portal
16. - [ ] Approve удалить 
17. - [ ] Разделение логики в AddOffer
18. - [ ] Вынести в конфиг все фразы ошибок
19. - [ ] Вынести в конфиг min, max amount для каждой валюты
20. - [ ] PageHeadLine упростить
21. - [ ] SearchSwap декомпозировать 
22. - [ ] Seo данные генерация из конфига
23. - [ ] Упростить Table
24. - [ ] CloseIcon упростить
25. - [ ] DropDawn упростить и декомпозировать
26. - [x] Core отделить логику от React
27. - [ ] FilterHistory сделать селектором
28. - [ ] LinkTransaction автогенерация
29. - [ ] Row рефактор декомпозиция
30. - [ ] Wallet декомпозировать упростить
31. - [ ] IndexDB вместо localStorage 
32. - [ ] Вынести всю логику взаимодействия с redux из компонентов
33. - [ ] Четко разделить компоненты на UI
34. - [ ] Перенести логику компонентов в Containers
35. - [ ] Покрыть тестами
36. - [ ] Унифицировать вызов API через Circuit Breaker
37. - [ ] Разделить валюты на для кошелька и для свапов
38. - [x] оставить только нужные шрифты в папке client/fonts 
39. - [x] подключить IPFS и ipfs-pubsub-room из пакета npm
40. - [x] подключить normalize css из пакета npm
41. - [x] config web3, blockchains, erc20, api, link, ipfs, все в своих отдельных папках (mainnet, testnet)
42. - [x] config default http, publicPath, time, остальное убрать,
43. - [ ] tips удалить из конфига, перенести в компоненты

**Comment by Spoki4** [comment]
Можно сделать чтобы в компоненте Href проверялся домен и если он != текущему, то ставиться "noopener noreferrer"

**Comment by noxonsu** [comment]
занятся вам нечем я смотрю

**Comment by nikdementev** [comment]
- [ ] Оставить только нужные шрифты в папке client/fonts
