### ISSUE TITLE
Fix security issues related to loading .js outside of swap.online

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/swap.react#373]
# Problem

While loading page, libraries are downloaded from outside domain names. This is not good, who can trust domains such as jquery.com? Who runs it? This may leave a huge security whole.

example:

![never-do-this 6](https://user-images.githubusercontent.com/22708849/44646162-cf466400-a9e2-11e8-8cb5-80e3684e74d3.png)

Who knows who has access to this js....

**WE SHOULD NEVER LOAD JS OR SVG OR ANYTHING FROM DOMAINS OTHER THAN swap.online**

ALSO remove yandex trackers, its .ru - people don't trust russians, no need to remind them its a .ru project when not needed

# Task

Always reference local copies of 

* fonts
* js
* css
* etc

# Purpose

(What this feature is intended to do or solve?)

# Area

frontend libraries

# Estimate time of implementation

30 mins

# Additional data

Discuss how to solve the problem of google tracking.

**Comment by noxonsu** [comment]
можно ставить те, где прописан integrity, остальные перенести на наш сайт, посмотреть работает ли все

**Comment by BootWP** [comment]
Я сделал загрузку jquery.js, bootstrap.js, 
и два скрипта от кикофлабса
kol_any_form.js и 206389.js
после наполнения формы переадресация работает у меня на https://swap-thank-you.kickoffpages.com
а далее я не знаю за что отвечает kickoffpages.com, проверяйте у себя.

**Comment by noxonsu** [comment]
geoip тоже

**Comment by BootWP** [comment]
Готово!
У меня закапывает город, проверяйте у себя это поле если заполняется
http://joxi.ru/8AnB5wQFjYN4yA
https://swap.online/?utm_term=term
