### ISSUE TITLE
при попытке переключить валюту в консоли еерров expected propery "SellCurrency" of type isCoinname 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#385]
![](https://i.imgur.com/qxNOIeZ.png) возможно бот шлет не правильные данные, а фронт их подхватывает и не можете переварить

**Comment by nikdementev** [comment]
все так как ты и написал это type force ругается

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/44776383-a65bd580-ab80-11e8-8fef-748509f4d55f.png)

**Comment by noxonsu** [comment]
ну и что, как исправить то? нужно функцию обновить таким образом, что если неизвестный коиннейм то поочереди пытается подставить любой из этих паттернов, после чего если ничего не найдено то уже ексцепшн бросать

**Comment by nikdementev** [comment]
нет остается как есть смысл тайпфорса тогда ? @caffeinum Что думаешь

**Comment by noxonsu** [comment]
остается, он нужен как и вообще типизация в программировании, в данном слаяе тайповрс нашел ошибку, что у нас не все адреса проверяются на валидность. нужно дописать алгоритм так, чтоб учитывался не название а тип коина. если ерс20 то одно, если биткоин то другое  и тп

**Comment by caffeinum** [comment]
@nikdementev у тебя на скриншоте проверка адреса же, а не sellCurrency? sellCurrency может быть только строкой, а адрес в ордерах не шлется

**Comment by noxonsu** [comment]
ну если оптяь будет невалидный ордер будет такая история
