### ISSUE TITLE
Error: Uncaught Error: already piped снизу экрана

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#387]
появляется ошибка Error: Uncaught Error: already piped , нужно ее как то ловить, и если она что то ломает, то релоадить страницу

![](https://i.imgur.com/ljW1dP4.png)

**Comment by nikdementev** [comment]
она не влияет ни на что

**Comment by nikdementev** [comment]
поставил версию 0.31.7 там не должно такого быть
