### ISSUE TITLE
orderbook: ордера приходят в консоль но не выводятся в интерфейсе

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#39]
swapApp.services.orders ордера есть, а в ордербуке не отображаются (но при этом если создавать новые то новые появляются, а старые нет)

**Comment by noxonsu** [comment]
баг динозавр возвращен к жизни, пруфы на видео 

## What is working wrong?

Ордера не отображаются хотя приходят в консоль через ipfs

## What should happen instead?

ордера должны отображатся

## Steps to reproduce

1. у нас в офисе стоит комп там давно висят ордера, уже месяц
2. с какогото времени эти ордера перестали отображатся на свап онлайне в остальных бразуерах

## Your system charateristics

- Browser: хром
- OS: винда
- Mainnet or Testnet: менйнет

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots


записал видос https://drive.google.com/file/d/1Z4qdpOxpW0_LC3pWi1-bj15c9RoZXsGh/view?usp=sharing


## Additional info

**Comment by sdwas** [comment]
Подтверждаю
![screenshot_20181209_190003](https://user-images.githubusercontent.com/43396375/49695445-f66a1f80-fbe6-11e8-8fcb-b11c69837006.png)

**Comment by indapublic** [comment]
@noxonsu  При выводе ордеров отсеиваются элементы с признаком `isProcessing = true`

**Comment by indapublic** [comment]
```
const filterMyOrders = (orders, peer) => orders
  .filter(order => order.owner.peer === peer)

const filterOrders = (orders, filter) => orders
  .filter(order => order.isProcessing !== true)
  .filter(order => Pair.check(order, filter))
  .sort((a, b) => Pair.compareOrders(b, a))
```
