### ISSUE TITLE
при нажатии на "плей" напротив ордера запрос вроде как ушел, но интерфйс в том месте где нажали на плей не отреогировал смотри

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#391]
смотри видео первые секунды https://drive.google.com/file/d/1kLybdKk-qU0ivg_5VznJTYzbvbJoq7cc/view

**Comment by noxonsu** [comment]
баг пока что не проявляется, можно закрывать если исправить https://github.com/swaponline/swap.react/issues/385

**Comment by nikdementev** [comment]
ну Игорь сделал обработчик callback тебя редиректит только тогда когда второй человек точно начнет свап
