### ISSUE TITLE
свап завис на 5. Waiting BTC Owner adds Secret Key to ETH Contact   хотя тот уже положил

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#393]
![](https://i.imgur.com/ItR9lsf.png)

**Comment by noxonsu** [comment]
ну с кем то, видимо с ботом. так или иначе проблема в реакте, потому что вторая сторона не прислала скерет, например она моет это сделать умешленно. нужно продублировтаь функционал поулчения секрета как я и сказал

**Comment by noxonsu** [comment]
как я уже сказал, нельзя довреять второй стороне, по возможности чекать через блокчейн

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.core/pull/101
