### ISSUE TITLE
через share оредр не подсвечивается, ъотя есть в списке

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#394]
https://testnet.swap.onlen/exchange/eth-btc/QmUcQDmDpM7PtCQPg4Bqv7yiSGLkKhL8frMFuTpBmTPQeg-1535510406595

например  этот на 0.123 ETH

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/883fd1aca64b6a0d49fb312d75b78c28672ab8b1

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/44779393-16218e80-ab88-11e8-8b8f-26970f731627.png)
