### ISSUE TITLE
проверка билда 30.08

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#397]
**базовый тест (до 10 минут)**
- [x] 1. зашел на тестнет, создал ордер (из хрома например)
- [x] 1.1 увидел сразу собственный ордер в спсике своих ордеров 
- [x] 2.0. с другого браузера этот ордер увиедел перейдя по кнопке share
- [x] 2.1. напрвления "ю бай" и "ю селл" в обоих браузерах показываются нормально а не перепутано
- [x] 3. куллер не шумит 
- [x] 4. еслли денег достаточно то доступен "плей"
- [x] 5. нажали "плей" (с браузера яндекс), пошел свап
- [x] 5.1. в течении нескольких секунд у маркетмейкера появилось уведомление, что кто то хочет начать свап
- [x] 6.1. нажали крестик "отменить свап" отмена сработала у обоих корректно
- [x] 6.2 маркеттейкер снова попробовал начать свап, уведомление снова пришло маркетмейкеру
- [x] 7. подождали сколько то секунд, начался свап корректно
- [x] 8. все шаги свапа выполнились

**тест с мобилой (до 10 минут)**
- [ ] 9.1 в андроиде создается оредр на продажу 1 свап за 0.00015 btc 
- [ ] 9.2 в браузере на компе он виден сразу
- [ ] 9.3 клиент  вбраузере нажимает плей
- [ ] 9.4 сразу приходит уведолмнеие на андроид 
- [ ] 9.5 ждем пока свап закончится
- [ ] 9.6 свап закончисля

**тест маркетмейкера (до 5ти минут)**
- [ ] 10.1 в браузере создается ордер на продажу 1 свап за 0.00015 BTC
- [ ] 10.2 в браузере создается ордер на покупку 1 свап за 0.0001 BTC (дешевле чем на продажу)
- [ ] с browserstack заходит человек и выполняет оредр 10.1
- [ ] одновременно из андроида пытаемся выполнить ордер 10.2
- [ ] маркетмейкер ничего не делает по идее должен выполнится ордер 10.1, а 10.2 отказатся

**Comment by nikdementev** [comment]
вообщем с новым дизайном на мобилки не показывается когда приходит уведомление на начало оредера с телефона меняться нельзя на данный момент

**Comment by noxonsu** [comment]
результатом прохода тестов должны быть ишью https://github.com/swaponline/swap.react/issues/411
