### ISSUE TITLE
возможность самому убирать добавлять коины на главную (из тех что в системе)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#403]
Noxon ⚡️, [31.08.18 01:27]
на главной при наведении на любой из альткоинов должен появлятся крестик, при наведении на крестик подсказка hide при нажатии крипта скрывается

Noxon ⚡️, [31.08.18 01:27]
появляется обратно если зайти на swap.online/cryptoname

Антон Билык, [31.08.18 01:27]
а как пользователь зайдет туда если у него нет ссылки с главной?

Noxon ⚡️, [31.08.18 01:28]
гденить сделаем страницу со всеми коинами

Noxon ⚡️, [31.08.18 01:28]
снизу где скачать ключи сделай кнопку all coins

Антон Билык, [31.08.18 01:29]
надо наверное прям под скписком твоих кошельков так логичнее

Антон Билык, [31.08.18 01:29]
ну вобщем-то это там и есть примерно

Noxon ⚡️, [31.08.18 01:30]
ну попробуй в общем

проблема в том что у нас может быть сотня крипт и каждый день куча добавляется, нужен какойнить менеджмент

связано с https://github.com/swaponline/swap.react/issues/402

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/pull/409
