### ISSUE TITLE
To list Synexcoin2.0 token

### ISSUE THREAD

**Issue by DariaPurtova** [swaponline/swap.react#416]
1.  Job: To list Synexcoin2.0 token on swap wallet

2.  Purpose. 
a) Clients benefits: to exchange tokens to BTC, USDT

b) Our benefits: mutual PR, possibly new client for swap button 

4.  Estimate time of implementation this feature - 1 day

**Comment by DariaPurtova** [comment]
Website: https://synexcoin.com
Name: Synexcoin2.0
Ticker: SYC2
Contract:
0x49feeF410293261c04F1d14600Ba427F8eED8723
Decimal: 2
The icon you can be used from the website:
https://static.wixstatic.com/media/cf0fa3_6e653e4d07f8405695a701f5cacae5f9~mv2.png/v1/fill/w_153,h_131,al_c,lg_1/cf0fa3_6e653e4d07f8405695a701f5cacae5f9~mv2.png

**Comment by noxonsu** [comment]
@DariaPurtova  не забывай асайнить людей 

![](https://i.imgur.com/CXfNJNF.png)

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/eeebb2882ce1790b5766e04d2f514ba1a6ab93f0

**Comment by noxonsu** [comment]
ситуация. у меня есть биток я хочу выставить ордер на покупку SYC https://drive.google.com/file/d/14BfBScVLh70zOCq45kCZyZHtucvzkgWW/view ордер тупо не появляется в оредрбуке

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/aaf2a60dc3521d62dd304b45ea4982ddfbcb742c
