### ISSUE TITLE
qr коды на отправку и получение крипты

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#421]
пример
https://i.imgur.com/jS9NDrB.png

**Comment by indapublic** [comment]
@noxonsu Задача не совсем понятна.

**Comment by noxonsu** [comment]
суда добавить scan qr https://i.imgur.com/aFpXJ7C.png

**Comment by noxonsu** [comment]
сюда добавить значек qr кода https://i.imgur.com/svBL2Mj.png при клике открывается qr код с адресом

**Comment by vladiuz1** [comment]
будет немного пестровато, я бы по другому сделал. всего одна кнопка "share" вместо двух по краям, а по нажатию выскакивают опции.. смотри тут

![swap-suggested-sharing-button](https://user-images.githubusercontent.com/22708849/45389392-77d00700-b624-11e8-8825-692b37217e70.gif)
