### ISSUE TITLE
Настроить сайт Swap.Online, чтобы он отправлял события в push.datalayer

### ISSUE THREAD

**Issue by chromebookman** [swaponline/swap.react#43]
Проблема: разработчики выкатывают апдейты на сайте, добавляя новые функции / разделы, а на них никак не настроена аналитика, трекание ивентов. Более того, из-за защиты Cloudfare я, как маркетолог, не могу настроить их самостоятельно через GTM, потому что Selector CSS каждый раз разный у каждого пользователя.

Решение: Создать табличку со всеми ивентами, и передавать их разработчикам, чтобы они делали нужные пуши в Data Layer через JavaScript, в зависимости от действий пользователя.

Таким образом, я как маркетолог, смогу подхватывать эти пуши в GTM и дальше их распространять по системам аналитики, Yandex Metrica и Google Analytics

Собственно, такая табличка готова, надо только её внедрить:
https://docs.google.com/spreadsheets/d/1l-O0IujhokEseMTwmT49DgvNPZrzY25TPRYISKmrbK0/edit?usp=sharing

P.S. Сейчас работают только 4 верхних строчки в таблице (напротив них написан статус Работает), напротив всех остальных статус Установлен, это значит, что я настроил GTM на прием этих событий, но осталось дело за малым — настроить JS код сайта так, чтобы он отправлял эти события.

**Comment by chromebookman** [comment]
Я не понимаю, почему эта задача закрыта, если она еще не сделана?
@nikdementev @rmixi

**Comment by chromebookman** [comment]
Коллеги, дайте контакты тестировщика, я поставлю ему задачу протестить все эти события

**Comment by chromebookman** [comment]
@nikdementev Почему опять задача закрыта, если на https://swap.online/ это до сих пор не работает?
Сейчас работает только на testnet, но это кастрированная версия

**Comment by noxonsu** [comment]
контакты тестировщика @apelsin555

**Comment by noxonsu** [comment]
так же нужны евенты на то что чел сохранил ключи и отдельно что подвтердил их сохарнение и тп.

**Comment by chromebookman** [comment]
@noxonsu Я уже писал тебе, чтобы ты в бизнес-процесс внедрил последний пункт "аналитика". Прежде чем выкатывать новые фичи, экраны, блоки, нужно показывать их мне, чтобы я придумывал, на что еще можно повесить аналитику, и настраивал эти события в Google Tag Manager + Google Analytics + Яндекс.Метрике. Сейчас на сайте все меняется хаотично, я не в курсе что происходит, захожу и вижу новые блоки. Не понятна логика, воронка обмена, она постоянно меняется. Поэтому если ты хочешь, чтобы я за этим следил, внедри это в бизнес-процесс. Так хаотично это херня. Постоянно все будет слетать.
