### ISSUE TITLE
транзакция свапа майнится 4 часа, что делать?

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#434]
сейчас опять свапы не проходят, при добавлении газа страница толи релодится толи что "она перезагружает шаги как то не правильно" никита говорит

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/45101717-d7b24380-b134-11e8-9cf4-e9855fa17221.png)
добавил провел свап
