### ISSUE TITLE
wrong direction of exchange of tokens

### ISSUE THREAD

**Issue by AlexKam41** [swaponline/swap.react#444]
## What is working wrong?

wrong direction of exchange of tokens

## What should happen instead?

The order to sell the tokens has changed to buy

## Steps to reproduce

transferred tokens into the wallet
created a warrant for their sale
placed an order
the platform itself changed the order to buy tokens

## Your system charateristics

- Browser: Chrome
- OS: Macos
- Mainnet or Testnet: Mainnet

## Does this affect atomic swap flow?

- [ x] yes

## Are real funds at risk?

- [x] yes

## Screenshots

![image](https://user-images.githubusercontent.com/35370697/45231422-06404200-b320-11e8-8f11-57adbe77bad5.png)
![image](https://user-images.githubusercontent.com/35370697/45231431-0e987d00-b320-11e8-9d9d-0354ebd72e8b.png)

**Comment by AlexKam41** [comment]
клиент

**Comment by AlexKam41** [comment]
Объясню по русски. Я создаю ордер на продажу swap токенов! А он заносится в стакан как на покупку. Я в состоянии отличить продажу и покупку и создать правильный ордер, но система регистрирует его неправильно.

**Comment by nikdementev** [comment]
я создал
![image](https://user-images.githubusercontent.com/17093843/45253754-601f2700-b375-11e8-8ef4-755f6c2368a3.png)
а так его видят другие люди
![image](https://user-images.githubusercontent.com/17093843/45253758-657c7180-b375-11e8-8d9a-344bdff84313.png)

**Comment by AlexKam41** [comment]
рекомендую проверить в другом браузере как он отображается в общем стакане

**Comment by nikdementev** [comment]
@AlexKam41 это и был другой браузер

**Comment by AlexKam41** [comment]
Ордеров на продажу swap я не вижу только на покупку и те не исполняются. я сейчас вобще создать не могу ордер. Не из кошелька, не из обменника.

**Comment by caffeinum** [comment]
@AlexKam41 В стакане сейчас только ордера на __продажу__ свап токенов. Ты создал такой же ордер. Ордеров на покупку нет, поэтому он не исполнится сам собой.

Сайт работает в точности так, как и нужно. Можешь предложить, как написать, чтоб было понятнее.

**Comment by nikdementev** [comment]
@AlexKam41 
![image](https://user-images.githubusercontent.com/17093843/45254170-8f856200-b37c-11e8-8c4e-5ad161d80c54.png)

**Comment by caffeinum** [comment]
@AlexKam41 

Я не знаю, почему ордер не создается. Создай, пожалуйста, другой ишшу и приложи скриншоты, балансы, вывод консоли.
