### ISSUE TITLE
После успешного проведения обмена, заявка так и висит

### ISSUE THREAD

**Issue by apelsin555** [swaponline/swap.react#446]
После успешного проведения обмена, уже проведённая заявка на обмен, так и висит как в общем списке ордеров и видна другим пользователям. У создателя она также остаётся висеть активной в "мои ордера".

**Comment by nikdementev** [comment]
у других написано что ордер в процессе и они не могут его нажать

**Comment by apelsin555** [comment]
Я про то, что зачем заявка остаётся висеть, если она уже проведена успешно? Её же люди видят. В ленте место занимает.

**Comment by nikdementev** [comment]
@apelsin555 Саша сказал пусть висит
