### ISSUE TITLE
Swap in wallet: Wrong error message on non-ethereum crypto balances

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/swap.react#447]
## What is working wrong?

Text on not enough balances

## What should happen instead?

The text should be customized so it reflects the corresponding asset.

## Steps to reproduce

- go to wallet
- choose a crypto (non-ethereum) with 0 balances
- click swap

uyou will see a stupid ethereum message

## Your system charateristics

all systems

## Does this affect atomic swap flow?

- [*] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [*] no

## Screenshots

![swap-why-token-why-ethereum](https://user-images.githubusercontent.com/22708849/45384116-c1fdbc00-b615-11e8-9b71-ee1723543090.gif)

## Additional info
Rewrite the text:

title should not say "Approve token"

instead it should say "insufficient balance"
also the text should go alpong the lines that in order to swap this crypto currency for another asset you need to have at least 0.003 BLAH on you balance.

**Comment by nikdementev** [comment]
При нажатие на кнопку swap
 - ERC20 и ETH  - проверка есть ли 0.02  ETH на балансе
 - для остальных блокчейнов проверка, что баланс выше необходимой комиссии
 - для каждой валюты свое описание

**Comment by vladiuz1** [comment]
- заодно кнопку переименовать на что-то английское
