### ISSUE TITLE
Добавить плейсхолдеры в раздел "вывести средства"

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#448]
![image](https://user-images.githubusercontent.com/2914674/45426996-6c252480-b6a6-11e8-93f5-b0d5c5bb2970.png)

**Comment by noxonsu** [comment]
border тоже сделать заметным

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/45427861-a5f72a80-b6a8-11e8-96ea-2ee64d8923d0.png)
