### ISSUE TITLE
https://swap.online/history не показывает ерс20

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#453]
1. не показывает биткоины
2. не показывает токены

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/88fead785ec2086d28ab1d871d955e3962838750

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/45497027-6bac8c80-b77f-11e8-8d3c-01d5f32715a2.png)
