### ISSUE TITLE
не вижу ордера (требуется удалить indexdb)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#457]
очень часто перестают быть видны новые ордера, приходится у нас для этого есть "лечилка" ручная https://wiki.swap.online/faq/#swap-faq-2 но это не выход. нужно отловить ошибку.

**Comment by caffeinum** [comment]
они не видны потому что долго грузятся

**Comment by noxonsu** [comment]
нет, мы это уже проходили, минут 5ть не появляются, после очистки indexdb появляются моментально

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/1b5e3b8998e4abd8f13990150aa9aaafcd3e4037
