### ISSUE TITLE
нет конфигурации flow... возможно еще в процессе разбивка конфигурации по файлам

### ISSUE THREAD

**Issue by shendel** [swaponline/swap.react#458]
Не работает обмен токенов
Ошибка в консоле... нет такого направления обмена
![image](https://user-images.githubusercontent.com/1880211/45602759-3c6e7780-ba2c-11e8-8bac-dc75ca56ceca.png)
Файл конфигурации
/shared/instances/newSwap.js
![image](https://user-images.githubusercontent.com/1880211/45602771-793a6e80-ba2c-11e8-90ca-61914579c9ea.png)

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/blob/950dede179ba062359b8f3fe03e5197ae83de7ac/shared/pages/Swap/Swap.js
пока сделал временное решение сегодня доделаю хорошо
