### ISSUE TITLE
при регистрации eos не появляется адрес

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#463]
## What is working wrong?

При регистрации EOS на тест нете, при первом нажатии ничего не происходит, при втором появилась пустая строка(кнопки исчезли, вместо них ничего не появилось)
## What should happen instead?

После клика должен появляться адрес 
.

## Steps to reproduce

1-заходим на тест нет
2- нажимаем ригстр адрес в троке EOS

## Your system charateristics

- Yandex 
- windows: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

## Screenshots
![image](https://user-images.githubusercontent.com/43392281/45723560-48f1fc00-bbf5-11e8-8630-357ea4c49591.png)

**Comment by nikdementev** [comment]
сейчас все появляется надо было кинуть денег на тестовый аккаунт EOS
![image](https://user-images.githubusercontent.com/17093843/46125991-20d94d00-c234-11e8-9414-40a62ee099e5.png)
