### ISSUE TITLE
Обновление BTC может зависнуть на обновлении рандомно

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#466]
если не получен ответ от ноды с балансом в течении 30 секунд, снизу показывать hint: reload

**Comment by xahon** [comment]
@nikdementev есть апи хинтов? как их вызывать?

**Comment by noxonsu** [comment]
нет хинтов нет, надо делать. ну добавь пока через alt (или tilte) в тег

**Comment by xahon** [comment]
@noxonsu это получается юзеру нужно будет наводить на поле чтобы узнать что произошла ошибка)

**Comment by noxonsu** [comment]
ну сделай просто ссылку reload
