### ISSUE TITLE
Таблица скачет при обновлении если кол-во цифр по ширине меньше чем ширина иконки лоадера

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#467]
![](https://i.imgur.com/3BeItIE.png)

**Comment by noxonsu** [comment]
скрин?

**Comment by xahon** [comment]
![screenshot_20180924_100624](https://user-images.githubusercontent.com/18731681/45934445-b4670f80-bfe1-11e8-94c7-5e5dcb60ac1e.png)
![screenshot_20180924_100626](https://user-images.githubusercontent.com/18731681/45934446-b4ffa600-bfe1-11e8-8f82-9cdb1d049ade.png)

**Comment by xahon** [comment]
@noxonsu к сожалению это не смержено
