### ISSUE TITLE
Когда меняешь exchange rate на ноль, buy становится NaN, если добавить еще цифру - sell также становится NaN

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#469]

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/issues/478 еще заодно это

**Comment by xahon** [comment]
Сделал пока в ревью, есть еще косяк с NaN в этом окошке, чуть позже нужно будет переоткрыть

**Comment by xahon** [comment]
PR #489

**Comment by xahon** [comment]
тоже уже в мастере
