### ISSUE TITLE
Сделать Show More Coins модальным окном

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#471]

**Comment by xahon** [comment]
Может лучше сделать окно "Show more coins" модальным как, например, "Import keys".  
1. Не нужно нажимать кнопку назад в браузере (по-другому как я понял выйти из него нельзя)  
2. Когда список длинный в "Show more coins", то ты попадаешь в конец списка и приходится скроллить вверх

**Comment by noxonsu** [comment]
давай

**Comment by xahon** [comment]
Тут собственно и вопрос. Эта секция имеет собственную урлу `/coins`. Если её сделать модалкой, то уже урлы отдельной не будет
@nikdementev

**Comment by nikdementev** [comment]
не будет урлы и не будет, мы из урла ничего не получаем

**Comment by noxonsu** [comment]
у меня на https://testnet.swap.online/ вообще нет show more coins

**Comment by xahon** [comment]
@noxonsu оно появится если скрыть одну или несколько валют
![screenshot_20180924_101019](https://user-images.githubusercontent.com/18731681/45934473-158ee300-bfe2-11e8-8460-7d3839fa55c7.png)

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/45934944-dcd51680-bfad-11e8-818c-fd55c1d37f78.png)
@xahon видишь как получается, но возможно будут вопросы или какие то доп задания по этому не пиши так в PR

**Comment by xahon** [comment]
@nikdementev хорошо
