### ISSUE TITLE
изменить поведение при клике на адрес кошелька

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#477]
по нажати на кошель нужно не отсылать на всякие сканы и сплореры, а давать стандартную выписку из транз (редирект на страницу истори со включенным фильтром по этой крипте)

Date | From | To | Amount | Tx Fee | Balance

**Comment by HovhannesKarapetian** [comment]
Нужно чтобы при клику сюда  переходили на https://testnet.swap.online/history ?
$![screenshot_1](https://user-images.githubusercontent.com/33616025/45857662-3f0afd00-bd9d-11e8-9e30-d2759d21233e.png)

**Comment by noxonsu** [comment]
да но перед этим на странице истории надо сделать, чтоб показывалисб только ETH транзакции
