### ISSUE TITLE
неправильная разрядность в форме добавления

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#478]
![](https://i.imgur.com/T9T6g6c.png)

**Comment by xahon** [comment]
exchange rate - это отношение продажи к покупке или наоборот?

**Comment by noxonsu** [comment]
нет, это сколько можно купить ЕОС за 1 биткоин

**Comment by xahon** [comment]
@noxonsu просто поменять местами или сделать чтобы считало exchange rate в обратном направлении?

**Comment by noxonsu** [comment]
сделай для начала как проще, потом будем смореть

**Comment by nikdementev** [comment]
нет надо по другому делать саня хочет что бы была одна основная валюты и все курсы на основе нее, а не просто поменять местами,
