### ISSUE TITLE
при попытке в мейннете купить немного свапов баг в флоу (покупка erc не работает)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#479]
когда маркетмейкер подтвердил сделку и покупателя перебросило на свап
![](https://i.imgur.com/b1wtSmZ.png)

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/4ce95a8652b4cc3bd638616cf3c2058fc7fad570
сейчас этой ошибки не будет

**Comment by noxonsu** [comment]
ну и закрою когда не будет сам
