### ISSUE TITLE
проверка eos 20.09

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#481]
**проверка создания адреса**
- [x] при заходе на главную страницу мне виден адрес, либо кнопка для его создания
- [x] при нажатии на кнопку, мне показывается прелоадер а затем сразу адрес
- [x] так или иначе адрес создается и баланс показывает 0

**проверка ввода и вывода средств**
- [x] я отправил деньги извне и они пришли на баланс
- [x] при нажатии на send показывается форма для ввода адреса и суммы, при этом показано сколько доступно для перевода
- [x] если ввести сумму меньшую чем минимально возможная отправка то покажется ошибка
- [x] если ввести сумму большую чем баланс то покажется ошибка
- [x] форма не принимает левые данные кроме числа
- [ ] при нажатии на кнопку отправки появляется прелоадер
- [ ] как только транзакция замайнится прелоадер исчезает 
- [ ] транзакция на отправку видна в истории

**создание ордера на продажу едениц криптовалюты за биткоин**
- [x] на странице кошелька есть кнопка SWAP, которая означает что можно поменять эту крипту на другую
- [x] заходим на в свап и виден ордербук (таблица с обьявлениями на покупку и продажу)
- [x] видна кнопка create order при нажатии на нее появляется форма для создания ордера
- [x] в форме виден мой доступный баланс и он корректный
- [ ] я хочу продать 10 едениц за 0.1 биткоин, ввожу данные в sell 10 , в buy 0.1 btc автоматически устанавливается курс 100 едениц / BTC 
- [x] я хочу продать больше чем у меня есть, появляется ошибка
- [ ] если поменять курс то поменяется поле buy, а поле сколько продать (sell) остается неизменным
- [x] при нажатии далее все данные указаны верно 
- [x] mining fee тоже указан верно
- [x] если зайти из другого браузера и попробовать найти этот оредр то он будет виден в корректном месте

**создание ордера на покупку едениц криптовалюты за биткоин**
- [x] хочу купить 100 едениц криптовалюты за 0.1 BTC ввел 100 едениц в поле buy и 0.1 BTC в поле sell все верно выставилось, курс верный (показывает 1000 едениц за BTC)
- [x] ордер создается

**пробуем свпнутся**
- [x] получилось свопнутся из двух браузеров (обоим в итоге написало "сенкью")

**Comment by noxonsu** [comment]
Добавь ссылки на соотвествующие ишью, которые открыты или существуют на те пункты где не отмечено галкой

**Comment by Pasha8914** [comment]
https://github.com/swaponline/swap.react/issues/493
