### ISSUE TITLE
описать структуру файлов и папок

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#484]
основный и файлы и папки нужно описать. пример 

.github	- служебная папка гитхаба
bin папка с прекомпиленными версиями некоторых приложений
-compile тут конкретно скомпиленные файлы
-server тут хранятся файлы которые нужны для работы http сервера который используется для генерации фаусета

ну и тп.

цель сделать содержание по которому будет понятно больше об архитектуре и где что.

**Comment by nikdementev** [comment]
Сделаю после того как сделаю рефакторинг

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/45841396-61ac0000-bd22-11e8-91da-d26bd18eb214.png)
так пойдет ?

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/67ade441177a77dad7a4c2d3133ba5b4d8c0e96c
