### ISSUE TITLE
вернуть стики и прелоадер в показатель пиров ipfs

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#495]
![](https://i.imgur.com/OZuVbJj.png) пропал прелоадер и надо сделать чтоб колчиество пиров было прилеплено как раньше

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/45840434-98cce200-bd1f-11e8-9e5a-8cb09cca4048.png)
