### ISSUE TITLE
нет истории свапов

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#496]
![](https://i.imgur.com/zyky87s.png) не вижу историю свапов

**Comment by noxonsu** [comment]
таск самому не закрывать!

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/45839671-b13bfd00-bd1d-11e8-8942-c7a97bb49611.png)
https://github.com/swaponline/swap.react/commit/2cdd8642f4a35af60a5814ab8d05d2af1eb78177

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/45840514-c44fcc80-bd1f-11e8-9443-6482cdb9feb7.png)

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/45849272-00902680-bd3a-11e8-8d25-3eab6565d256.png)
