### ISSUE TITLE
в мейннете закрывать оверлеем весь экран если появились денги на счету и чел не сохранил приватник

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#501]
пока у юзера на счету по нулям он может привтаник не сохранять но если обнаружены деньги или токены сразу требуется заблокировать доступ к интерфейсу пока он не подтвердит что сохранил приватник. 

ну то есть показывать это:

**Comment by noxonsu** [comment]
запиши видео на screentogif (только небольшое, секунд 10-15) разместим в твитере

**Comment by xahon** [comment]
![screencast](https://user-images.githubusercontent.com/18731681/45986376-8ac7ea00-c0ae-11e8-8a2f-1765efc8dd4d.gif)

**Comment by nikdementev** [comment]
сделай без лоадера сразу окно для сохранения и текстом скачать
только его нарисовать хорошо необходимо не в таком количестве красного а по спокойнее

**Comment by xahon** [comment]
@nikdementev так это лоудер который сейчас по дефолту вряд-ли его получится убрать, если только оверлей поставить поверх него

**Comment by xahon** [comment]
@nikdementev так лучше? 
![image](https://user-images.githubusercontent.com/18731681/46050435-77cd1c80-c177-11e8-80bd-248092b13817.png)
