### ISSUE TITLE
нет значка крестика в уведомлении на начало свапа

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#503]
![image](https://user-images.githubusercontent.com/2914674/45853805-9eabdd00-bd8a-11e8-88c4-17d3fdbd26f1.png)

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/b5e61b5c6e72be8f333edefe26ecc73bb970b910

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/45935244-232c7480-bfb2-11e8-9f56-1f2d5a54de48.png)
