### ISSUE TITLE
не работает конвектор

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#515]
я хочу продать 10 едениц за 0.1 биткоин, ввожу данные в sell 10 , в buy 0.1 btc автоматически устанавливается курс 100 едениц / BTC, НО
![image](https://user-images.githubusercontent.com/43392281/45987168-63275080-c0b3-11e8-9680-c51b46144678.png)

**Comment by xahon** [comment]
#478 сказали по-другому делать, но так и не понял как именно

**Comment by noxonsu** [comment]
должен быть курс 100 EOS / BTC в  этом случае как на скрине

**Comment by xahon** [comment]
![image](https://user-images.githubusercontent.com/18731681/45990360-324f1780-c0c3-11e8-8428-0db372395836.png)

**Comment by noxonsu** [comment]
ну вот сейчас логично

**Comment by xahon** [comment]
@noxonsu закрой, пожалуйста

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/issues/545

**Comment by caffeinum** [comment]
> не работает конвектор
да, когда отопление дадут
