### ISSUE TITLE
при переходе в SWAP на еос и другие не ерс20 просит сделать апрув (ну или пополнить баланс)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#518]
![](https://i.imgur.com/mGeHWEO.png )

**Comment by noxonsu** [comment]
(после очистки локалстораджа)

**Comment by noxonsu** [comment]
сюдаже: я смогу запустить свап не имея эфира на счету (но уведомление показалось типа пополните счет, но все равно отправился реквест на свап другой стороне)

**Comment by nikdementev** [comment]
эфир нужен на все свапы кроме EOS

**Comment by noxonsu** [comment]
лайткоин, биткоин кеш просят апрув. кроме того у меня на счету ровно 0.02 ETH и все равно просит

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/46117848-291d9200-c20c-11e8-98cf-f7efc4e5fc19.png)
![image](https://user-images.githubusercontent.com/1909384/46117853-2d49af80-c20c-11e8-9040-1731430c5073.png)
