### ISSUE TITLE
Перенести Футер с Вики на основной сайт Swap.Online

### ISSUE THREAD

**Issue by chromebookman** [swaponline/swap.react#52]
Взять футер на wiki.swap.online
И запилить его на сайте swap.online

**Comment by noxonsu** [comment]
не в этом репо помойму надо делать

**Comment by rmixi** [comment]
ага, но я сделал)

**Comment by chromebookman** [comment]
Внизу есть белая полоска, как можно убрать?
@noxonsu @rmixi

**Comment by noxonsu** [comment]
сделать футер белым

**Comment by chromebookman** [comment]
@rmixi @BootWP Сделайте футер белым, на сайте Swap.online внизу. измените цветовую гамму.

**Comment by noxonsu** [comment]
если готово передвигай в ревью (поставь zenhub)
