### ISSUE TITLE
Система ввыдает ошибку в консоли net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by PetuhovaS** [swaponline/swap.react#520]
## What is working wrong?

При обновлении страницы, клике на “Wallet”, “Exchange”, “History”, “Affiliate”, “Listing” получаем ошибку в консоли

## What should happen instead?

...Describe what do you think should happen instead in this situation...

## Steps to reproduce
1. Сделать клик на любой из вкладок хедеров “Wallet”, “Exchange”, “History”, “Affiliate”, “Listing”
2. Посмотреть ошибку в консоли  - net::ERR_CONNECTION_REFUSED"
## Your system charateristics

- Browser: Chrome
- OS: Ubuntu
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/46947841-ce49be80-d084-11e8-8bd6-9328d91681a3.png)
нужен какой то другой скрипт аналитики

**Comment by nikdementev** [comment]
выяснили что это add block блокирует и показывает такую ошибку
