### ISSUE TITLE
При клике на Share происходит только копирование ссылки

### ISSUE THREAD

**Issue by PetuhovaS** [swaponline/swap.react#521]
## What is working wrong?

"Во вкладке Exchange при клике на Share происходит только копирование ссылки Ожидаемый результат: Система предлагает другие браузеры для перехода по ссылке.
Фактический результат: Появляется только всплывающее предупреждение “Copied”"
## What should happen instead?

...Describe what do you think should happen instead in this situation...

## Steps to reproduce

1.  Перейти во вкладку ""Exchange""
2. Сделать клик на  “Share”"

## Your system charateristics

- Browser: Chrome 
- OS: Ubuntu
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...

**Comment by noxonsu** [comment]
не очень понимаю зачем другие браузеры? в одном браузере нельзя открыть другой браузер

**Comment by PetuhovaS** [comment]
Я имела в виду чтоб система предлага отправить ссылку на фейсбук, инстаграмм например.

**Comment by nikdementev** [comment]
не понятно что делать и как
