### ISSUE TITLE
Скопированная ссылка не открывается в браузере Mozilla

### ISSUE THREAD

**Issue by PetuhovaS** [swaponline/swap.react#522]
## What is working wrong?

"Во вкладке Exchange при клике на Share копируем ссылку, пробуем открыть ее в браузере Mozilla
 Ожидаемый результат: Система переходит по ссылке и открывает вкладку Exchange
Фактический результат:  Контент не отображается"
## What should happen instead?

...Describe what do you think should happen instead in this situation...

## Steps to reproduce

"1. Перейти на вкладку ""Exchange""
2. Кликнуть на Share - скопируется ссылка
3. Открыть браузер Mozilla
4. Вставить ссылку"

## Your system charateristics

- Browser: Mozilla
- OS: Ubuntu
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...

**Comment by noxonsu** [comment]
дубль https://github.com/swaponline/swap.react/issues/523
