### ISSUE TITLE
Система не открывается в браузере Mozilla

### ISSUE THREAD

**Issue by PetuhovaS** [swaponline/swap.react#523]
## What is working wrong?

"Пробуем открыть сайт в браузере Mozilla
 Ожидаемый результат: Сайт загружается
Фактический результат:  Контент не отображается"
## What should happen instead?

...Describe what do you think should happen instead in this situation...

## Steps to reproduce

1. Открыть браузер Mozilla
2. Перейти по ссылке https://testnet.swap.online"
## Your system charateristics

- Browser: Mozilla
- OS: Ubuntu
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...

**Comment by noxonsu** [comment]
у меня открылось в файрфоксе, если в убунту не открывается, то их слишком мало

**Comment by xahon** [comment]
![image](https://user-images.githubusercontent.com/18731681/46253872-48951300-c4c9-11e8-8747-1be8b8c7e700.png)

Archlinux 4.17

**Comment by nikdementev** [comment]
я всегда пользуюсь для обменов firefox и все хорошо
отображается только на ubuntu
