### ISSUE TITLE
Вкладка Exchange не выделяется

### ISSUE THREAD

**Issue by PetuhovaS** [swaponline/swap.react#526]
## What is working wrong?

"При переходе на вкладку Exchange она не выделяется подчеркиванием.
Ожидаемый результат: При переходе на вкладку Exchange она  выделяется подчеркиванием.
Фактический результат:При переходе на вкладку Exchange она не выделяется подчеркиванием.
"

## What should happen instead?

...Describe what do you think should happen instead in this situation...

## Steps to reproduce

1. Перейти во вкладку "Exchange"

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

https://prnt.sc/kwzssr

**Comment by xahon** [comment]
Merged

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/46117872-494d5100-c20c-11e8-9ab0-76e116f320fa.png)

![image](https://user-images.githubusercontent.com/1909384/46117868-40f51600-c20c-11e8-9859-c2cd7d9afe76.png)

А тут наоборот, она выделяется

**Comment by noxonsu** [comment]
видимо перешел на главную откудато

**Comment by xahon** [comment]
@caffeinum как перейти на верхний экран?
