### ISSUE TITLE
проверять необходимые доступы к публичным нодам и писать об их недоступоности 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#530]
# Problem
у одного из клиентов в консоли
![image](https://user-images.githubusercontent.com/2914674/46035826-5f450e00-c147-11e8-8b2c-6333e4bcbabb.png)

такое ощущение, что у него какой то жесткий файрвол. по идее 

# Task

у нас должен быть чекер что доступны необходимые ресурсы, если нет писать "недоступна публичная нода биткоина" под балансом. 

# Purpose

(What this feature is intended to do or solve?)

# Area

главная страница, о недоступности важных урлов для каждого блокчейна писать красным под адресом, а на мобиле вместо баланса показывать красный знаек ерора (восклицательный знак) при клике уже показывать ошибку что не доступен такой то сайт

# Estimate time of implementation

# Additional data

**Comment by nikdementev** [comment]
1 - Сделать прям загрузку вместо лоадера где будет все проверяться и писаться пользователю
пока все не пройдет сайт не запустить
2 - Найти по 3 - 4 аналога каждой API и выбирать рабочую

**Comment by noxonsu** [comment]
"выбирать рабочую" усложнение (чекер сам по себе сложный, не достаточно просто на 200 ОК проверить, там еще куча всего) лучше писать "нода не доступна, выберите другую" и чел там сам выбирает

**Comment by nikdementev** [comment]
мне все равно делать выбор API для кора

**Comment by noxonsu** [comment]
дубль https://github.com/swaponline/swap.react/issues/968
