### ISSUE TITLE
SEO сменить description на главной странице

### ISSUE THREAD

**Issue by 1maxim** [swaponline/swap.react#535]
URL: https://swap.online
Description: Atomic swap wallet will help you to exchange cryptocurrencies instantly in a more secure way exluding third-parties. Decentralized exchange.

**Comment by caffeinum** [comment]
*excluding

**Comment by noxonsu** [comment]
сейчас вообще дескрипшина нету! 

вот от дарьи

Our wallet with Atomic swap algorithms will help you store and  exchange cryptocurrencies instantly and more secure without third-parties. Decentralized exchange.

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/46108392-a2a28980-c1e6-11e8-8d49-9c6be947ea09.png)
