### ISSUE TITLE
orders: неправильные надписи про направление обмена

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#543]
## What is working wrong?

Непонятно, в какую сторону обмениваюсь:
![image](https://user-images.githubusercontent.com/1909384/46118794-00e46200-c211-11e8-9146-2897651ed032.png)

## What should happen instead?

Раньше было правильно: сверху было you have USDT, снизу было you have USDT

## Steps to reproduce

https://swap.online/usdt-swap

## Your system charateristics

- Browser: Chrome
- OS: Mac OS X Mojave
- Mainnet or Testnet: mainnet

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

**Comment by noxonsu** [comment]
да вообще убрать надо выбор направления, выбор должен быть при клике на ексченж вообще https://github.com/swaponline/swap.react/issues/483
