### ISSUE TITLE
orders: привести все котировки с стандарту

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#545]
1. в каждой паре есть главная крипта, обычно это BTC или USDT . Везде всегда она должна писаться после слеша.  
2. котировки всегда пишутся по формуле "сколько стоит альткои если измерять в главной валюте". тоесть если пара ETH / BTC то получается гдето 0.03 . размерность у котировки отсутсвует, тоест нельзя писать 0.03 ETH / BTC  (сейчас пишется в добавлении ордера)
3. но можно писать так 0.03 BTC . например в ордербуке.

- [ ]  исправить добавление оредра
- [ ]  исправить ордербук
- [ ] проверить, что будет если создавать ордер на продажу BTC а покупать ETH правильно ли выставлена котировка

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/46258665-8c8f1480-c4d7-11e8-8d8b-c894a5cfe3f7.png)


около недели назад кто-то поменял заголовки таблицы, надо просто вернуть как было, было все правильно

**Comment by noxonsu** [comment]
да не это старая проблема, у нас не будет выбора направления сверху и тогда будет проще, но сейчас надо курсы сделать стардартными
