### ISSUE TITLE
DropDown on click error

### ISSUE THREAD

**Issue by xahon** [swaponline/swap.react#547]
## What is working wrong?

Нажатие на спиннер выбора валюты вызывает ошибку 
![image](https://user-images.githubusercontent.com/18731681/46183080-87349d00-c312-11e8-86d6-c71cd5f3fffd.png)
![image](https://user-images.githubusercontent.com/18731681/46183094-9a476d00-c312-11e8-9794-728d261e6bf7.png)

## Steps to reproduce

1. Нажать на дропдаун

**Comment by nikdementev** [comment]
это еще вчера с утра пофиксил
