### ISSUE TITLE
Некорректное отображение swaps

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.react#549]
![screenshot_20180928_132118](https://user-images.githubusercontent.com/43396375/46186491-3e84e000-c322-11e8-9a09-941279c32149.png)
На странице не отображаются те свапы, которые добавлены в core.
Вместо этого, отображается только одна свап-пара для любой монеты, кроме btc: [текущая-монета]-LTC
Для btc отображается список всевозможных свап-пар, даже если их нет в core.

Предлагаю починить корректное отображение добавленных в core свап-пар добавлением массива свап-пар и проверки.

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/81305fd01ca9cffcd89fc3d5ce11b8d52ba4157c
