### ISSUE TITLE
сделать чтоб билд мог запускатся офлайново

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#55]
сейчас при скачке билда все тянется с testnet.swap.online а надо чтоб с локала. возможно это отдельный билд надо делать? если да, то нужен конфиг swap.local

**Comment by nikdementev** [comment]
Там нужно две строчки изменить, можно просто перед сборкой менять их.
![image](https://user-images.githubusercontent.com/17093843/41505376-8cf874fe-724b-11e8-83e8-0720b544499e.png)

**Comment by noxonsu** [comment]
прикрепляй билжы сюда прям. в архиве

**Comment by noxonsu** [comment]
в другой раз
