### ISSUE TITLE
Некорректно рассчитывает расходы в истории

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.react#574]
Как видим, было переведено 10 монет, а выводит остаток перевода.

![screenshot_20181002_004312](https://user-images.githubusercontent.com/43396375/46295823-58e9e280-c5dc-11e8-8c71-64700763cdce.png)

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/46301245-7bfd9d80-c5ae-11e8-819c-7ba28d84b328.png)
хм он проверяет vout по нашему адресу возможно на этой API оно работает по другому
потому что на скрине всего 2 output и не одного нашего
скорее всего просто всегда 1 vout надо изучить
