### ISSUE TITLE
в тестнете при саом первом заходе показывать сообщение "обновити страницу, чтоб получить демо деньги"

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#585]

**Comment by nikdementev** [comment]
Нет, надо просто больше кошельков с тестовыми бабками или наоборот меньше,
там можно и 5 раз подряд обновлять и всегда будет 0

**Comment by noxonsu** [comment]
да там изначально всегда ноль, всегда надо один раз обновисть
