### ISSUE TITLE
Информационный перегруз /mobile

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#587]
Ссылка: testnet.swap.online
Этапность: Атомарный обмен между эфиром и биткоином/ процесс атомарного обмена
Подробности: Непонятно почему так много информации выведено в процесс атомарного перевода, деморализует взгляд.
14
![image](https://user-images.githubusercontent.com/2914674/46389983-0ee92580-c6de-11e8-8cc1-6c5534114b37.png)

**Comment by caffeinum** [comment]
мб сделаем на мобилке шрифт поменьше и пузырьки сверху , 
( 1 ) – ( 2 ) – ( . )  – ( . )  – ( . )  – ( . )

**Comment by noxonsu** [comment]
у нас обычный прогресс бар есть, просто выключен для отладки

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/issues/799
