### ISSUE TITLE
TXT документ с ключами имеет странные маркеры /mobile

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#591]
Ссылка: testnet.swap.online
Этапность: Атомарный обмен между эфиром и биткоином/ просмотр скачанных ключей
Подробности: Помимо того, что расстояние между эфиром и его адресом просто огромное, адрес эфира как-то странно выделяется, то есть его часть (зеленым цветом), это может вызвать некоторое недопонимание. (убрать пустое пространство и лайткойн в самый конец)
11
![image](https://user-images.githubusercontent.com/2914674/46390355-0d206180-c6e0-11e8-92c6-31848fc44fe0.png)

**Comment by nikdementev** [comment]
это твой телефон думает что это номер телефона

**Comment by caffeinum** [comment]
лайткоин в самый конец?

**Comment by noxonsu** [comment]
ну да по мере подключения

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/46600666-92967e00-caf3-11e8-8b29-988b7da7f464.png)
он же и так в конце
