### ISSUE TITLE
Некорректное формирование TXT файла с ключами /mobile

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#593]
Ссылка: testnet.swap.online
Этапность: Атомарный обмен между эфиром и биткоином / просмотр TXT с ключами
Подробности: Формирование TXT происходит с недочетами. Во первых зачем-то поялвяется litecoin адрес, хотя мы его не запрашивали. Расстояние между блоками текста слишком большое, его надо как-то сохранить более корректно. Т.е. лайткоин в конец, сократить расстояние между блоками текста при сохранении)

![image](https://user-images.githubusercontent.com/2914674/46390399-46f16800-c6e0-11e8-972b-d9fd0629618d.png)

**Comment by noxonsu** [comment]
лайткоин внис сдвинут и нет проблем

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/46408499-0531e300-c71b-11e8-8745-53b886bd81d0.png)
https://github.com/swaponline/swap.react/commit/7bb1fc561cff862b7a1f1a2facbfa53c9b16396e
