### ISSUE TITLE
Неактивна кнопка NEXT/едет верстка/ mobile

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#597]
Ссылка: testnet.swap.online
Этапность: Атомарный обмен между эфиром и биткоином / добавление оффера
Подробности: При заполнении всех данных кнопка NEXT остается неактивной, верстка едет на кнопке NEXT
-Починить кнопку NEXT, исправить её сценарий
Скриншот ошибки:
![image](https://user-images.githubusercontent.com/2914674/46390490-be26fc00-c6e0-11e8-9f67-a91b67101468.png)

**Comment by nikdementev** [comment]
#601
