### ISSUE TITLE
добавить автоклик во время свапа

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#60]
Pasha Ivanov, [18.06.18 21:43]
https://github.com/swaponline/swap.react/commit/d457b1fce7d685655caffd9728aa0592b34e3032

Pasha Ivanov, [18.06.18 21:43]
добавил кнопку (не проверял работает ли) - надо ее распихать по свапам

это чтоб юзеры сами не кликали на розовые кнопки во время свапа

**Comment by nikdementev** [comment]
Доделал кнопку, и распихал по компонентам.
