### ISSUE TITLE
Нижняя плашка мешает вводу данных/mobile 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#600]
Ссылка: testnet.swap.online
Этапность: Атомарный обмен между эфиром и биткоином
Подробности: Нижняя фиолетовая плашка заслоняет весь вид. Неудобный набор, я бы оставил маленькую стрелку "назад" в углу.
Скриншот ошибки:

![image](https://user-images.githubusercontent.com/2914674/46390528-ee6e9a80-c6e0-11e8-931e-cd094f81170b.png)

**Comment by nikdementev** [comment]
Поменять intput type="number" что бы в мобильной версии отображались только цифры, а не куча букв
