### ISSUE TITLE
в тест нете не отображаются созданные ордера, созданные другими участниками

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#607]
## What is working wrong?
![image](https://user-images.githubusercontent.com/43392281/46447224-f94e2b80-c7c3-11e8-8d68-4c20efd00a5f.png)

...Describe the bug briefly...
![image](https://user-images.githubusercontent.com/43392281/46447256-15ea6380-c7c4-11e8-8fe0-538653d187f0.png)

## What should happen instead?

работает локально

![image](https://user-images.githubusercontent.com/43392281/46447344-8b563400-c7c4-11e8-8497-d74f30dc252a.png)

w?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...

**Comment by Pasha8914** [comment]
Error: Uncaught TypeError: Cannot read property 'body' of undefined

**Comment by nikdementev** [comment]
ETH - на SWAP нет таких ордеров 
 а body у тебя на ноду биткойна ругалась
