### ISSUE TITLE
в testnet.swap.online не видны никакие оредра

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#613]
https://testnet.swap.online/btc-eth например  
![image](https://user-images.githubusercontent.com/2914674/46468730-f9592600-c7d9-11e8-8b56-ce0991d8e102.png)

**Comment by noxonsu** [comment]
IPFS сломался

**Comment by nikdementev** [comment]
Причем тут IPFS, 
https://github.com/swaponline/testnet.build/commit/b8dcfefe421b15383aec473f525c9bf8140c8432
сейчас все ок)
это был UglifyJs
