### ISSUE TITLE
добавить новый erc20 окен SWAP - наш собственный 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#62]
0x5f53dc58cad6101d943b26ffb9427723aeb816f9 ринкби ерс20 
0x14a52cf6B4F68431bd5D9524E4fcD6F41ce4ADe9 мейннет

тикер SWAP

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.core/issues/27 возможно задачи связаны

**Comment by noxonsu** [comment]
референс https://github.com/swaponline/Office/issues/73

**Comment by nikdementev** [comment]
commit](https://github.com/swaponline/swap.react/commit/e8aef14de8f7eb63f71f8fd36b9bb110f1e684c0)
на страницу баланс добавлены в свап нет)

**Comment by nikdementev** [comment]
6bf7bfcdae12fcf1d82694443ab5f55cea398d3c
