### ISSUE TITLE
flow "5. Waiting BTC Owner adds Secret Key to ETH Contact" не получает секрет

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#625]
![](https://i.imgur.com/GX9Dq7P.png)

**Comment by caffeinum** [comment]
а можешь показать Information about swap? у меня есть подозрение что тот второй чувак тоже не снял деньги

**Comment by caffeinum** [comment]
потому что он так и делает, он пытается получить секрет из контракта и ему вообще пофиг, пришлет ему второй чувак какие-то сообщения или нет
