### ISSUE TITLE
на адаптиве какое то говно с таблицами все размазало на километр

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#638]

**Comment by noxonsu** [comment]
![screenshot_2018-10-09-12-56-43-036_com android chrome](https://user-images.githubusercontent.com/2914674/46661958-e02dec00-cbc2-11e8-8f9c-16bffa72e80e.png)

**Comment by nthgness** [comment]
![image](https://user-images.githubusercontent.com/10322798/46764810-26c83700-cce6-11e8-9c24-d8bcd160f416.png)

**Comment by nthgness** [comment]
Пока сделал пробный функционал с кнопками, которые смог вместить, предлагаю сделать переключалку на троеточие для трех этих кнопок

@noxonsu, @caffeinum - давайте вместе подумаем еще завтра
