### ISSUE TITLE
Uncaught TypeError: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#639]
![image](https://user-images.githubusercontent.com/2914674/46663962-36e9f480-cbc8-11e8-9ea5-d82745eee913.png)

**Comment by caffeinum** [comment]
походу LTC

**Comment by sdwas** [comment]
Сейчас вроде все работает. Возможно были проблемы api эксплорера.

**Comment by caffeinum** [comment]
Неправильно, что падает на строчке req.body. Нужно добавить проверку раньше и писать информативное сообщение об ошибке: статус, который вернул запрос, и url, который пытались запросить

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/47699975-be55e100-dc25-11e8-8d3e-7cc805c760a0.png)
https://github.com/swaponline/swap.react/commit/71e24a57fa2662a4768610bdc11c9b5fa3afc7db
