### ISSUE TITLE
добавить онбоардинг

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#645]
на галвной странице должен быть онбординг вот https://wiki.swap.online/new-form.html ион его сверстал, нужно повесить на главную и постепенно улучшать

**Comment by BootWP** [comment]
Архив https://drive.google.com/open?id=1jE3JwC4DxaOILF5eNumo3EvTjUOkO5nN
Чтобы все работало нужны все эти скрипты http://joxi.ru/82QqpabcjlPw92

**Comment by nikdementev** [comment]
@noxonsu @BootWP мне это делать нормально в реакте или что ?
причем тут скрипты jquery ?

**Comment by noxonsu** [comment]
можем ли мы эту штуку вствить так же как фрму емейла и не праится?

**Comment by BootWP** [comment]
Можно, только мне нужно знать как подключить скачивание ключей к кнопке
"Download private keys"
http://joxi.ru/vAWyRxdi1Yjx3m

**Comment by nikdementev** [comment]
я выведу это функцию глобально как и до этого делали @BootWP

**Comment by BootWP** [comment]
я просто не в курсе как и работает, мне нужно от знать название функции которая это делает, и я ее прикручу к кнопке на on click

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/46750304-549a8500-ccc0-11e8-9256-f8c7782964ed.png)
@BootWP

**Comment by BootWP** [comment]
я попробовал три варианта, поставил с задержкой на 15 секунд и все равно не работают
http://joxi.ru/vAWyRxdi1Yjvzm
Как подключить downloadPrivateKeys чтобы работало?

**Comment by indapublic** [comment]
@BootWP 
вам нужно просто вызывать функцию```window.downloadPrivateKeys()```, судя по всему

**Comment by BootWP** [comment]
Все равно не работает
http://joxi.ru/brRYERBuJwyaZA
window.downloadPrivateKeys is not a function

**Comment by BootWP** [comment]
Окно добавлена, на данный момент показывается только один раз в сутки,
чтобы посмотреть форму больше раз нужно удалить куки по ссылке:
https://swap.online/?cleanmodalcookie=1
