### ISSUE TITLE
inposible to spend LTC

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#650]

**Comment by sdwas** [comment]
Подробности проблемы будут?

**Comment by Pasha8914** [comment]
нажимаешь спед-вводишь адрес и сумму, нажмаешь отправить и ничгео не происходит

**Comment by sdwas** [comment]
Я перевел, транзакция создалась, всё работает.
![screenshot_20181010_232713](https://user-images.githubusercontent.com/43396375/46739500-08f9d280-cce4-11e8-887c-0db23025fa75.png)

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/46790956-b272af80-cd48-11e8-9d7e-6a25df54dcc4.png)
все работает
