### ISSUE TITLE
лайткоин убрать пару на эфир, сделать только биткоин

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#651]
в виду того что у нас главная валюта битко а на эфир пока не делали обмен

**Comment by caffeinum** [comment]
в смысле не делали, если наоборот делали именно на эфир?

**Comment by noxonsu** [comment]
вот этот таск должен раз и навсегда запретить менять левые валюты https://github.com/swaponline/swap.react/issues/656

**Comment by caffeinum** [comment]
да, но у нас нет обмена лайткоина на биткоин

**Comment by nikdementev** [comment]
дубль
