### ISSUE TITLE
если в ордербуке нет ничего ИЛИ ЗАГРУЩА то показывать пустую таблицу как раньее  или ПРЕЛОАДЕР

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#660]
тоесть должен быдь бид ас с подписами "There is no orders here" сейчас выглядит так 
![image](https://user-images.githubusercontent.com/2914674/46736720-653c0280-cca2-11e8-9b85-564efe5dd29a.png)

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/46763616-f6cb6480-cce2-11e8-82d6-f2327d6a3791.png)
согласен, удалить вот это условие нужно

**Comment by noxonsu** [comment]
ну так удали. кроме того у нас большой эпик. ситуация. два друга сидят с телефонами один создает ордер второй его не видит больше 10 сек и начинает все тыкать.
