### ISSUE TITLE
На рассмотрение: в случае импорта своих ключей не заставлять снова их же сохранять

### ISSUE THREAD

**Issue by 1maxim** [swaponline/swap.react#664]
Как по мне неудобно:
если юзер импортнул свои ключи на сайте, то нет смысла его спрашивать сохранил ли он свои же только что импортированные ключи и его просить их вбить их же повторно проходя подтверждение процесса сохранения.
Вариант решения:
Если определить что юзер импортировал свои ключи, то показывать ему другие попапы

**Comment by noxonsu** [comment]
согласен
