### ISSUE TITLE
EOS registration on swap.online

### ISSUE THREAD

**Issue by nikdementev** [swaponline/swap.react#666]
Nik ✨, [11.10.18 12:37]
@diademnetwork 
на swap.online после нажатия на кнопку buy account и когда нет денег,
показывается аккаунт и сохраняется в localstorage приватник и аккаунт
но explorer его не видит)

**Comment by noxonsu** [comment]
ошибка не исправлена на текущем тестнете, даже если деньги есть пишет что ак активирован, но екслорер его не видит.

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/pull/1204
