### ISSUE TITLE
add indent

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#677]
<img width="137" alt="2018-10-15 23 18 29" src="https://user-images.githubusercontent.com/43392281/46953353-fc54f000-d0d0-11e8-99ab-e879e8497374.png">
 нужно добавить отступы, ШОБ красиво было

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/b304d2bf538d6d3cb36b707365e2abe664f9430b
это сделанно
