### ISSUE TITLE
верстка. измененеие надписей в ордербуке

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#680]
![](https://i.imgur.com/r6CxKSE.png)

в текущей итерации после опроса нескольких человек делаем так. позже опрашиваем людей по новой и улучшем и тп.

**Comment by noxonsu** [comment]
![](https://i.imgur.com/ZjN4qdz.png)

1. На текущей версии никто из трех опрошеных не понял, что нажать чтоб поменять  эфир на биткоин. 
2. "что такое ASK и BID" вызывает вопросы не несет никакой смысловой нагрузки
3. просят ввети поясниение from X to Y 
4. кое кто предложил создать ордер
5. amoun, price и total так же не несут никакого смысла. Сумма чего по чем и сколько, при медитации секунд через 10 вроде как понятно.

на новой картинке.
1. очевидно что надо нажать на одну из фиолетовых кнопок "start exchange ... ETH to ... BTC" очевидно сколько он получит в итоге и сколько отдаст.
2. понятно что такое BID и ASK (позже пригодится в проф трейдинге)
3. данное пояснение введено на розовые кнопки (нельзя ввести в шапке, потому что некоторые ордера свои и будет путаница, ранее с этим сталкивались в первых версиях и ввели isMy
4. продумывание размещение create order я пока опсустил, возможно стоит продублировать в каждой таблице (add order to table)
5. я заменил на конкретно суммы в чем измеряется данные в этой колонке

**Comment by noxonsu** [comment]
![](https://i.imgur.com/qw2nlHY.png) самому ишью не закрывать!

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/commit/01b0704e27eda250861d31363d1032492fc69ec6
![image](https://user-images.githubusercontent.com/17093843/47147794-af8f3600-d2d7-11e8-9af2-30736522c29c.png)

**Comment by caffeinum** [comment]
на кнопках одинаковый текст в верхнем и нижнем ордербуке

**Comment by caffeinum** [comment]
Start exchange это неправильно, Start exchanging или просто Exchange, 
но мне все равно BUY ETH больше нравится

**Comment by nikdementev** [comment]
@noxonsu все вопросы

**Comment by noxonsu** [comment]
Пока закрыто пока не будет инсайта
