### ISSUE TITLE
ели долго нет ответа от маркетмейкера клиенту показывать что делать

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#681]
![](https://i.imgur.com/hvgjaus.jpg)

через минуту давать сообщение "Скорее всего вторая сторона не приняля ваш запрос. Попробуйте выбрать другой ордер" (пруфрит от даши)

**Comment by nikdementev** [comment]
Если тот человек выйдет ордер сразу же удаляется, прям моментально я даже не успеваю нажать старт
если ты нажал старт другому пришло предложение он отклонил у тебя тоже пропадет
как ты сделал этот баг ?

**Comment by nikdementev** [comment]
Как можно его воспроизвести ?
 - как только я закрываю другой браузер ордер удаляется
 - если я жду пока прийдет уведомление и закрываю он тоже удаляется
 - если я отклоняю тут сразу же появляется кнопка розовая вместо надписи
не получилось повторить баг но нашел другой
https://drive.google.com/file/d/1CQR0FYHMsStyylYveLtLznvtHH7of7pH/view
