### ISSUE TITLE
swap: уведомлять о проблемах со свопом

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#686]
Если вторая сторона прекратила обмен, как-то уведомлять пользователя.

? Писать, что "Возможно, второй чувак оффлайн, отменить обмен?" и кнопка "Вернуться в ордербук", которая кидает на тот же ордербук. ?

То же самое делать, если во время свопа пришло событие user offline

**Все это не делать, если ты уже заблокировал деньги.**

@noxonsu

**Comment by nikdementev** [comment]
Тут есть только одна проблема человек может просто покинуть страницу с обменом но он будет
онлайн, так обычно и происходит потому что иначе обмен выполниться, а как бороться с этим я пока не могу предложить. Потому что блокирование средств очень быстро происходит, как по мне не актуальная проблема

**Comment by nikdementev** [comment]
дубль #237
