### ISSUE TITLE
Module not found: Error: Can't resolve 'swap.swap'

### ISSUE THREAD

**Issue by dehimer** [swaponline/swap.react#699]
## What is working wrong?

Can't run swap.react. Get many of errors like "Module not found: Error: Can't resolve 'swap.swap' in ..."

## What should happen instead?

Should run without errors.

## Steps to reproduce

- clone and install swap.react
- clone and install swap.core
- try run swap react (*npm run dev* or with *npm run start*)

## Your system charateristics

- Browser: Chrome 69.0.3497.100
- OS: OSX Mojave

## Does this affect atomic swap flow?

- [ ] yes
- [x ] no

## Are real funds at risk?

- [ ] yes
- [ x] no

## Screenshots

![2018-10-21 14 53 36](https://user-images.githubusercontent.com/2872894/47267026-bb346400-d546-11e8-8333-311f0c6a7774.png)

**Comment by nikdementev** [comment]
установи git submodule)

**Comment by dehimer** [comment]
Спасибо, не увидел в инструкции по установке. Я бы добавил
