### ISSUE TITLE
Изменить тултип граватара

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#707]
## What is working wrong?

![image](https://user-images.githubusercontent.com/43392281/47278666-02d1f300-d60e-11e8-8464-bbd236024c7b.png)
 тултип граватара выдает один и тот же текст для граватара пользователя и других пользователей ( текст неккоректный) 
## What should happen instead?

Исправить this is your automatically created gravatar. its unique for every profile 
либо на automatically created gravatar. its unique for every profile ,
либо для граватара данного пользователя оставить этот текст, а для остальных граватаров изменить. (можно указать такой- "Automatically created gravatar. its unique for every profile. You can see your in the upper right corner")

## Steps to reproduce

- steps
- to
- reproduce

## Your system charateristics

- Browser: 
- OS: 
- Mainnet or Testnet:

## Does this affect atomic swap flow?

- [ ] yes
- [ ] no

## Are real funds at risk?

- [ ] yes
- [ ] no

## Screenshots

... You can use Ctrl+V to place screenshots right into GitHub issue ...

**Comment by noxonsu** [comment]
можно так подробно ишью не оформлять))
