### ISSUE TITLE
ЕТН-SWAP пара не существует, но можно создать ордер

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#708]
## What is working wrong?

можно создать офер свап-эфир
![image](https://user-images.githubusercontent.com/43392281/47289734-85bf7180-d63f-11e8-8441-51e0bdd6e29a.png)
но перейти посмотреть оферы этой валютной пары нельзя (выбрав свап-эфир)
![image](https://user-images.githubusercontent.com/43392281/47289772-adaed500-d63f-11e8-8033-98e13cffd8e7.png)
 происходит переход на страницу ВТС-SWAP
![image](https://user-images.githubusercontent.com/43392281/47289813-d59e3880-d63f-11e8-8560-5a84b046cbbf.png)
но при этом в таблице ордеров таблица включает столбцы ЕТH и SWАР

Не понятно!
## What should happen instead?
 В случае если осуществляется создание ордера, несуществующей В. пары, выдавать ошибку. Так же при переходе на страницу несуществующей В. пары выдавать сообщение:

Unfortunately this currency pair does not exist yet, you can to write to our team and we will try to come up with something. team@swap.online

**Comment by nikdementev** [comment]
дубль
