### ISSUE TITLE
добавить страницу "Listing"

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#71]
в ней текст который делает владислав сопов (запросить у него) под текстом форма контактная "введите адрес вашего контракта (erc20 или любой другой)", вашу позицию в компании (ceo, cto, marketing, other) ссылку на иконку (желательно svg) форму отправлять пост запросом (аяксом) на landing.wpmix.net/newclient.php

**Comment by noxonsu** [comment]
заасайнил Леху пусть он сделает и потом пулреквест, а никита примет

**Comment by VladislavSopov** [comment]
https://docs.google.com/document/d/1_I0gTEMzsrkViNG4aA8O1zKbA5ewDYOVcdHqjgCS00E/

**Comment by nikdementev** [comment]
30a86865ed1cd57ba4e674265d6edc7f9da8da06
