### ISSUE TITLE
SEO задача metatags для страниц wallet

### ISSUE THREAD

**Issue by 1maxim** [swaponline/swap.react#710]
https://swap.online/Ethereum-wallet
title | Ethereum Wallet with Atomic Swap. ETH & ERC20 tokens compatible.
description | Receive, send & securely exchange Ethereum (ETH) & ERC20 token using Swap.Online wallet with integrated Atomic Swap algorithm.
h1 | Your online Ethereum (ETH) web wallet with Atomic Swap.

https://swap.online/Bitcoin-wallet
title | Swap.Online - Bitcoin (BTC) Web Wallet with Atomic Swap.
description | Send, receive and exchange Bitcoin (BTC). Swap.Online Bitcoin Wallet will allow you to exchange your coins using Atomic Swap technology.
h1 | Your online Bitcoin (BTC) web wallet with Atomic Swap.

https://swap.online/Eos-wallet
title | Swap.Online - EOS Web Wallet with Atomic Swap.
description | Swap.Online multi-currency wallet based on Atomic Swap technology where you can store, send and exchange EOS.
h1 | Your online EOS web wallet with Atomic Swap.

https://swap.online/BitcoinCash-wallet
title | Swap.Online - Bitcoin Cash (BCH) Wallet with Atomic Swap.
description | Swap.Online Web Wallet - here you can store, send, receive and exchange Bitcoin Cash (BCH) using Atomic Swap algorithms.
h1 | Your online Bitcoin Cash (BCH) wallet with Atomic Swap.

https://swap.online/Litecoin-wallet
title | Swap.Online - Litecoin (LTC) Web Wallet with Atomic Swap.
description | Litecoin (LTC) web wallet with Atomic Swap exchange. Send, receive, store and swap your cryptocurrency online.
h1 | Your online Litecoin (LTC) web wallet with Atomic Swap.

https://swap.online/USDT-wallet
title | Swap.Online - Tether (USDT) Web Wallet with Atomic Swap.
description | Atomic Swap web wallet allows you to store and exchange USDT to Bitcoin. Multi-currency wallet with decentralized exchange.
h1 | Your online Tether (USDT) wallet with Atomic Swap.

https://swap.online/{full name}-wallet ШАБЛОН для всех остальных коинов
title | Swap.Online - {full name} ({ticker name}) Web Wallet with Atomic Swap.
description | Atomic Swap Wallet allows you to manage and securely exchange {full name} ({ticker name}) with 0% fees. Based on Multi-Sig and Atomic Swap technologies.
h1 | Your online {full name} ({ticker name}) wallet with Atomic Swap.

**Comment by noxonsu** [comment]
@DariaPurtova пруфрид ждем, далее делаем

**Comment by DariaPurtova** [comment]
https://swap.online/Ethereum-wallet
title | Ethereum Wallet with Atomic Swap (exchange)
securely exchange Ethereum (ETH) & ERC20 - мы меняем токены на eth? помню, говорил, чтобы убрали такую возможность
description | Exchange Ethereum (ETH) & ERC20 token using Swap.Online (hot) wallet with built-in Atomic Swap exchange. (No fees, No registration or KYC)
//мне кажется в описании надо употреблять самые ппулярные по поисковым запросам слова плюс наши преимущества. из данного описания ничего не побуждает меня использовать никому неизвестный кошелек.//
h1 | Your online Ethereum (ETH) web wallet with Atomic Swap. (или так: Your Ethereum (ETH) hot wallet with Atomic Swap exchange)

https://swap.online/Bitcoin-wallet
title | Swap.Online - Bitcoin (BTC) Web Wallet with Atomic Swap. (или так: Your Bitcoin (BTC) hot wallet with Atomic Swap exchange)
description | Swap.Online Bitcoin Wallet will allow you to exchange your coins using Atomic Swap technology. (или так: Swap.Online Bitcoin wallet with Atomic Swap exchange will allow you to exchange your coins p2p.)
h1 | Your online Bitcoin (BTC) web wallet with Atomic Swap. //не нравится мне сочетание в одном предложение слов online и web, предлагаю просто hot wallet использовать//

https://swap.online/Eos-wallet
title | Swap.Online - EOS Web Wallet with Atomic Swap (exchange).
description | Swap.Online multi-currency wallet with built-in Atomic Swap exchange. Store, send, and exchange EOS.
h1 | Your online EOS hot wallet with Atomic Swap exchange.

https://swap.online/BitcoinCash-wallet
title | Swap.Online - Bitcoin Cash (BCH) Wallet with Atomic Swap exchange.
description | Swap.Online Web Wallet - here you can store, send, receive, and exchange Bitcoin Cash (BCH) using Atomic Swap algorithms. //может все же добавить p2p, no fees, no registration or kyc?//
h1 | Your online Bitcoin Cash (BCH) wallet with Atomic Swap.

https://swap.online/Litecoin-wallet
title | Swap.Online - Litecoin (LTC) Web Wallet with Atomic Swap.
description | Litecoin (LTC) web wallet with Atomic Swap exchange. Send, receive, store, and swap your cryptocurrency online.
h1 | Your online Litecoin (LTC) web wallet with Atomic Swap. (или hot wallet - можно проверить что популярнее по поиску web или hot)

https://swap.online/USDT-wallet
title | Swap.Online - Tether (USDT) Web Wallet with Atomic Swap.
description | Atomic Swap web wallet allows you to store and exchange USDT to Bitcoin. Multi-currency wallet with a decentralized exchange (based on Atomic Swap technology)
h1 | Your online Tether (USDT) wallet with Atomic Swap.

https://swap.online/{full name}-wallet ШАБЛОН для всех остальных коинов
title | Swap.Online - {full name} ({ticker name}) Web Wallet with Atomic Swap.
description | Atomic Swap Wallet allows you to manage and securely exchange {full name} ({ticker name}) with 0% fees. Based on Multi-Sig and Atomic Swap technologies. (manage tokens? что имеется ввиду?)
h1 | Your online {full name} ({ticker name}) wallet with Atomic Swap.

**Comment by indapublic** [comment]
@DariaPurtova Можете составить точный список (без замечаний, комментариев и переносов строк?)

А то, например, я затрудняюсь интерпретировать такую конструкцию:

> title | Ethereum Wallet with Atomic Swap (exchange)
> securely exchange Ethereum (ETH) & ERC20 - мы меняем токены на eth? помню, говорил, чтобы убрали такую возможность

**Comment by noxonsu** [comment]
@indapublic бери просто все исключив русский текст и //
