### ISSUE TITLE
SEO задача metatags для страниц обмена

### ISSUE THREAD

**Issue by 1maxim** [swaponline/swap.react#712]
https://swap.online/bch-eth ШАБЛОН для такого типа страниц (которые у нас постоянно будут появляться новые с разными монетами)

title | Atomic Swap {full_name1} ({ticker_name1}) to {full_name2} ({ticker_name2}) Instant Exchange
description | Best exchange rate for {full_name1} ({ticker_name1}) to {full_name2} ({ticker_name2}). Swap.Online wallet provides instant exchange using Atomic Swap Protocol.
h1 | Atomic Swap {full_name1} ({ticker_name1}) to {full_name2} ({ticker_name2}). No limit exchange with 0% fee

Ранее предоставлял уникальные метатеги на основные направления обмена, желательно их не затереть при присвоении другим страницам данного шаблона.

**Comment by noxonsu** [comment]
@DariaPurtova пруфрид

**Comment by noxonsu** [comment]
это страница с ордербуком.
