### ISSUE TITLE
в ордербуке перепутаны колонки

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#718]
![](https://i.imgur.com/7vksrPQ.png) но при этом если смотреть от овнера то все ок 
![image](https://user-images.githubusercontent.com/2914674/47325243-a4d3f880-d66b-11e8-9ead-04ed641143a2.png)

**Comment by noxonsu** [comment]
видимо это еще осталось со времен костыля с ismy

**Comment by caffeinum** [comment]
что перепутано?

**Comment by noxonsu** [comment]
![](https://i.imgur.com/yDOmBO0.png)
