### ISSUE TITLE
В истории свапов порядок неудобный

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#724]
![image](https://user-images.githubusercontent.com/1909384/47350128-d2e22880-d6bd-11e8-9ad4-0d37ccae2a93.png)

Наверное, последние свапы лучше, чтоб были вверху

**Comment by noxonsu** [comment]
плюс скрывать те что были старше месяца например (за кнопку "показат все")

**Comment by nikdementev** [comment]
Пока это очень не удобно делать, надо привести все flow к единообразию 
![image](https://user-images.githubusercontent.com/17093843/47384465-97da0680-d74a-11e8-9454-d07ece901057.png)
а проверять scriptValues я считаю не совсем правильно

решения 
 - либо вынести в this.swap время создания
 - на данный момент можно делать id.split('-')[1] (это как временное решение)
