### ISSUE TITLE
кешировать файлы, чтоб с мобилки не перезагружать их каждый раз

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#725]
https://github.com/TalAter/UpUp/

либа позволяет хранить файлы на устройстве, и не грузить их каждый раз. Подключается быстрее, чем uglify, а эффект тот же

**Comment by noxonsu** [comment]
не уверен, что необходимо, кеш можно в cf настроить

**Comment by indapublic** [comment]
uglify был нужен для того, чтобы повысить оценку от Google до Grade A. Эту проблему данная библиотека не решает.
Настроить кэш можно через nginx (или, как сказал @noxonsu, через Cloudflare).
Как себя поведет эта библиотека на проекте в стадии активного девелопмента - я не могу сказать.
