### ISSUE TITLE
ipfs quota error 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#735]
![](https://i.imgur.com/wamLBcu.png) новая ошибка не могу на мейннете ничего делать

**Comment by noxonsu** [comment]
помогла полное удаление indexdb и там реально было дохера записей

**Comment by nikdementev** [comment]
Это значит у тебя нет доступа в indexedDB или там нет места, по факту это не ошибка так говорят в ipfs
https://github.com/ipfs/js-ipfs/issues/1388#issuecomment-396424106
