### ISSUE TITLE
релизы как у майезервалета

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#742]
1. научится билдить локальную версию, чтоб работала с компа (не с локалхоста)
2. хром екстеншин 

пример https://github.com/kvhnuke/etherwallet/releases/tag/v3.23.1

**Comment by sdwas** [comment]
1. Для реализации необходимо перевести роутинг swap.react на HashRouter - используется в майезервалет. Данное решение может сломать SEO.
2. Зависит от п.1

**Comment by noxonsu** [comment]
а можно if (local) {HashRouter} else {...}  ? )

**Comment by nikdementev** [comment]
history.push() и все будет работать
