### ISSUE TITLE
сделать простую смену направления в создании ордера 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#752]
<img src="https://i.imgur.com/ph6XkJE.png">

вот тут неудобно надо мне поменять крипты местами, чтоб продавать свапы а не биток. Например просто это сделать если в верхнем выпадающем списке сразу сделать чтоб был первым элементом тот что в нижнем выпадающем списке выбран. сейчас вторую крипту приходится искать и скролить кучу

**Comment by nikdementev** [comment]
тут надо делать через reducers у тебя этот объект хранится в редюсере 
надо искать в нем нужную удалять и вставлять на 2ое место в списке
напиши экшен который будет это делать

**Comment by noxonsu** [comment]
что с этим ишью
