### ISSUE TITLE
в истории не показываются переводы erc20

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#758]
только  эфир и биткоин, а надо еще чтоб эфир показывался. можно парсить езерскан https://etherscan.io/address/0x55648de19836338549130b1af587f16bea46f66b#tokentxns

**Comment by nikdementev** [comment]
![Uploading image.png…]()
https://github.com/swaponline/swap.react/commit/df0f8d9fa6ad729085adecbc36401c91cba50b81

**Comment by noxonsu** [comment]
только что провел на мейннете свап, на syc2 пришедшие и отправленные токены не отобразились в истории

**Comment by noxonsu** [comment]
я отправил на другой кошелек SWAP токены и  эта транзакция не отобразилась в истории
