### ISSUE TITLE
в таблице не подсчитывается exchange rate

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#76]
http://joxi.ru/Rmzb7VkC0v0wdm

**Comment by nikdementev** [comment]
<img width="1117" alt="2018-06-26 11 03 34" src="https://user-images.githubusercontent.com/17093843/41883226-c7f03f88-7930-11e8-96d0-98fe5c104263.png">
[commit](https://github.com/swaponline/swap.react/commit/424eb628cc5039a014e50c416239c30c7ab5f137)
