### ISSUE TITLE
ошибка ipfs null при первом заходе 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#771]
все новые пользователи не подключаются к ipfs, требуется перезагрузить страницу. пока что мы перезагружаем ее после того как чел закрыл онбоардинг. 

проверить можно например через browserstack

**Comment by nikdementev** [comment]
допустим в tor нет такого я захожу каждый раз с чистого браузера
пока не могу воиспроивести баг

**Comment by noxonsu** [comment]
сейчас и у меня перестал проявлятся, странная фигня

**Comment by noxonsu** [comment]
видел как проявилась у лехи в инкогнито моде

**Comment by nikdementev** [comment]
в инкогнито моде IPFS не работает вообще я же писал

**Comment by noxonsu** [comment]
хз потом у него подключилось. ладно понаблюдаем еще

**Comment by caffeinum** [comment]
@nikdementev 
> в инкогнито моде IPFS не работает вообще я же писал
это только в файерфоксе и это тут вообще не при чем

Я это дебажил один раз. Баг этот возникает потому, что там (не помню где) стоит таймер на 8 секунд, и если за 8 секунд ipfs не загрузится, то _ipfs конечно же будет null

Во-первых, нужно по-любому выводить адекватное сообщение об ошибке, потому что ipfs часто не работает, и нужно давать об этом понять пользователю,

Во-вторых, понятно, сделать тот кусок кода не через таймер, а по-нормальному.

**Comment by nikdementev** [comment]
https://github.com/ipfs/js-ipfs/issues/1388#issuecomment-396424106
прочитай это
для второго нужно отсоединить IPFS от кора либо делать все асинхронно иначе никак

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/48263189-4f9f3180-e436-11e8-8b0c-04038eba2f45.png)
![image](https://user-images.githubusercontent.com/1909384/48263214-63e32e80-e436-11e8-8641-44d50d954b70.png)


ipfs пытается загрузиться и ждет, пока не получится

**Comment by nikdementev** [comment]
а то что прошло 30 секнуд ?

**Comment by caffeinum** [comment]
не понял
