### ISSUE TITLE
частичное закрытие заявки (возможно в core?)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#776]
Навеяно тестами свап онлайна челом из банкекса который не понял вообще куда жать. Мотивация на swap.online/exchange сделать полноценный омбенник, где человек выбирает направление, сумму на продажу и ему считается сразу сумма которая ему прийдет. После нажатия кнопки далее сразу начинается свап. 

вариант 1. берем с рынка
1. в ордербуке выбирается максимально большой ордер который может покрыть текущую заявку и который помечен флагом что возможно частичное исполнение.
2. берется котировка и калькулируется сумма к получению
3. юзер нажимает далее, отправляется запрос на начало свапа, но  с меньшей суммой
4. маркетмейкер принимает запрос и начинается процесс свапа с меньшей суммой
5. старый ордер маркетмейкера удаляется?

вариант 2. даркпул с ботами
1. юзер когда заполняет форму сам отправляет в ордербук свою заявку
2. ему сразу же приходят реквесты от ботов, но они не показываются, просто выбирается максимально выгодный и его цена берется за основу
3. при нажатии далее следовательно этот реквест принимается и начинается свап

@nikdementev @caffeinum возможно ли релизовать такое в течении двух итераций? так как юзабилити такого обменника повышается в разы. Если еще приделать сюда https://github.com/swaponline/swap.core/pull/138 то можно сказать что по UX мы догнали ченжели

**Comment by nikdementev** [comment]
если делать опционально по желанию пользователю то почему нет
