### ISSUE TITLE
Надо withdraw окно причесать, чтоб можно было вывести все и не писалось везед eth

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#777]

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/47780546-a3aa6780-dd0c-11e8-889b-4d9cedf768ad.png)
![image](https://user-images.githubusercontent.com/17093843/47780835-4236c880-dd0d-11e8-9e7c-e1fea76cdc7d.png)
https://github.com/swaponline/swap.react/pull/792
