### ISSUE TITLE
SEO задача. Залить тексты на страницы

### ISSUE THREAD

**Issue by 1maxim** [swaponline/swap.react#779]
https://docs.google.com/document/d/1A7mjCsRBkofhqiYFx1ADlLhR-HHeeBjbXgJ6h2hAMHg/ 
Тексты по ссылке.

Необходимо разместить текстовый блок перед футером. Т.е. под всем основным контентом каждой страницы.

**Comment by indapublic** [comment]
@noxonsu Требования/предствления к внешнему виду блока есть?

**Comment by noxonsu** [comment]
@indapublic нет просто текст обычный пока что

**Comment by noxonsu** [comment]
по видимому надо после принятия локализации

**Comment by Spaider15** [comment]
Возьмусь
