### ISSUE TITLE
wallet: новые валюты не видны нигде

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#790]
Когда обновляем список валют, часто бывает, что какая-то пропадает одновременно и из балансов, и из скрытых.

![image](https://user-images.githubusercontent.com/1909384/47734734-35fa2f00-dc6b-11e8-9192-26de28b7ad25.png)

![image](https://user-images.githubusercontent.com/1909384/47734775-4a3e2c00-dc6b-11e8-9c28-41683f7f733d.png)

Например, на скрине выше нет Телоса

localStorage:
![image](https://user-images.githubusercontent.com/1909384/47734798-5de99280-dc6b-11e8-96ab-fd053af555bb.png)

**Comment by nikdementev** [comment]
потому что ее не добавили на страницу скрытых валют

**Comment by caffeinum** [comment]
нужно сделать, чтоб так не происходило

**Comment by nikdementev** [comment]
ну надо проверять вручную что там сделали принятие props
