### ISSUE TITLE
дублирование информации в истории свапов

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#803]
![](https://i.imgur.com/ufzBV7B.png )

**Comment by noxonsu** [comment]
и если присмотрется один и тот же свап по 5ть раз

**Comment by nikdementev** [comment]
они не дублируются сейчас, но и не удаляется если до этого был повтор
могу сделать что бы была проверка и удалялись ?

**Comment by noxonsu** [comment]
все еще дублируются, новые тоже

**Comment by caffeinum** [comment]
может опять код затерли?
