### ISSUE TITLE
SEO задача. RU metatags для главной и страниц обмена

### ISSUE THREAD

**Issue by 1maxim** [swaponline/swap.react#806]
https://docs.google.com/spreadsheets/d/1f9grh7rVXql3cQiuQFD9IR0ahaJIH8RiQGqppWCr5RQ/edit#gid=683785932 - по данной ссылке в таблице РУ метатеги по основным направлениям обмена и для главной. (если не удобно будет скопирую сюда)

Шаблон для всех остальных страниц в том числе новых которые будут появляться:

title | Обмен {full_name1} ({ticker_name1}) на {full_name2} ({ticker_name2}) – Атомарный Обмен
description | Децентрализированный обменник Swap.Online предлагает вам лучший курс обмена {full_name1} ({ticker_name1}) на {full_name2} ({ticker_name2}). Онлайн кошелек без регистрации.
h1 | Атомарный Своп {full_name1} ({ticker_name1}) на {full_name2} ({ticker_name2}) – Моментальный Обмен с Комиссией 0%

**Comment by Spaider15** [comment]
Возьмусь
