### ISSUE TITLE
SEO задача. RU metatags для страниц wallet

### ISSUE THREAD

**Issue by 1maxim** [swaponline/swap.react#807]
https://docs.google.com/spreadsheets/d/1f9grh7rVXql3cQiuQFD9IR0ahaJIH8RiQGqppWCr5RQ/edit#gid=69236024 - по данной ссылке метатеги для wallet страниц для основных валют.

Для всех остальных валют и новых что будут появляться просьба присвоить шаблон:

title | Онлайн кошелек {full name} ({ticker name}) с функцией Атомарного Свопа (Atomic Swap)
description | Swap.Online - это децентрализированный онлайн веб кошелек для криптовалюты {full name} ({ticker name}) без регистрации. Легкий обмен криптовалют внутри кошелька.
h1 | Ваш онлайн кошелек для {full name} ({ticker name}) с функцией Атомарного Свопа и комиссией 0%

**Comment by Spaider15** [comment]
Возьмусь
