### ISSUE TITLE
SwapAuth._initService(): TypeError: Invalid hex string

### ISSUE THREAD

**Issue by nikdementev** [swaponline/swap.react#81]
иногда при обновление страницы появляется ошибка 
чищу local storage, обновляю и все работает
<img width="531" alt="2018-06-27 17 27 49" src="https://user-images.githubusercontent.com/17093843/41959202-a0ae60ee-7a2f-11e8-8620-03b4c76baadc.png">

**Comment by noxonsu** [comment]
дубль, закрываю https://github.com/swaponline/swap.react/issues/80
