### ISSUE TITLE
Оптимизация

### ISSUE THREAD

**Issue by nikdementev** [swaponline/swap.react#817]
- [x] componentWillReceiveProps заменить на static getDerivedStateFromProps
- [ ] componentWillMount заменить на constructor
- [ ] shouldComponentUpdate добавить в все компоненты на подобии таблиц
- [x] убрать вызов reducers из table [documentation](https://redux.js.org/introduction/ecosystem#reducers)
- [ ] убрать menu из store, вынести в переменную
- [ ] убрать счетчик в IPFS  из store
- [ ] убрать currencies из store, вынести в конфигурацию
- [ ] убрать API из store
- [ ] вынести из store/core hiddenCoinList
- [x] добавить в state приложение, разрешение и запрещенные валюты и валютные пары
- [ ] декомпозировать компоненты Row, EthtoBtc и все т.п. на компонент высшего порядка и презентационный компонент (упрощает понимание работы, уменьшение дублирования кода)

**Comment by ihteandr** [comment]
componentWillReceiveProps заменить на static getDerivedStateFromProps
 componentWillReceiveProps -> getSnapshotBeforeUpdate

**Comment by ihteandr** [comment]
убрать вызов reducers из table documentation сделал

**Comment by noxonsu** [comment]
пока из этого списка ничего не делаем пока нет четкого бага который виден со стороны пользователя.
