### ISSUE TITLE
вывести текущие и прошлые свапы

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#82]
где то нужно смотреть старые свапы и состояние по ним, после начала свапа он должен пропадать из ордербука, то где его найти? если он завис то оттуда кнопку рефанд нажать предстоит

**Comment by nikdementev** [comment]
Пока так сделал, завтра подумаю над дизайном как красиво оформить и ниже добавлю историю и количество шагов
<img width="1099" alt="2018-06-30 22 31 08" src="https://user-images.githubusercontent.com/17093843/42125198-637a759a-7cb5-11e8-8191-3d4ee0d7a22a.png">
