### ISSUE TITLE
в не полноэкраном режиме нет кнопок меню

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#828]
## What is working wrong?

![image](https://user-images.githubusercontent.com/43392281/48055019-52154780-e1fa-11e8-97e0-6f5ff5317f8b.png)

Chrome
они скрываются, когда делаешь окно браузера слишком узским(узким)

**Comment by caffeinum** [comment]
по идее, у тебя должен включиться режим мобилки на такой ширине экрана, но он включается, только если перезагрузить страницу. На самом деле, если посмотреть гитхаб, у него так же происходит

**Comment by nthgness** [comment]
протестируйте, я на всех разрешениях поправил страницу wallet

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/48346483-56bf7d00-e68c-11e8-93b8-a39321eab201.png)
@nthgness в таком виде, получается, нет возможности узнать свой адрес, и перейти по ссылкам в верхней части

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/pull/1026
