### ISSUE TITLE
при ошибке отправлять данные в даталейер

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#832]
![](https://i.imgur.com/EtbVQcA.png) 
вот эту ошибку отправлять в даталейер вот таким способом "window.ga.getAll()[0].send({ hitType: 'event', eventCategory: 'fatalError', eventAction: "{сюдавставить текст ошибки}" });"

только проверь что обьект ga существует, в экстеншине его нет

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/48068157-1ae76c00-e1e3-11e8-9735-30db112bce9b.png)
есть такой экшен просто передавай другой запрос
