### ISSUE TITLE
при загрузке сделать уведомление когда подключились к ipfs

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#85]
радосное сообщение "IPFS: 4 peers connected" количество пиров можно как то получить из ipfs

**Comment by noxonsu** [comment]
А там всегда 1 пир, откуда берется вообще это?

пт, 29 июн. 2018 г., 9:27 nikdementev <notifications@github.com>:

**Comment by noxonsu** [comment]
в общем надо говорить ip или домен того star сервера к которому мы подключены. в данный момент это star.wpmix.net  . уведомление должно приходить в колокольчик

**Comment by nikdementev** [comment]
Показывает соединение и количество пользователей.
<img width="386" alt="2018-06-30 22 35 17" src="https://user-images.githubusercontent.com/17093843/42125225-e7780b64-7cb5-11e8-93ce-baab37b953af.png">
