### ISSUE TITLE
exchange: не могу создать ордер на продажу токенов, если перед этим не зайти в wallet

### ISSUE THREAD

**Issue by caffeinum** [swaponline/swap.react#852]
## What is working wrong?

Нельзя создать ордер на продажу своп-токенов

## What should happen instead?

Нужно обновлять баланс

## Steps to reproduce

https://testnet.swap.online/swap-btc

Создать ордер на продажу токенов

Не получится, потому что система думает, что баланс ноль

## Does this affect atomic swap flow?

- [ ] yes
- [x] no

## Are real funds at risk?

- [ ] yes
- [x] no

## Screenshots

![image](https://user-images.githubusercontent.com/1909384/48198671-a50e0c80-e36a-11e8-807d-0d236596bb63.png)
![image](https://user-images.githubusercontent.com/1909384/48198676-ab03ed80-e36a-11e8-89bd-1f57cc8f30a4.png)

**Comment by nikdementev** [comment]
![image](https://user-images.githubusercontent.com/17093843/48200572-9c203980-e370-11e8-90d1-2b067f80dbda.png)
67 строку добавить вместо 78
