### ISSUE TITLE
Custom fee value;

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.react#872]
Добавить ползунок для ручного выставления fee при отправке или свопе.

**Comment by noxonsu** [comment]
имхо лучше чтоб транза замайнилась, ползунок обычно принимает две позиции - быстро и медленно. я бы не хотел чтоб можно было медленно, а лишняя нагрузки интерфейса для профи нужна, на которых мы не расчитываем

**Comment by caffeinum** [comment]
можно превратить таск в "сделать, чтоб можно было менять fee через консоль"

```
swapApp.swaps.BTC.feeValue = 15000
```

по идее так сработает, а можно добавить метод setFee

**Comment by noxonsu** [comment]
![](https://airdb.wpmix.net/Telegram_2018-12-20_23-29-26db17218e-de45-43fb-a5b0-34c8c682fb50.png) в интерфейсе как то так должно быть. normal, fast, extrafast
