### ISSUE TITLE
Динамическое обновление баланса с учетом неподтвержденного в модалке withdraw

### ISSUE THREAD

**Issue by sdwas** [swaponline/swap.react#875]
Необходимо реализовать динамическое обновление баланса с учетом unconfirmedBalance при открытии формы и при нажатии кнопки transfer (непосредственно перед отправкой запросить баланс и сделать проверку).

Можно посмотреть как я реализовал похожий функционал для addOffer: #728 #864

**Comment by sdwas** [comment]
Но не учитывается unconfirmedBalance. В этом и есть суть таска.

![screenshot_20181110_114056](https://user-images.githubusercontent.com/43396375/48296006-7feddb00-e4dd-11e8-8700-2e9c8718c908.png)

**Comment by nikdementev** [comment]
изначально в getBalance мы получаем оба прям там считай и выводи сразу нужное значение

**Comment by sdwas** [comment]
@nikdementev а как же обновление баланса в wallet? Там отдельно показывает текущий баланс и неподтвержденный.

**Comment by nikdementev** [comment]
какое это имеет отношение ты же не просто возвращаешь а кладешь в стор приложения

**Comment by sdwas** [comment]
Поэтому необходимо извлечь оттуда эти значения, как я сделал для addOffer. Сейчас возвращается только баланс и сразу напрямую.

**Comment by nikdementev** [comment]
Почитай про это [redux](https://redux.js.org/)

**Comment by caffeinum** [comment]
@nikdementev я не понял, при чем тут это?

unconfirmedBalance это важная переменная, она нужна по всему приложению, как ты предлагаешь это решить?

**Comment by nikdementev** [comment]
она и так доступна всему приложению) @caffeinum

**Comment by sdwas** [comment]
Я ведь и предлагаю триггерить обновление баланса, а затем извлекать balance и unconfirmedBalance в @connect из coinData

**Comment by noxonsu** [comment]
Делаем как @sdwas в addOffer, @Pasha8914 если не понятно уточни в личке у него
