### ISSUE TITLE
Alternative destination address

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/swap.react#88]
In order to speed up the swap and make the protocol cheaper to use on the website, it would be amazing to be able to provide an alternative destination address for the swap.

Let's say I want to exchange 1 BTC for 10 ETH, I want to have the ETH to be transferred to my offline wallet directly rather than having to pay for transaction twice. Specially if I do not want to keep the exchanged ETH in browser wallet in the first place.

**Comment by noxonsu** [comment]
technically it is possible. We need UX research, where user will be set this addresses?

**Comment by noxonsu** [comment]
Я думаю при создании ордера сделать ссылку add destination addres. И так же при конфирм свапа на первом экране где 10 сек таймер нужно указывать дестинецшн

**Comment by caffeinum** [comment]
А кто платит газ за withdraw?

**Comment by vladiuz1** [comment]
можно брать другую крипту (например свопы) за такие сделки, и тогда мы ее заканчиваем за тебя, 

обозвать это Order Booster - который платный, позволяет посылать на альт адрес, не требует онлайновости.

**Comment by noxonsu** [comment]
немного спутано, давайте отдельно альтернатив дестинейшин адрес, офлайновость обсуждать https://github.com/swaponline/swap.react/issues/326
