### ISSUE TITLE
Если на балансе ноль то не получается нажать ексчендж и сенд

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#881]
Доступны кнопки send и exchange но при клике вообще ничего не происходит. кнопки работают только там где есть баланс. но ведь exchange должен работать в любом случае (если есть например биток) а так же надо давать понять почему не работают кнопки или дисеблить их.

**Comment by caffeinum** [comment]
это же из UX Audit

**Comment by caffeinum** [comment]
вроде сделали
