### ISSUE TITLE
add offer: логическая ошибка: amount must be bigger then your balance 

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#886]
![](https://airdb.wpmix.net/chrome_2018-11-12_19-12-44.png )

**Comment by noxonsu** [comment]
ошибка красным тектом вообще не понятно от чего появляется и вообще не является ошибкой

**Comment by caffeinum** [comment]
там есть две ошибки: пытаешься вывести больше своих денег или меньше, чем minAmount.

сообщение для них одно

**Comment by noxonsu** [comment]
ага сообщение "Сумма должна быть больше чем на вашем балансе". Надо поменять на "Сумма должна быть меньше, чем ваш баланс"
