### ISSUE TITLE
https://swap.online/history SENT и RECIVED показывают recived

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#904]
![](https://airdb.wpmix.net/chrome_2018-11-13_17-35-12e81f0af8-c7a4-45b9-af24-ef6c65d1e285.png)

**Comment by Pasha8914** [comment]
как повторить?

![image](https://user-images.githubusercontent.com/43392281/48463174-eac54c00-e826-11e8-8e03-ea195bc81b0e.png)


![image](https://user-images.githubusercontent.com/43392281/48463189-f44eb400-e826-11e8-8706-89b728a2bb4d.png)

![image](https://user-images.githubusercontent.com/43392281/48463207-0597c080-e827-11e8-9795-2fac09f5868d.png)
