### ISSUE TITLE
проблема с входом на мейннет

### ISSUE THREAD

**Issue by Pasha8914** [swaponline/swap.react#954]
п 1. чистим локал стораж
п2. чистим хэш
п3. импортируем ключи - неверный ключ
ждем 1000 лет ничего не происходит
Хром

![image](https://user-images.githubusercontent.com/43392281/48674880-133da500-eb9d-11e8-85a5-dc760a2b23ee.png)

это в секундах
![image](https://user-images.githubusercontent.com/43392281/48674882-189aef80-eb9d-11e8-9fea-32d12e566861.png)

![image](https://user-images.githubusercontent.com/43392281/48674886-23558480-eb9d-11e8-98c9-22e194638de1.png)

![image](https://user-images.githubusercontent.com/43392281/48674975-767c0700-eb9e-11e8-880d-d7c376f732b1.png)

НИКОГДА НЕ ПОПАДЕШЬ НА САЙТ, пока не почистишь хэш

**Comment by noxonsu** [comment]
в консоли что? ты импортируешь ключи от тестнета?

**Comment by nikdementev** [comment]
да есть такой баг Саш вставь вместо биткойна ключа адресс)) и все будешь долго смотреть на ничего)
