### ISSUE TITLE
partial: пройтись по чеклисту

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#963]
1. я захожу на страницу /partial
2. в другом браузере создаю оредр с партиал
![](https://airdb.wpmix.net/chrome_2018-11-19_22-12-4595f4a040-0e97-4bee-baae-377b599f23ac.png) 

в форме не учлось.

3. если менять направление обмна btc на eth то появляется варнинг с NaN

4. если обновить страницу то тоже ничего не показывает

**Comment by noxonsu** [comment]
нужно больше дебага. я написал тест кейс для проверки, нужно записать видео, где все это видно

- [ ] общее. боб создает ордер на продажу 0.5 ETH по какойто цене
- [ ] алиса каким то образом находит этот ордер через /partial старутует и свап проходит корректно на нужную самму
- [ ] очищаем состояние, нет партиал ордеров, отткрыты браузер алиса и браузер боб
- [ ] алиса открывает /partial там "я отдаю биткоин, получаю эфир". показывает no offer
- [ ] боб создает партиал ордер продает 2 эфира за сколько то биткоинов
- [ ] у алисы сразу же меняется Max amount for offer: 2 ETH
- [ ] алиса воодит сумму 1 эфир, ей калькулируется стоимость в BTC
- [ ] алиса меняет направление обмена с BTC-ETH на другой например ETH-SWAP - ей показывает no offers и стоит что доступно 0 SWAP
- [ ] алиса перезагружает страницу и снова выстанавливается BTC-ETH направление и видно опять  что доступно до 2 ETH
- [ ] боб убирает свой ордер, у алисы становится Max amount for offer: 0 ETH и пишет no offer
- [ ] боб создает ордер на продажу 1 ETH за 1 BTС без установки галочки partial и он не появляется и не обрабатывается алисы в форме
- [ ] боб убирает свой ордер и создает такой же на продажу 1 ETH за 1 BTC но partial
- [ ] сара в третьем браузере создает ордер на продажу 2 ETH за 5 BTC (очень не выгодный для алисы, еще невыгоднее курс даже чем боба)
- [ ] алиса видит что доступно до 2 ETH
- [ ] алиса вводит что хочет купить 0.5 эфира, калькулятор показывает 0.5 BTC 
- [ ] алиса вводит 1.5 ETH калькулятор показывает  3.75 BTC
- [ ] нажимает start и начинает обмениватся с сарой (должно застярть на моменте "пополните на 3.75 btc, потому что у тестовых аков нет битка)

**Comment by nikdementev** [comment]
> 1. я захожу на страницу /partial
> 2. в другом браузере создаю оредр с партиал
> в форме не учлось.
> 
> 1. если менять направление обмна btc на eth то появляется варнинг с NaN
> 2. если обновить страницу то тоже ничего не показывает

он и не будет тебе ничего показывать ты вводить значение начни

**Comment by noxonsu** [comment]
да все равно не рабоатет вводи не вводи, запиши видео по чек лесту, обсуждение бесполезно

**Comment by shendel** [comment]
я просто тыкнул в галочки.... палево :-(

**Comment by shendel** [comment]
![image](https://user-images.githubusercontent.com/1880211/48805909-c4714600-ed29-11e8-9e5b-1858d06eb305.png)

там нету перерасчета в той реализации ... это надо в кор все вместе с обработкой запросов на "partial"

**Comment by shendel** [comment]
https://github.com/swaponline/swap.react/commit/6c8ac6837288b49480765734c583bd88bdc48957#r31373860

**Comment by nikdementev** [comment]
https://github.com/swaponline/swap.react/pull/1003
добавил теперь все как ты хочешь

**Comment by shendel** [comment]
Видео на три части резделенно (прерывало из-за F12) переснимать нету смысла там и так будет видно какие баги
https://www.youtube.com/watch?v=u6VRuAvM4Wo&feature=youtu.be
https://www.youtube.com/watch?v=wCt_IxpqW44&feature=youtu.be
https://www.youtube.com/watch?v=WVm30oLlLz4&feature=youtu.be

1. При заходе на страницу /partial, когда уже заранее есть ордер (ETH->BTC), в полях формы стоит по нулям, и кнопка START активна. При нажатии на кропку - создает ордер продажи 0 ETH за 0 BTC и начинает свап по этому ордеру (само-собой с предсказуемым исходом)

2. При появлении третьей стороны (Сары) не учитывает ее предложения, хотя они доходят до Алисы (видны в консоле)

**Comment by shendel** [comment]
3. Нужно дать возможность пользователю указывать не только кол-во битка, но и кол-во эфира (для примера пары ETH->BTC)

**Comment by nikdementev** [comment]
1 - 0 да надо убрать
2 - учитывает самую выгодную комиссию
3 - нет

**Comment by shendel** [comment]
2. Нужно еще тогда учитывать кол-во, которое нужно алисе (отсеивать ордера, в которых меньше нужного)
3. Леха такое уже в черновике добавил - возможность запросить ордер, указав или buyAmount или sellAmount

**Comment by shendel** [comment]
2. И в поле aviable указывать максимальное значение из всех ордеров (без учета коммисии) - в данном случае (с Сарой) - там должно быть 3

**Comment by shendel** [comment]
Тоесть Алиса максимально может купить 3 эфира, если она вводит что ей надо 0.5 или 1 - то показывает ставку Боба, если больше - ставку Сары
