### ISSUE TITLE
import keys  на странице  балансов

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#97]
в продолжение https://github.com/swaponline/swap.react/issues/95 сделай ссылку mport keys при клике открывается окно где надо ввести приватник (биткоин и эфир) который после нажатия import перезаписывает те, что в локал сторадже. дополнительно должен сразу проверятся приватник биткоина, что он не тестнетовский (если сидим в мейннете) и наоборот.

если мы в мейннете то если на балансе есть какиетто деньги огромными красными буквами писать, "Your balances is not empty! This operation can destroy funds"

в форме дописать "⚠ your current keys will be owerwrited. You lose your funds!"

**Comment by noxonsu** [comment]
сделать с перезагрузкой страницы

**Comment by nikdementev** [comment]
75e9dd6de894b5088e23cdc299e24c5564cd6913

**Comment by nikdementev** [comment]
63b7fa44e79d0e163d0113b12528d8e1590da8df
