### ISSUE TITLE
swap: alternative destenation adres когда я покупаю токен кнопка "confirm adress" не срабатывает (на другой стороне мобила надроид)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#986]
застряло тут
![](https://airdb.wpmix.net/chrome_2018-11-22_00-25-09b5d42e76-c338-482c-be5e-b7376ea66eeb.png)

**Comment by noxonsu** [comment]
это как то связано с отсутствием sign со второй стороны

**Comment by shendel** [comment]
Фокус (клик) на поле ввода адреса превращает TimerButton в Button? (Должен исчезнуть цифровой отсчет "CONFIRM ADDRESS 1...15" => "CONFIRM ADDRESS"
)

**Comment by shendel** [comment]
![screenshot_20181122-235003](https://user-images.githubusercontent.com/1880211/48921947-4b522a00-eeb4-11e8-885a-47d30e687338.png)
![screenshot_20181122-235030](https://user-images.githubusercontent.com/1880211/48921949-4beac080-eeb4-11e8-8d7c-59f7cdc2a1b7.png)
![screenshot_20181122-235143](https://user-images.githubusercontent.com/1880211/48921950-4beac080-eeb4-11e8-8951-ce11b929a1aa.png)
![screenshot_20181122-235257](https://user-images.githubusercontent.com/1880211/48921951-4beac080-eeb4-11e8-9125-d0c8bf579181.png)
![screenshot_20181122-235507](https://user-images.githubusercontent.com/1880211/48921952-4c835700-eeb4-11e8-87ad-5f03ef50fb20.png)
![screenshot_20181122-235521](https://user-images.githubusercontent.com/1880211/48921954-4c835700-eeb4-11e8-9ea3-adcbd3045bac.png)
![screenshot_20181122-235540](https://user-images.githubusercontent.com/1880211/48921955-4c835700-eeb4-11e8-8d1a-fae762545688.png)
![screenshot_20181122-235642](https://user-images.githubusercontent.com/1880211/48921956-4c835700-eeb4-11e8-99a5-4836291d3b44.png)
![screenshot_20181122-235753](https://user-images.githubusercontent.com/1880211/48921957-4d1bed80-eeb4-11e8-9f94-be76738a6ff3.png)
![screenshot_20181122-235907](https://user-images.githubusercontent.com/1880211/48921958-4d1bed80-eeb4-11e8-8e02-80fd79896f7d.png)
![screenshot_20181123-000030](https://user-images.githubusercontent.com/1880211/48921959-4db48400-eeb4-11e8-9d29-f4cfe4ade3b6.png)
![screenshot_20181123-000436](https://user-images.githubusercontent.com/1880211/48921960-4db48400-eeb4-11e8-9279-f0b58a93b126.png)
![screenshot_20181123-000511](https://user-images.githubusercontent.com/1880211/48921961-4db48400-eeb4-11e8-95b5-7b45b26bafed.png)

Странное поведение... частично удалось воспроизвести
Если ничего не делать - отсчет на кнопке доходит до 1 и "останавливается" - не обновляется состояние/или контейнер (Swap) его не перехватывает. Если нажать на поле ввода адреса (после того как закончился отсчет) - идет моментальная отрисовка и продолжение свапа

Видео (ордер выставил мобилой)
https://youtu.be/g1Ktcj_yrpo

В целом где проблема ясно - взял в работу. Завтра будет фикс

**Comment by shendel** [comment]
Отправил пул
https://github.com/swaponline/swap.react/pull/1006
