### ISSUE TITLE
после создания ордера надо в стакан кидать где ордера те-же какой я поставил (чтоб увидеть его)

### ISSUE THREAD

**Issue by noxonsu** [swaponline/swap.react#99]
Vlad, [05.07.18 14:32]
там конфуз, я ставлю ордер а потом меня кидает в другой стакан

Vlad, [05.07.18 14:33]
и там пусто

Vlad, [05.07.18 14:33]
надо в стакан кидать где ордера те-же какой я поставил

Noxon ⚡️, [05.07.18 14:37]
[В ответ на Vlad]
это старый глюк восприятия. на самом деле все ок, просто ты видиш ьсвои ордера в "своих ордерах а тебе показываются встречные, ведь ты же продаешь эфир"

**Comment by caffeinum** [comment]
Давайте аккуратно разберемся. Я предлагаю выписать для себя небольшую справку.

Во-первых, внутри кор сейчас следующие правила:
```javascript
// order:
{
  isMy: true
  buyCurrency: "ETH"
  sellCurrency: "BTC"
}
```

Это означает, что я ПОКУПАЮ ETH, ПРОДАЮ BTC, и далее я буду это называть ПРЯМЫМ направлением.

Тот же ордер в чужом ордербуке будет:
```javascript
// order:
{
  isMy: false
  buyCurrency: "ETH"
  sellCurrency: "BTC"
}
```

То есть поля buy и sell относятся только к создателю ордера. Для другого человека это неактуально, потому что он продает эфир, а покупает биткоин. То есть, для него направление ордера будет ОБРАТНЫМ.

# Прямые и обратные ордера

Для любой пары введем базовую и вторичную валюту. В ETH-BTC и TOKEN-BTC очевидно базовой будет биткоин. Продажа ETH будет ПРЯМЫМ обменом, а покупка – ОБРАТНЫМ. Запомнить можно так: раз она вторичная, то ее нужно ПРОДАТЬ, чтоб иметь надежную базовую валюту. :)

# bids / asks

В трейдерском мире используется терминология bid/ask, что означает заявку на покупку и на продажу соответственно. Запомнить тоже легко, *B*ID = *BUY*, A*S*K = SELL. То есть, bid = предложение купить ваши ETH от продавца, а ASK = просьба купить у него ETH. Опять логика со вторичной валютой нам помогает.

# Новый формат
Итого, я предлагаю для ордербука конвертировать заявки в примерно следующий формат:

```javascript
// order:
{
  type: BID | ASK,
  pair: "ETH-BTC", // всегда в таком порядке
  price: 0.07, // всегда цена ETH в BTC,
  amount: 10 // всегда количество ETH
}
```

Скрипты для конвертации есть у меня внутри бота в репо caffeinum/swap.core, позже опубликую.

@noxonsu @nikdementev

**Comment by nikdementev** [comment]
db91892f3c7a6cc8d9a2b1c782bf2a1a93d33e03
